In [3]:
import pandas as pd

df3 = pd.read_csv(
    "UserReviews43DylanDMB.csv",
    encoding="latin1"
    # Use latin1 encoding so pandas can correctly read special characters in the CSV file
)

df4 = pd.read_csv(
    "ExpertReviewsClean43LIWCforDMB.csv",
    encoding="latin1"
    # Use latin1 encoding so pandas can correctly read special characters in the CSV file
)

C:\Users\dylansodhi\AppData\Local\Temp\ipykernel_2648\611161027.py:3: DtypeWarning: Columns (0: idvscore, 1: thumbsUp, 2: thumbsTot) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv(

In [4]:
# to see the columns of each files:
print(df3.columns.tolist())
print(df4.columns.tolist())

['url', 'idvscore', 'reviewer', 'dateP', 'Rev', 'thumbsUp', 'thumbsTot', 'WC', 'Analytic', 'Clout', 'Authentic', 'Tone', 'WPS', 'Sixltr', 'Dic', 'function', 'pronoun', 'ppron', 'i', 'we', 'you', 'shehe', 'they', 'ipron', 'article', 'prep', 'auxverb', 'adverb', 'conj', 'negate', 'verb', 'adj', 'compare', 'interrog', 'number', 'quant', 'affect', 'posemo', 'negemo', 'anx', 'anger', 'sad', 'social', 'family', 'friend', 'female', 'male', 'cogproc', 'insight', 'cause', 'discrep', 'tentat', 'certain', 'differ', 'percept', 'see', 'hear', 'feel', 'bio', 'body', 'health', 'sexual', 'ingest', 'drives', 'affiliation', 'achieve', 'power', 'reward', 'risk', 'focuspast', 'focuspresent', 'focusfuture', 'relativ', 'motion', 'space', 'time', 'work', 'leisure', 'home', 'money', 'relig', 'death', 'informal', 'swear', 'netspeak', 'assent', 'nonflu', 'filler', 'AllPunc', 'Period', 'Comma', 'Colon', 'SemiC', 'QMark', 'Exclam', 'Dash', 'Quote', 'Apostro', 'Parenth', 'OtherP']
['url', 'idvscore', 'reviewer', 'dateP', 'Rev', 'WC', 'Analytic', 'Clout', 'Authentic', 'Tone', 'WPS', 'Sixltr', 'Dic', 'function', 'pronoun', 'ppron', 'i', 'we', 'you', 'shehe', 'they', 'ipron', 'article', 'prep', 'auxverb', 'adverb', 'conj', 'negate', 'verb', 'adj', 'compare', 'interrog', 'number', 'quant', 'affect', 'posemo', 'negemo', 'anx', 'anger', 'sad', 'social', 'family', 'friend', 'female', 'male', 'cogproc', 'insight', 'cause', 'discrep', 'tentat', 'certain', 'differ', 'percept', 'see', 'hear', 'feel', 'bio', 'body', 'health', 'sexual', 'ingest', 'drives', 'affiliation', 'achieve', 'power', 'reward', 'risk', 'focuspast', 'focuspresent', 'focusfuture', 'relativ', 'motion', 'space', 'time', 'work', 'leisure', 'home', 'money', 'relig', 'death', 'informal', 'swear', 'netspeak', 'assent', 'nonflu', 'filler', 'AllPunc', 'Period', 'Comma', 'Colon', 'SemiC', 'QMark', 'Exclam', 'Dash', 'Quote', 'Apostro', 'Parenth', 'OtherP']

In [5]:
# to see the first 20 rows of title for each file
print(df3["reviewer"].head(20))
print(df4["reviewer"].head(20))

0       'Longbottom94'
1            'MartinB'
2             'Jaakko'
3              'CapoR'
4           'OrwellB.'
5             'RONGIU'
6        'Tokyochuchu'
7           'Fenrir81'
8            'cabrita'
9           'farknash'
10           'Spangle'
11         'Nesbitt10'
12        'TrilobiteG'
13          'Luxocell'
14        'TomBeltran'
15            'BrettT'
16         'Voltronix'
17     'LatinCritic13'
18       'MattBrady99'
19         'Ralfbergs'
Name: reviewer, dtype: str
0          "Andrew O'Hehir"
1              'A.O. Scott'
2                      None
3             'Noel Murray'
4         'Joshua Rothkopf'
5                      None
6        'Bill Goodykoontz'
7         'Kimberley Jones'
8           'Peter Travers'
9            'V.A. Musetto'
10        'David Hiltbrand'
11            'Roger Ebert'
12       'Michael Phillips'
13                'Ty Burr'
14             'Shawn Levy'
15                     None
16     'James Berardinelli'
17                     None
18             'Rick Groen'
19                     None
Name: reviewer, dtype: str

In [6]:
# Keep only the columns needed for the analysis and remove all unnecessary columns
# axis=1 tells pandas to remove columns instead of rows
df3 = df3.drop(df3.columns[5:], axis=1) 
df4 = df4.drop(df4.columns[7:], axis=1)

In [7]:
# Check the number of rows and columns in the dataframe
print(df3.shape)
print(df4.shape)

(319662, 5)
(238973, 7)

In [8]:
df3.head(20)

,url,idvscore,reviewer,dateP,Rev
0,https://www.metacritic.com/movie/bronson,8.0,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...
1,https://www.metacritic.com/movie/bronson,9.0,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...
2,https://www.metacritic.com/movie/bronson,10.0,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...
3,https://www.metacritic.com/movie/bronson,6.0,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...
4,https://www.metacritic.com/movie/bronson,8.0,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...
5,https://www.metacritic.com/movie/bronson,8.0,'RONGIU',"'Jun 10, 2011'","'Sorry, machine translation. The stage, by Ni..."
6,https://www.metacritic.com/movie/bronson,8.0,'Tokyochuchu',"'Nov 30, 2013'","'Bronson is a great, extremely strange movie ..."
7,https://www.metacritic.com/movie/bronson,7.0,'Fenrir81',"'Apr 22, 2011'",'Despite being flawed by a weak narrative str...
8,https://www.metacritic.com/movie/bronson,4.0,'cabrita',"'Aug 10, 2012'",'If valhalla rising was a weak version of agg...
9,https://www.metacritic.com/movie/bronson,10.0,'farknash',"'Aug 19, 2011'",'http://mikesharkey.blogspot.com/2009/04/igiz...
10,https://www.metacritic.com/movie/bronson,4.0,'Spangle',"'Mar 6, 2015'","'Extremely claustrophobic, Bronson is possibl..."
11,https://www.metacritic.com/movie/bronson,8.0,'Nesbitt10',"'Jul 4, 2013'",'One thing is for certain: Bronson invites yo...
12,https://www.metacritic.com/movie/bronson,5.0,'TrilobiteG',"'Jan 6, 2016'","'Got to say, I m rather disappointed. To begi..."
13,https://www.metacritic.com/movie/bronson,3.0,'Luxocell',"'Jan 16, 2015'","'Call me simple minded if you desire, but I r..."
14,https://www.metacritic.com/movie/bronson,5.0,'TomBeltran',"'May 27, 2013'",'Posted on 5/20/13 10:15 AM\rTom hardy gives ...
15,https://www.metacritic.com/movie/bronson,7.0,'BrettT',"'Jun 8, 2014'","'Well acted and gritty, Bronson is a good fil..."
16,https://www.metacritic.com/movie/bronson,8.0,'Voltronix',"'Aug 14, 2014'","'Tom Hardy nails it in this role, partially d..."
17,https://www.metacritic.com/movie/bronson,9.0,'LatinCritic13',"'Apr 7, 2019'",'Bronson is defined as a film that s notoriou...
18,https://www.metacritic.com/movie/bronson,9.0,'MattBrady99',"'Sep 9, 2015'",'Bronson follows the life of notorious prison...
19,https://www.metacritic.com/movie/bronson,5.0,'Ralfbergs',"'Jun 25, 2016'","'I really liked TOm Hardy s performance here,..."

In [9]:
df4.head(20)

,url,idvscore,reviewer,dateP,Rev,WC,Analytic
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46
5,https://www.metacritic.com/movie/bronson,80.0,None,None,"'He s neither victim nor hero, but a man who,...",17,59.32
6,https://www.metacritic.com/movie/bronson,80.0,'Bill Goodykoontz',None,"'This is unhinged genius, an amazing piece of...",16,93.26
7,https://www.metacritic.com/movie/bronson,78.0,'Kimberley Jones',None,'Refn s artful and energetic film never goes ...,12,62.04
8,https://www.metacritic.com/movie/bronson,75.0,'Peter Travers',None,'This movie and Hardy s electrifying performa...,13,65.46
9,https://www.metacritic.com/movie/bronson,75.0,'V.A. Musetto',None,'Tom Hardy gives an amazing performance as Pe...,20,99.00
10,https://www.metacritic.com/movie/bronson,75.0,'David Hiltbrand',None,"'The tone is surreal, at once visceral and cl...",20,78.30
11,https://www.metacritic.com/movie/bronson,75.0,'Roger Ebert',None,"'It is 92 minutes of rage, acted by Tom Hardy.'",10,93.26
12,https://www.metacritic.com/movie/bronson,75.0,'Michael Phillips',None,"'Hardy is remarkable, however. This is an act...",20,87.27
13,https://www.metacritic.com/movie/bronson,75.0,'Ty Burr',None,'Bronson isn t a story in the traditional sen...,30,99.00
14,https://www.metacritic.com/movie/bronson,75.0,'Shawn Levy',None,"'It s played with real zest and energy, and i...",24,27.87
15,https://www.metacritic.com/movie/bronson,70.0,None,None,"'With an intelligent, provocative and stylize...",27,99.00
16,https://www.metacritic.com/movie/bronson,63.0,'James Berardinelli',None,'It s lively and vivid but ends up leaving th...,26,88.90
17,https://www.metacritic.com/movie/bronson,60.0,None,None,"'Too smart/arty for the slasher set, and too ...",31,63.48
18,https://www.metacritic.com/movie/bronson,50.0,'Rick Groen',None,'Bronson is one of those based on a true stor...,26,99.00
19,https://www.metacritic.com/movie/bronson,30.0,None,None,"'Despite the artistic flourishes, this is sti...",26,97.95

In [10]:
# Check how many missing values each column has
print(df3.isnull().sum())

url            0
idvscore    3404
reviewer    3407
dateP       3413
Rev         3413
dtype: int64

In [11]:
print(df4.isnull().sum())

url         0
idvscore    2
reviewer    2
dateP       2
Rev         2
WC          0
Analytic    0
dtype: int64

In [12]:
# Check how many completely duplicated rows exist
print(df3.duplicated().sum())

929

In [13]:
print(df4.duplicated().sum())

27

In [14]:
# Show rows in df3 that contain at least one missing value
display(df3[df3.isnull().any(axis=1)].head(20))

,url,idvscore,reviewer,dateP,Rev
29,https://www.metacritic.com/movie/a-screaming-man,NaN,NaN,NaN,NaN
30,https://www.metacritic.com/movie/lovers-of-hate,NaN,NaN,NaN,NaN
34,https://www.metacritic.com/movie/viva-riva!,NaN,NaN,NaN,NaN
130,https://www.metacritic.com/movie/september-11,NaN,NaN,NaN,NaN
134,https://www.metacritic.com/movie/catching-out,NaN,NaN,NaN,NaN
185,https://www.metacritic.com/movie/norman,NaN,NaN,NaN,NaN
187,https://www.metacritic.com/movie/dumbstruck,NaN,NaN,NaN,NaN
277,https://www.metacritic.com/movie/the-catechism...,NaN,NaN,NaN,NaN
296,https://www.metacritic.com/movie/the-real-cancun,NaN,NaN,NaN,NaN
297,https://www.metacritic.com/movie/the-era-of-va...,NaN,NaN,NaN,NaN
762,https://www.metacritic.com/movie/emerald-cowboy,NaN,NaN,NaN,NaN
867,https://www.metacritic.com/movie/footprints,NaN,NaN,NaN,NaN
1049,https://www.metacritic.com/movie/a-love-affair...,NaN,NaN,NaN,NaN
1208,https://www.metacritic.com/movie/alls-faire-in...,NaN,NaN,NaN,NaN
1234,https://www.metacritic.com/movie/a-warriors-heart,NaN,NaN,NaN,NaN
1235,https://www.metacritic.com/movie/brothers-justice,NaN,NaN,NaN,NaN
1525,https://www.metacritic.com/movie/the-big-bang,NaN,NaN,NaN,NaN
2012,https://www.metacritic.com/movie/the-greening-...,NaN,NaN,NaN,NaN
2241,https://www.metacritic.com/movie/certifiably-j...,NaN,NaN,NaN,NaN
2242,https://www.metacritic.com/movie/salvation-bou...,NaN,NaN,NaN,NaN

In [15]:
display(df4[df4.isnull().any(axis=1)].head(20))

,url,idvscore,reviewer,dateP,Rev,WC,Analytic
41664,https://www.metacritic.com/movie/whiteout,NaN,NaN,NaN,NaN,0,0.0
157759,https://www.metacritic.com/movie/micmac---au-f...,NaN,NaN,NaN,NaN,0,0.0

In [16]:
df4.head(50)

,url,idvscore,reviewer,dateP,Rev,WC,Analytic
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46
5,https://www.metacritic.com/movie/bronson,80.0,None,None,"'He s neither victim nor hero, but a man who,...",17,59.32
6,https://www.metacritic.com/movie/bronson,80.0,'Bill Goodykoontz',None,"'This is unhinged genius, an amazing piece of...",16,93.26
7,https://www.metacritic.com/movie/bronson,78.0,'Kimberley Jones',None,'Refn s artful and energetic film never goes ...,12,62.04
8,https://www.metacritic.com/movie/bronson,75.0,'Peter Travers',None,'This movie and Hardy s electrifying performa...,13,65.46
9,https://www.metacritic.com/movie/bronson,75.0,'V.A. Musetto',None,'Tom Hardy gives an amazing performance as Pe...,20,99.00
10,https://www.metacritic.com/movie/bronson,75.0,'David Hiltbrand',None,"'The tone is surreal, at once visceral and cl...",20,78.30
11,https://www.metacritic.com/movie/bronson,75.0,'Roger Ebert',None,"'It is 92 minutes of rage, acted by Tom Hardy.'",10,93.26
12,https://www.metacritic.com/movie/bronson,75.0,'Michael Phillips',None,"'Hardy is remarkable, however. This is an act...",20,87.27
13,https://www.metacritic.com/movie/bronson,75.0,'Ty Burr',None,'Bronson isn t a story in the traditional sen...,30,99.00
14,https://www.metacritic.com/movie/bronson,75.0,'Shawn Levy',None,"'It s played with real zest and energy, and i...",24,27.87
15,https://www.metacritic.com/movie/bronson,70.0,None,None,"'With an intelligent, provocative and stylize...",27,99.00
16,https://www.metacritic.com/movie/bronson,63.0,'James Berardinelli',None,'It s lively and vivid but ends up leaving th...,26,88.90
17,https://www.metacritic.com/movie/bronson,60.0,None,None,"'Too smart/arty for the slasher set, and too ...",31,63.48
18,https://www.metacritic.com/movie/bronson,50.0,'Rick Groen',None,'Bronson is one of those based on a true stor...,26,99.00
19,https://www.metacritic.com/movie/bronson,30.0,None,None,"'Despite the artistic flourishes, this is sti...",26,97.95
20,https://www.metacritic.com/movie/bronson,30.0,'J. Hoberman',None,"'Bronson is essentially a faux-operatic, musi...",17,97.21
21,https://www.metacritic.com/movie/bronson,25.0,'Walter Addiego',None,'It s an assaultive work about an assaultive ...,9,98.87
22,https://www.metacritic.com/movie/disgrace,100.0,'Roger Ebert',None,'This is such a rare movie. Its characters ar...,14,14.58
23,https://www.metacritic.com/movie/disgrace,90.0,'Stephen Holden',None,'Mr. Malkovich is one of the few actors capab...,14,99.00
24,https://www.metacritic.com/movie/disgrace,83.0,'Peter Rainer',None,"'As fiercely unsentimental as Disgrace is, it...",29,69.54
25,https://www.metacritic.com/movie/disgrace,80.0,None,None,"'The austere economy of Coetzee s writing, cr...",24,99.00
26,https://www.metacritic.com/movie/disgrace,80.0,'Bob Mondello',None,'John Malkovich has played some odd ducks in ...,32,95.70
27,https://www.metacritic.com/movie/disgrace,80.0,None,None,'Surprisingly successful adaptation of J. M. ...,10,98.58
28,https://www.metacritic.com/movie/disgrace,75.0,'V.A. Musetto',None,'I cannot tell a lie. I derive great satisfac...,13,43.96
29,https://www.metacritic.com/movie/disgrace,75.0,'Lisa Schwarzbaum',None,'Newcomer Jessica Haines is transparent and h...,22,98.34
30,https://www.metacritic.com/movie/disgrace,75.0,'Ty Burr',None,"'It s a harsh experience, at times engrossing...",32,93.26
31,https://www.metacritic.com/movie/disgrace,70.0,'Eddie Cockrell',None,'Anchored by another marvelously quirky yet d...,39,95.33
32,https://www.metacritic.com/movie/disgrace,70.0,'J.R. Jones',None,'The movie eventually begins to wilt under th...,40,99.00
33,https://www.metacritic.com/movie/disgrace,70.0,'Joe Morgenstern',None,"'Nothing is simple in this film, which ramifi...",28,98.76
34,https://www.metacritic.com/movie/disgrace,70.0,None,None,"'Absorbing but often bloodless and, frankly, ...",7,5.89
35,https://www.metacritic.com/movie/disgrace,67.0,'Keith Phipps',None,'After a compelling opening act and some shoc...,24,99.00
36,https://www.metacritic.com/movie/disgrace,60.0,None,None,'The story often appears a little unreal.',7,99.00
37,https://www.metacritic.com/movie/disgrace,60.0,'Philip Kennicott',None,'Is it a great movie? John Malkovich s portra...,28,93.26
38,https://www.metacritic.com/movie/disgrace,40.0,None,None,'A frustrating film full of overplayed men-as...,28,68.29
39,https://www.metacritic.com/movie/disgrace,40.0,'Joe Neumaier',None,"'The film, unfortunately, hasn t the depth Ma...",12,99.00
40,https://www.metacritic.com/movie/a-screaming-man,90.0,'Manohla Dargis',"'Apr 14, 2011'","'It s a modest film, if only in scale and app...",42,97.73
41,https://www.metacritic.com/movie/a-screaming-man,83.0,'Eric Kohn',"'Apr 12, 2011'","'At its core, A Screaming Man emphasizes the ...",27,93.26
42,https://www.metacritic.com/movie/a-screaming-man,80.0,'Robert Koehler',"'May 26, 2013'",'Haroun s tender but unsentimental regard for...,25,93.26
43,https://www.metacritic.com/movie/a-screaming-man,80.0,'David Fear',"'Apr 12, 2011'",'A collective sense of psychological turmoil ...,43,99.00
44,https://www.metacritic.com/movie/a-screaming-man,70.0,None,"'Apr 12, 2011'",'Haroun is uninterested in big war scenes and...,17,97.21
45,https://www.metacritic.com/movie/a-screaming-man,60.0,None,"'Apr 16, 2011'",'The first half-hour is as evocative as (and ...,38,95.37
46,https://www.metacritic.com/movie/a-screaming-man,60.0,'Joe Neumaier',"'Apr 15, 2011'",'Haroun is achingly conscious of day-to-day d...,21,29.30
47,https://www.metacritic.com/movie/a-screaming-man,50.0,'Nick Pinkerton',"'Apr 12, 2011'",'The characterizations never comfortably acco...,18,46.37
48,https://www.metacritic.com/movie/lovers-of-hate,91.0,'Eric Kohn',"'Feb 10, 2011'",'Never indulging in outright scare tactics or...,21,93.26
49,https://www.metacritic.com/movie/lovers-of-hate,90.0,'Jeannette Catsoulis',"'Feb 10, 2011'","'Smartly written and flawlessly acted, Lovers...",27,66.94

In [17]:
# Creates a new column by extracting the movie title from the end of the URL
df3["title_from_url"] = df3["url"].str.rsplit("/", n=1).str[-1]

In [18]:
df3.head(30)

,url,idvscore,reviewer,dateP,Rev,title_from_url
0,https://www.metacritic.com/movie/bronson,8.0,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...,bronson
1,https://www.metacritic.com/movie/bronson,9.0,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...,bronson
2,https://www.metacritic.com/movie/bronson,10.0,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...,bronson
3,https://www.metacritic.com/movie/bronson,6.0,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...,bronson
4,https://www.metacritic.com/movie/bronson,8.0,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...,bronson
5,https://www.metacritic.com/movie/bronson,8.0,'RONGIU',"'Jun 10, 2011'","'Sorry, machine translation. The stage, by Ni...",bronson
6,https://www.metacritic.com/movie/bronson,8.0,'Tokyochuchu',"'Nov 30, 2013'","'Bronson is a great, extremely strange movie ...",bronson
7,https://www.metacritic.com/movie/bronson,7.0,'Fenrir81',"'Apr 22, 2011'",'Despite being flawed by a weak narrative str...,bronson
8,https://www.metacritic.com/movie/bronson,4.0,'cabrita',"'Aug 10, 2012'",'If valhalla rising was a weak version of agg...,bronson
9,https://www.metacritic.com/movie/bronson,10.0,'farknash',"'Aug 19, 2011'",'http://mikesharkey.blogspot.com/2009/04/igiz...,bronson
10,https://www.metacritic.com/movie/bronson,4.0,'Spangle',"'Mar 6, 2015'","'Extremely claustrophobic, Bronson is possibl...",bronson
11,https://www.metacritic.com/movie/bronson,8.0,'Nesbitt10',"'Jul 4, 2013'",'One thing is for certain: Bronson invites yo...,bronson
12,https://www.metacritic.com/movie/bronson,5.0,'TrilobiteG',"'Jan 6, 2016'","'Got to say, I m rather disappointed. To begi...",bronson
13,https://www.metacritic.com/movie/bronson,3.0,'Luxocell',"'Jan 16, 2015'","'Call me simple minded if you desire, but I r...",bronson
14,https://www.metacritic.com/movie/bronson,5.0,'TomBeltran',"'May 27, 2013'",'Posted on 5/20/13 10:15 AM\rTom hardy gives ...,bronson
15,https://www.metacritic.com/movie/bronson,7.0,'BrettT',"'Jun 8, 2014'","'Well acted and gritty, Bronson is a good fil...",bronson
16,https://www.metacritic.com/movie/bronson,8.0,'Voltronix',"'Aug 14, 2014'","'Tom Hardy nails it in this role, partially d...",bronson
17,https://www.metacritic.com/movie/bronson,9.0,'LatinCritic13',"'Apr 7, 2019'",'Bronson is defined as a film that s notoriou...,bronson
18,https://www.metacritic.com/movie/bronson,9.0,'MattBrady99',"'Sep 9, 2015'",'Bronson follows the life of notorious prison...,bronson
19,https://www.metacritic.com/movie/bronson,5.0,'Ralfbergs',"'Jun 25, 2016'","'I really liked TOm Hardy s performance here,...",bronson
20,https://www.metacritic.com/movie/bronson,8.0,'nbock',"'Aug 26, 2015'",'While Bronson does take several creative lib...,bronson
21,https://www.metacritic.com/movie/bronson,3.0,'Broyax',"'Jan 27, 2017'","'J avais vu la bande-annonce, tr s dr le, et ...",bronson
22,https://www.metacritic.com/movie/bronson,7.0,'AndrewBurge',"'Jan 31, 2019'",'This film is so British that I want to send ...,bronson
23,https://www.metacritic.com/movie/bronson,6.0,'ahmedaiman1999',"'Mar 20, 2019'",'This is definitely a one-of-a-kind character...,bronson
24,https://www.metacritic.com/movie/bronson,10.0,'Mclovin69',"'Apr 5, 2021'","'The movie was hilarious, Michael peterson wa...",bronson
25,https://www.metacritic.com/movie/bronson,9.0,'TUMBLERok',"'Jun 22, 2020'","' , , . . ! . , , . . ! . , , Bronson . . . 9...",bronson
26,https://www.metacritic.com/movie/bronson,9.0,'Honestyopinons',"'Jun 27, 2020'",'one of the best movies about insanity withou...,bronson
27,https://www.metacritic.com/movie/disgrace,0.0,'Nazgulero',"'Feb 27, 2011'",'After watching this horrible movie for thirt...,disgrace
28,https://www.metacritic.com/movie/disgrace,10.0,'wwh',"'Aug 2, 2011'",'Re: seems quite disgusted by him right from ...,disgrace
29,https://www.metacritic.com/movie/a-screaming-man,NaN,NaN,NaN,NaN,a-screaming-man

In [19]:
df4["title_from_url"] = df4["url"].str.rsplit("/", n=1).str[-1]

In [20]:
df4.head(30)

,url,idvscore,reviewer,dateP,Rev,WC,Analytic,title_from_url
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88,bronson
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07,bronson
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69,bronson
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46,bronson
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46,bronson
5,https://www.metacritic.com/movie/bronson,80.0,None,None,"'He s neither victim nor hero, but a man who,...",17,59.32,bronson
6,https://www.metacritic.com/movie/bronson,80.0,'Bill Goodykoontz',None,"'This is unhinged genius, an amazing piece of...",16,93.26,bronson
7,https://www.metacritic.com/movie/bronson,78.0,'Kimberley Jones',None,'Refn s artful and energetic film never goes ...,12,62.04,bronson
8,https://www.metacritic.com/movie/bronson,75.0,'Peter Travers',None,'This movie and Hardy s electrifying performa...,13,65.46,bronson
9,https://www.metacritic.com/movie/bronson,75.0,'V.A. Musetto',None,'Tom Hardy gives an amazing performance as Pe...,20,99.00,bronson
10,https://www.metacritic.com/movie/bronson,75.0,'David Hiltbrand',None,"'The tone is surreal, at once visceral and cl...",20,78.30,bronson
11,https://www.metacritic.com/movie/bronson,75.0,'Roger Ebert',None,"'It is 92 minutes of rage, acted by Tom Hardy.'",10,93.26,bronson
12,https://www.metacritic.com/movie/bronson,75.0,'Michael Phillips',None,"'Hardy is remarkable, however. This is an act...",20,87.27,bronson
13,https://www.metacritic.com/movie/bronson,75.0,'Ty Burr',None,'Bronson isn t a story in the traditional sen...,30,99.00,bronson
14,https://www.metacritic.com/movie/bronson,75.0,'Shawn Levy',None,"'It s played with real zest and energy, and i...",24,27.87,bronson
15,https://www.metacritic.com/movie/bronson,70.0,None,None,"'With an intelligent, provocative and stylize...",27,99.00,bronson
16,https://www.metacritic.com/movie/bronson,63.0,'James Berardinelli',None,'It s lively and vivid but ends up leaving th...,26,88.90,bronson
17,https://www.metacritic.com/movie/bronson,60.0,None,None,"'Too smart/arty for the slasher set, and too ...",31,63.48,bronson
18,https://www.metacritic.com/movie/bronson,50.0,'Rick Groen',None,'Bronson is one of those based on a true stor...,26,99.00,bronson
19,https://www.metacritic.com/movie/bronson,30.0,None,None,"'Despite the artistic flourishes, this is sti...",26,97.95,bronson
20,https://www.metacritic.com/movie/bronson,30.0,'J. Hoberman',None,"'Bronson is essentially a faux-operatic, musi...",17,97.21,bronson
21,https://www.metacritic.com/movie/bronson,25.0,'Walter Addiego',None,'It s an assaultive work about an assaultive ...,9,98.87,bronson
22,https://www.metacritic.com/movie/disgrace,100.0,'Roger Ebert',None,'This is such a rare movie. Its characters ar...,14,14.58,disgrace
23,https://www.metacritic.com/movie/disgrace,90.0,'Stephen Holden',None,'Mr. Malkovich is one of the few actors capab...,14,99.00,disgrace
24,https://www.metacritic.com/movie/disgrace,83.0,'Peter Rainer',None,"'As fiercely unsentimental as Disgrace is, it...",29,69.54,disgrace
25,https://www.metacritic.com/movie/disgrace,80.0,None,None,"'The austere economy of Coetzee s writing, cr...",24,99.00,disgrace
26,https://www.metacritic.com/movie/disgrace,80.0,'Bob Mondello',None,'John Malkovich has played some odd ducks in ...,32,95.70,disgrace
27,https://www.metacritic.com/movie/disgrace,80.0,None,None,'Surprisingly successful adaptation of J. M. ...,10,98.58,disgrace
28,https://www.metacritic.com/movie/disgrace,75.0,'V.A. Musetto',None,'I cannot tell a lie. I derive great satisfac...,13,43.96,disgrace
29,https://www.metacritic.com/movie/disgrace,75.0,'Lisa Schwarzbaum',None,'Newcomer Jessica Haines is transparent and h...,22,98.34,disgrace

In [21]:
# Show rows where all important review information is missing
missing_reviews = df3[
    df3[["idvscore", "reviewer", "dateP", "Rev"]]
    .isnull()
    .all(axis=1)
]

display(missing_reviews.head())
print(len(missing_reviews))

,url,idvscore,reviewer,dateP,Rev,title_from_url
29,https://www.metacritic.com/movie/a-screaming-man,NaN,NaN,NaN,NaN,a-screaming-man
30,https://www.metacritic.com/movie/lovers-of-hate,NaN,NaN,NaN,NaN,lovers-of-hate
34,https://www.metacritic.com/movie/viva-riva!,NaN,NaN,NaN,NaN,viva-riva!
130,https://www.metacritic.com/movie/september-11,NaN,NaN,NaN,NaN,september-11
134,https://www.metacritic.com/movie/catching-out,NaN,NaN,NaN,NaN,catching-out

3403

In [22]:
print(df3.isnull().sum())

url                  0
idvscore          3404
reviewer          3407
dateP             3413
Rev               3413
title_from_url       0
dtype: int64

In [23]:
# Delete rows that contain more than 2 null values
df3 = df3[df3.isnull().sum(axis=1) <= 2]

In [24]:
df4 = df4[df4.isnull().sum(axis=1) <= 2]

In [26]:
print(df3.isnull().sum())

url               0
idvscore          0
reviewer          0
dateP             5
Rev               5
title_from_url    0
dtype: int64

In [27]:
print(df4.isnull().sum())

url               0
idvscore          0
reviewer          0
dateP             0
Rev               0
WC                0
Analytic          0
title_from_url    0
dtype: int64

In [29]:
display(df3[df3.isnull().any(axis=1)].head())

,url,idvscore,reviewer,dateP,Rev,title_from_url
124298,https://www.metacritic.com/movie/rogue-one-a-s...,cargo carriers,storm-troopers,NaN,NaN,rogue-one-a-star-wars-story
260515,https://www.metacritic.com/movie/the-dark-knight,10.0,'{Nobody,NaN,NaN,the-dark-knight
271313,https://www.metacritic.com/movie/eragon,0,'[Anonymous,NaN,NaN,eragon
290080,https://www.metacritic.com/movie/before-the-de...,10.0,'[Anonymous,NaN,NaN,before-the-devil-knows-youre-dead
297409,https://www.metacritic.com/movie/children-of-men,10.0,"'Lance""The\'OlP""Romance', 'date_published': '...",NaN,NaN,children-of-men

In [32]:
df3.head(20)

,url,idvscore,reviewer,dateP,Rev,title_from_url
0,https://www.metacritic.com/movie/bronson,8.0,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...,bronson
1,https://www.metacritic.com/movie/bronson,9.0,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...,bronson
2,https://www.metacritic.com/movie/bronson,10.0,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...,bronson
3,https://www.metacritic.com/movie/bronson,6.0,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...,bronson
4,https://www.metacritic.com/movie/bronson,8.0,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...,bronson
5,https://www.metacritic.com/movie/bronson,8.0,'RONGIU',"'Jun 10, 2011'","'Sorry, machine translation. The stage, by Ni...",bronson
6,https://www.metacritic.com/movie/bronson,8.0,'Tokyochuchu',"'Nov 30, 2013'","'Bronson is a great, extremely strange movie ...",bronson
7,https://www.metacritic.com/movie/bronson,7.0,'Fenrir81',"'Apr 22, 2011'",'Despite being flawed by a weak narrative str...,bronson
8,https://www.metacritic.com/movie/bronson,4.0,'cabrita',"'Aug 10, 2012'",'If valhalla rising was a weak version of agg...,bronson
9,https://www.metacritic.com/movie/bronson,10.0,'farknash',"'Aug 19, 2011'",'http://mikesharkey.blogspot.com/2009/04/igiz...,bronson
10,https://www.metacritic.com/movie/bronson,4.0,'Spangle',"'Mar 6, 2015'","'Extremely claustrophobic, Bronson is possibl...",bronson
11,https://www.metacritic.com/movie/bronson,8.0,'Nesbitt10',"'Jul 4, 2013'",'One thing is for certain: Bronson invites yo...,bronson
12,https://www.metacritic.com/movie/bronson,5.0,'TrilobiteG',"'Jan 6, 2016'","'Got to say, I m rather disappointed. To begi...",bronson
13,https://www.metacritic.com/movie/bronson,3.0,'Luxocell',"'Jan 16, 2015'","'Call me simple minded if you desire, but I r...",bronson
14,https://www.metacritic.com/movie/bronson,5.0,'TomBeltran',"'May 27, 2013'",'Posted on 5/20/13 10:15 AM\rTom hardy gives ...,bronson
15,https://www.metacritic.com/movie/bronson,7.0,'BrettT',"'Jun 8, 2014'","'Well acted and gritty, Bronson is a good fil...",bronson
16,https://www.metacritic.com/movie/bronson,8.0,'Voltronix',"'Aug 14, 2014'","'Tom Hardy nails it in this role, partially d...",bronson
17,https://www.metacritic.com/movie/bronson,9.0,'LatinCritic13',"'Apr 7, 2019'",'Bronson is defined as a film that s notoriou...,bronson
18,https://www.metacritic.com/movie/bronson,9.0,'MattBrady99',"'Sep 9, 2015'",'Bronson follows the life of notorious prison...,bronson
19,https://www.metacritic.com/movie/bronson,5.0,'Ralfbergs',"'Jun 25, 2016'","'I really liked TOm Hardy s performance here,...",bronson

In [33]:
df4.head(20)

,url,idvscore,reviewer,dateP,Rev,WC,Analytic,title_from_url
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88,bronson
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07,bronson
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69,bronson
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46,bronson
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46,bronson
5,https://www.metacritic.com/movie/bronson,80.0,None,None,"'He s neither victim nor hero, but a man who,...",17,59.32,bronson
6,https://www.metacritic.com/movie/bronson,80.0,'Bill Goodykoontz',None,"'This is unhinged genius, an amazing piece of...",16,93.26,bronson
7,https://www.metacritic.com/movie/bronson,78.0,'Kimberley Jones',None,'Refn s artful and energetic film never goes ...,12,62.04,bronson
8,https://www.metacritic.com/movie/bronson,75.0,'Peter Travers',None,'This movie and Hardy s electrifying performa...,13,65.46,bronson
9,https://www.metacritic.com/movie/bronson,75.0,'V.A. Musetto',None,'Tom Hardy gives an amazing performance as Pe...,20,99.00,bronson
10,https://www.metacritic.com/movie/bronson,75.0,'David Hiltbrand',None,"'The tone is surreal, at once visceral and cl...",20,78.30,bronson
11,https://www.metacritic.com/movie/bronson,75.0,'Roger Ebert',None,"'It is 92 minutes of rage, acted by Tom Hardy.'",10,93.26,bronson
12,https://www.metacritic.com/movie/bronson,75.0,'Michael Phillips',None,"'Hardy is remarkable, however. This is an act...",20,87.27,bronson
13,https://www.metacritic.com/movie/bronson,75.0,'Ty Burr',None,'Bronson isn t a story in the traditional sen...,30,99.00,bronson
14,https://www.metacritic.com/movie/bronson,75.0,'Shawn Levy',None,"'It s played with real zest and energy, and i...",24,27.87,bronson
15,https://www.metacritic.com/movie/bronson,70.0,None,None,"'With an intelligent, provocative and stylize...",27,99.00,bronson
16,https://www.metacritic.com/movie/bronson,63.0,'James Berardinelli',None,'It s lively and vivid but ends up leaving th...,26,88.90,bronson
17,https://www.metacritic.com/movie/bronson,60.0,None,None,"'Too smart/arty for the slasher set, and too ...",31,63.48,bronson
18,https://www.metacritic.com/movie/bronson,50.0,'Rick Groen',None,'Bronson is one of those based on a true stor...,26,99.00,bronson
19,https://www.metacritic.com/movie/bronson,30.0,None,None,"'Despite the artistic flourishes, this is sti...",26,97.95,bronson