In [55]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\aleks\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in c:\Users\aleks\anaconda3\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [118]:
# first we import pandas library and read our excel files
import pandas as pd
df1 = pd.read_excel("/Users/aleks/Downloads/sales.xlsx")
df2 = pd.read_excel("/Users/aleks/Downloads/metaClean43Brightspace.xlsx")

In [57]:
# installing numpy
import numpy as np

In [58]:
# to see the columns of each files:
print(df1.columns.tolist())
print(df2.columns.tolist())

['year', 'release_date', 'title', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'Unnamed: 8', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url']
['url', 'title', 'studio', 'rating', 'runtime', 'cast', 'director', 'genre', 'summary', 'awards', 'metascore', 'userscore', 'RelDate']

In [59]:
# to see the first 20 rows of title for each file
print(df1["title"].head(20))
print(df2["title"].head(20))

0                                      Bakha Satang
1                                         Antitrust
2                                          Santitos
3                               Frank McKlusky C.I.
4                                A Walk to Remember
5                                           Zig Zag
6                                    TakhtÃƒÂ© siah
7             Angry Monk: Reflections on Tibet, The
8                                  30 Years to Life
9                        The Killing of John Lennon
10                                        Mad Money
11                                   Little Chenier
12                               Over Her Dead Body
13    O Ano em Que Meus Pais SaÃƒÂ­ram de FÃƒÂ©rias
14                                              120
15                            The Other Boleyn Girl
16                        A Lawyer Walks into a Bar
17                                       La Rondine
18                          Jodaeiye Nader az Simin
19                                           Pariah
Name: title, dtype: object
0      !Women Art Revolution
1        10 Cloverfield Lane
2           10 Items or Less
3                   10 Years
4           100 Bloody Acres
5                100 Streets
6     1,000 Times Good Night
7                  10,000 BC
8                  10,000 km
9                 1001 Grams
10                ReykjavÃ­k
11            102 Dalmatians
12               10th & Wolf
13                11 Flowers
14                11 Minutes
15                   11/8/16
16                        12
17                  12-12-12
18             12 Hour Shift
19         12 Mighty Orphans
Name: title, dtype: str

In [60]:
# to see the datatype of "title" in each file:
print(df1["title"].dtype)
print(df2["title"].dtype)

object
str

In [61]:
# to see every atributes of first 5 rows
print(df1.head())
print(df2.head())

   year     release_date                title              genre  \
0  2000      January 1st         Bakha Satang              Drama
1  2001     January 12th            Antitrust  Thriller/Suspense
2  2000     January 28th             Santitos                NaN
3  2002  2002 (Wide) by   Frank McKlusky C.I.                NaN
4  2002     January 25th   A Walk to Remember              Drama

   international_box_office  domestic_box_office  worldwide_box_office  \
0                   76576.0                  NaN               76576.0
1                 6900000.0           10965209.0            17865209.0
2                       NaN             378562.0                   NaN
3                       NaN                  NaN                   NaN
4                 4833792.0           41227069.0            46060861.0

   production_budget  Unnamed: 8  opening_weekend  theatre_count  \
0                NaN         NaN              NaN            NaN
1         30000000.0         NaN        5486209.0         2433.0
2                NaN         NaN              NaN            NaN
3                NaN         NaN              NaN            NaN
4         11000000.0         NaN       12177488.0         2411.0

   avg run per theatre  runtime       keywords         creative_type  \
0                  NaN    129.0            NaN  Contemporary Fiction
1                  3.1      NaN            NaN  Contemporary Fiction
2                  NaN    105.0            NaN                   NaN
3                  NaN      NaN            NaN                   NaN
4                  5.3      NaN  Coming of Age  Contemporary Fiction

                                                 url
0  https://www.the-numbers.com/movie/Bakha-Satang...
1        https://www.the-numbers.com/movie/Antitrust
2         https://www.the-numbers.com/movie/Santitos
3  https://www.the-numbers.com/movie/Frank-McKlus...
4  https://www.the-numbers.com/movie/Walk-to-Reme...
                                                 url                  title  \
0  https://www.metacritic.com/movie/!women-art-re...  !Women Art Revolution
1  https://www.metacritic.com/movie/10-cloverfiel...    10 Cloverfield Lane
2  https://www.metacritic.com/movie/10-items-or-less       10 Items or Less
3          https://www.metacritic.com/movie/10-years               10 Years
4  https://www.metacritic.com/movie/100-bloody-acres       100 Bloody Acres

                     studio       rating  runtime  \
0       Hotwire Productions  | Not Rated     83.0
1        Paramount Pictures      | PG-13    104.0
2                Click Star          | R     82.0
3  Anchor Bay Entertainment          | R    100.0
4           Music Box Films  | Not Rated     91.0

                                                cast              director  \
0                                                NaN  Lynn Hershman-Leeson
1  John Gallagher Jr.,John Goodman,Mary Elizabeth...      Dan Trachtenberg
2                 Jonah Hill,Morgan Freeman,Paz Vega       Brad Silberling
3             Channing Tatum,Chris Pratt,Jenna Dewan          Jamie Linden
4                                                NaN       Cameron Cairnes

                                         genre  \
0                                  Documentary
1  Action,Sci-Fi,Drama,Mystery,Thriller,Horror
2                         Drama,Comedy,Romance
3                         Drama,Comedy,Romance
4                                Horror,Comedy

                                             summary  \
0                                                NaN
1  Waking up from a car accident, a young woman (...
2  While researching a role as a supermarket mana...
3                                                NaN
4  Reg and Lindsay run an organic fertilizer busi...

                                              awards  metascore  userscore  \
0                                                NaN         70        NaN
1  #18MostDiscussedMovieof2016 , #1MostSharedMovi...         76        7.7
2                                                NaN         54        5.8
3                                                NaN         61        6.9
4                                                NaN         63        7.5

     RelDate
0 2011-06-01
1 2016-03-11
2 2006-12-01
3 2012-09-14
4 2013-06-28

In [62]:
# to see how many rows and columns are in the file
print("File 1 shape:", df1.shape)
print("File 2 shape:", df2.shape)

File 1 shape: (30612, 16)
File 2 shape: (11364, 13)

In [63]:
#  to see the columns names of every file:
print("\nFile 1 columns:")
print(df1.columns.tolist())

print("\nFile 2 columns:")
print(df2.columns.tolist())

File 1 columns:
['year', 'release_date', 'title', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'Unnamed: 8', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url']

File 2 columns:
['url', 'title', 'studio', 'rating', 'runtime', 'cast', 'director', 'genre', 'summary', 'awards', 'metascore', 'userscore', 'RelDate']

In [64]:
# there was one column with empty value in Sales file. to check if the whole column is empty we do:
# 1):
print("\nNumber of missing values:")
print(df1["Unnamed: 8"].isna().sum())

Number of missing values:
30612

In [65]:
# 2):
print("\nNumber of non-missing values:")
print(df1["Unnamed: 8"].notna().sum())

Number of non-missing values:
0

In [66]:
# So now we can safely remove the column:
df1 = df1.drop(columns=["Unnamed: 8"])

In [67]:
# Checking the columns again:
print("File 1 columns after removing the empty column:")
print(df1.columns.tolist())

File 1 columns after removing the empty column:
['year', 'release_date', 'title', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url']

In [68]:
#  so now we change the name of some columns to have consistent names:
df1 = df1.rename(columns={
    "year": "release_year"
})

df2 = df2.rename(columns={
    "RelDate": "release_date"
})

In [69]:
# we convert column names to lowercase to prevent further problems caused by capitalization:
df1.columns = df1.columns.str.lower()
df2.columns = df2.columns.str.lower()

In [70]:
# to check the names again : 
print("File 1 columns:")
print(df1.columns.tolist())

print("\nFile 2 columns:")
print(df2.columns.tolist())

File 1 columns:
['release_year', 'release_date', 'title', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url']

File 2 columns:
['url', 'title', 'studio', 'rating', 'runtime', 'cast', 'director', 'genre', 'summary', 'awards', 'metascore', 'userscore', 'release_date']

In [71]:
# to check the data types of each Table:
print("File 1 data types:")
print(df1.dtypes)

print("\nFile 2 data types:")
print(df2.dtypes)

File 1 data types:
release_year                  int64
release_date                    str
title                        object
genre                           str
international_box_office    float64
domestic_box_office         float64
worldwide_box_office        float64
production_budget           float64
opening_weekend             float64
theatre_count               float64
avg run per theatre         float64
runtime                     float64
keywords                     object
creative_type                   str
url                             str
dtype: object

File 2 data types:
url                        str
title                      str
studio                     str
rating                     str
runtime                float64
cast                       str
director                   str
genre                      str
summary                    str
awards                     str
metascore                int64
userscore              float64
release_date    datetime64[us]
dtype: object

In [72]:
# our finding was:
# File 1 release_year is already numeric.
# File 1 release_date is text (object) and needs special handling later.
# File 2 release_date is already a proper date.
# runtime is numeric in both files.
# Most descriptive fields are text.

In [73]:
# to see how many missing values are in Sales file:
print("Missing values in File 1:")
print(df1.isna().sum().sort_values(ascending=False))

Missing values in File 1:
production_budget           26132
opening_weekend             19683
avg run per theatre         19660
theatre_count               19649
domestic_box_office         18728
keywords                    18095
international_box_office     9037
worldwide_box_office         9037
runtime                      6053
creative_type                3945
genre                        1704
title                           8
release_date                    0
release_year                    0
url                             0
dtype: int64

In [74]:
# we do the same for the second file:
print("\nMissing values in File 2:")
print(df2.isna().sum().sort_values(ascending=False))

Missing values in File 2:
awards          6977
summary         5897
cast            3702
userscore       2105
rating          1067
studio           350
runtime          255
genre             20
director          14
title              0
url                0
metascore          0
release_date       0
dtype: int64

In [75]:
# to see if any placeholder replaced the missing values
missing_values = ["N/A", "n/a", "NA", "na", "NULL", "null", "-", "?"]

print("Placeholder values in File 1:")
for column in df1.columns:
    count = df1[column].isin(missing_values).sum()
    if count > 0:
        print(column, ":", count)

print("\nPlaceholder values in File 2:")
for column in df2.columns:
    count = df2[column].isin(missing_values).sum()
    if count > 0:
        print(column, ":", count)

Placeholder values in File 1:

Placeholder values in File 2:

In [76]:
# We create a seperate cleaned title column which we can use for matching
# to remove unnecessary punctuations and spaced we add a library called RE
import re

In [77]:
# to standardize movie titles and keep missing titles as missing values we create a function: 
def clean_title(title):
    if pd.isna(title):
        return None

#to convert the title to text:
    title = str(title)
#convert all letters to lowercase:
    title = title.lower()
# romove extra spaces from begining and end:
    title = title.strip()
# to remove punctuations and keep letters, numbers, and spaces:
    title = re.sub(r"[^\w\s]", "", title)
# to replace multiple spaces with one space
    title = re.sub(r"\s+", " ", title)

    return title

In [78]:
# now we apply the function to our file:
df1["title_clean"] = df1["title"].apply(clean_title)
df2["title_clean"] = df2["title"].apply(clean_title)

In [79]:
# to compare the original title column with the new column:
print("File 1:")
print(df1[["title", "title_clean"]].head(10))

print("\nFile 2:")
print(df2[["title", "title_clean"]].head(10))

File 1:
                                   title                          title_clean
0                           Bakha Satang                         bakha satang
1                              Antitrust                            antitrust
2                               Santitos                             santitos
3                    Frank McKlusky C.I.                    frank mcklusky ci
4                     A Walk to Remember                   a walk to remember
5                                Zig Zag                              zig zag
6                         TakhtÃƒÂ© siah                        takhtãƒâ siah
7  Angry Monk: Reflections on Tibet, The  angry monk reflections on tibet the
8                       30 Years to Life                     30 years to life
9             The Killing of John Lennon           the killing of john lennon

File 2:
                    title            title_clean
0   !Women Art Revolution   women art revolution
1     10 Cloverfield Lane    10 cloverfield lane
2        10 Items or Less       10 items or less
3                10 Years               10 years
4        100 Bloody Acres       100 bloody acres
5             100 Streets            100 streets
6  1,000 Times Good Night  1000 times good night
7               10,000 BC               10000 bc
8               10,000 km               10000 km
9              1001 Grams             1001 grams

In [80]:
# to check how many times did a title repeated in the same file:
title_counts_1 = df1["title_clean"].value_counts()

print("Duplicate titles in File 1:")
print(title_counts_1[title_counts_1 > 1].head(20))

Duplicate titles in File 1:
title_clean
royal opera house the nutcracker    5
ride                                5
dreamland                           5
a christmas carol                   4
blue                                4
gold                                4
the king                            4
pinocchio                           4
adam                                4
reunion                             4
run                                 4
chef                                3
vice                                3
met opera la traviata               3
the grudge                          3
master                              3
fallen                              3
the divide                          3
anonymous                           3
darling                             3
Name: count, dtype: int64

In [81]:
# and for the second file: 
title_counts_2 = df2["title_clean"].value_counts()

print("\nDuplicate titles in File 2:")
print(title_counts_2[title_counts_2 > 1].head(20))

Duplicate titles in File 2:
title_clean
aftermath            3
eden                 3
innocence            3
lucky                3
the circle           3
the king             3
the outsider         3
the square           3
the take             3
together             3
a family affair      2
adam                 2
after                2
after the wedding    2
amazing grace        2
amy                  2
anna                 2
ava                  2
awake                2
backstage            2
Name: count, dtype: int64

In [82]:
# so it might be same movie names but totally diffrent ones. we need to check them alongside the release years.
# first we extract the released date from file 2:
df2["release_year"] = df2["release_date"].dt.year
print(df2[["release_date", "release_year"]].head(10))

  release_date  release_year
0   2011-06-01          2011
1   2016-03-11          2016
2   2006-12-01          2006
3   2012-09-14          2012
4   2013-06-28          2013
5   2017-01-13          2017
6   2014-10-24          2014
7   2008-03-07          2008
8   2015-07-10          2015
9   2015-05-08          2015

In [83]:
# to spot unusual years:
print("Minimum release year:", df1["release_year"].min())
print("Maximum release year:", df1["release_year"].max())

print("\nRelease year distribution:")
print(df1["release_year"].value_counts().sort_index().head(20))

Minimum release year: 2000
Maximum release year: 2021

Release year distribution:
release_year
2000     504
2001     464
2002     475
2003     554
2004     599
2005     577
2006     649
2007     748
2008     731
2009     625
2010     633
2011     843
2012    1043
2013     997
2014    1150
2015    2427
2016    3029
2017    3177
2018    3343
2019    3385
Name: count, dtype: int64

In [84]:
# to check movies with same name but different years:
df1["movie_key"] = (
    df1["title_clean"].fillna("")
    + "_"
    + df1["release_year"].astype(str)
)

df2["movie_key"] = (
    df2["title_clean"].fillna("")
    + "_"
    + df2["release_year"].astype(str)
)

In [85]:
# original title,release year, and new movie key:
print("File 1:")
print(df1[["title", "release_year", "movie_key"]].head(10))

print("\nFile 2:")
print(df2[["title", "release_year", "movie_key"]].head(10))

File 1:
                                   title  release_year  \
0                           Bakha Satang          2000
1                              Antitrust          2001
2                               Santitos          2000
3                    Frank McKlusky C.I.          2002
4                     A Walk to Remember          2002
5                                Zig Zag          2002
6                         TakhtÃƒÂ© siah          2002
7  Angry Monk: Reflections on Tibet, The          2009
8                       30 Years to Life          2002
9             The Killing of John Lennon          2008

                                  movie_key
0                         bakha satang_2000
1                            antitrust_2001
2                             santitos_2000
3                    frank mcklusky ci_2002
4                   a walk to remember_2002
5                              zig zag_2002
6                        takhtãƒâ siah_2002
7  angry monk reflections on tibet the_2009
8                     30 years to life_2002
9           the killing of john lennon_2008

File 2:
                    title  release_year                   movie_key
0   !Women Art Revolution          2011   women art revolution_2011
1     10 Cloverfield Lane          2016    10 cloverfield lane_2016
2        10 Items or Less          2006       10 items or less_2006
3                10 Years          2012               10 years_2012
4        100 Bloody Acres          2013       100 bloody acres_2013
5             100 Streets          2017            100 streets_2017
6  1,000 Times Good Night          2014  1000 times good night_2014
7               10,000 BC          2008               10000 bc_2008
8               10,000 km          2015               10000 km_2015
9              1001 Grams          2015             1001 grams_2015

In [86]:
# now we check duplicated movie keys:
duplicate_keys_1 = df1["movie_key"].value_counts()

duplicate_keys_1 = duplicate_keys_1[duplicate_keys_1 > 1]
print("Duplicate movie_keys in File 1:")
print(duplicate_keys_1.head(20))

Duplicate movie_keys in File 1:
movie_key
ride_2018                 3
blue_2017                 3
dreamland_2020            3
a christmas carol_2018    2
first love_2018           2
les affamãƒâs_2018        2
money_2017                2
the messenger_2015        2
escape room_2017          2
_2015                     2
the space between_2017    2
best f_2018               2
delirium_2018             2
the outsider_2018         2
aftermath_2014            2
wuthering heights_2012    2
_2009                     2
thirst_2009               2
white noise_2005          2
the interpreter_2005      2
Name: count, dtype: int64

In [87]:
duplicate_keys_2 = df2["movie_key"].value_counts()

duplicate_keys_2 = duplicate_keys_2[duplicate_keys_2 > 1]
print("\nDuplicate movie_keys in File 2:")
print(duplicate_keys_2.head(20))

Duplicate movie_keys in File 2:
movie_key
dreamland_2020     2
swan song_2021     2
the hunter_2012    2
Name: count, dtype: int64

In [88]:
keys_to_check = [
    "blue_2017",
    "dreamland_2020",
    "_2009"
]

duplicates_file1 = df1[df1["movie_key"].isin(keys_to_check)]
print(duplicates_file1.to_string(index=False))

 release_year  release_date     title             genre  international_box_office  domestic_box_office  worldwide_box_office  production_budget  opening_weekend  theatre_count  avg run per theatre  runtime                                     keywords        creative_type                                                                           url title_clean      movie_key
         2017  October 13th      Blue       Documentary                  103208.0                  NaN              103208.0                NaN              NaN            NaN                  NaN     76.0                                          NaN              Factual                      https://www.the-numbers.com/movie/Blue-(Australia)(2017)        blue      blue_2017
         2017  October 13th      Blue             Drama                  175171.0                  NaN              175171.0                NaN              NaN            NaN                  NaN     97.0                                          NaN Contemporary Fiction                                 https://www.the-numbers.com/movie/Blue-(2015)        blue      blue_2017
         2017    April 21st      Blue       Documentary                   17621.0                  NaN               17621.0                NaN              NaN            NaN                  NaN    100.0                                          NaN              Factual                               https://www.the-numbers.com/movie/Blue-(Turkey)        blue      blue_2017
         2009  October 23rd       NaN               NaN                       NaN             230600.0                   NaN                NaN          18002.0            3.0                  3.0      NaN                                          NaN                  NaN                                  https://www.the-numbers.com/movie/(Untitled)         NaN          _2009
         2009     July 17th       NaN   Romantic Comedy                 2089638.0           32425665.0            34515303.0          7500000.0         834501.0           27.0                  7.2     95.0                                      Romance Contemporary Fiction                          https://www.the-numbers.com/movie/500-Days-of-Summer         NaN          _2009
         2020 February 25th Dreamland Thriller/Suspense                  672369.0             409363.0             1081732.0                NaN         178602.0          216.0                  2.5    118.0                               Crime Thriller Contemporary Fiction                            https://www.the-numbers.com/movie/Dreamland-(2020)   dreamland dreamland_2020
         2020 November 13th Dreamland Thriller/Suspense                  238652.0                  NaN              238652.0                NaN              NaN            NaN                  NaN    101.0                               Crime Thriller   Historical Fiction https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)   dreamland dreamland_2020
         2020      June 5th Dreamland      Black Comedy                       NaN                  NaN                   NaN                NaN              NaN            NaN                  NaN     92.0 Early / Simultaneous Video-on-Demand release              Fantasy                          https://www.the-numbers.com/movie/Dreamland-(Canada)   dreamland dreamland_2020

In [89]:
df1

,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url,title_clean,movie_key
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021
30608,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021
30609,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021
30610,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021
30611,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021

In [90]:
#for syntax compability we need to rename avg run per theatre
df1.rename(columns={"avg run per theatre":"avg_run_per_theatre"},inplace=True)
df1

,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021
30608,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021
30609,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021
30610,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021
30611,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021

In [91]:
rows = df1[:10]
print(rows)

   release_year     release_date                                  title  \
0          2000      January 1st                           Bakha Satang
1          2001     January 12th                              Antitrust
2          2000     January 28th                               Santitos
3          2002  2002 (Wide) by                     Frank McKlusky C.I.
4          2002     January 25th                     A Walk to Remember
5          2002        June 21st                                Zig Zag
6          2002         May 10th                         TakhtÃƒÂ© siah
7          2009      January 2nd  Angry Monk: Reflections on Tibet, The
8          2002         June 7th                       30 Years to Life
9          2008      January 2nd             The Killing of John Lennon

               genre  international_box_office  domestic_box_office  \
0              Drama                   76576.0                  NaN
1  Thriller/Suspense                 6900000.0           10965209.0
2                NaN                       NaN             378562.0
3                NaN                       NaN                  NaN
4              Drama                 4833792.0           41227069.0
5                NaN                       NaN               1649.0
6              Drama                       NaN              21324.0
7        Documentary                       NaN               2125.0
8             Comedy                       NaN              99023.0
9              Drama                       NaN               6975.0

   worldwide_box_office  production_budget  opening_weekend  theatre_count  \
0               76576.0                NaN              NaN            NaN
1            17865209.0         30000000.0        5486209.0         2433.0
2                   NaN                NaN              NaN            NaN
3                   NaN                NaN              NaN            NaN
4            46060861.0         11000000.0       12177488.0         2411.0
5                   NaN                NaN           1649.0            1.0
6                   NaN                NaN           1500.0            5.0
7                   NaN                NaN           2125.0            1.0
8                   NaN                NaN           3376.0            1.0
9                   NaN                NaN           3077.0            1.0

   avg_run_per_theatre  runtime          keywords         creative_type  \
0                  NaN    129.0               NaN  Contemporary Fiction
1                  3.1      NaN               NaN  Contemporary Fiction
2                  NaN    105.0               NaN                   NaN
3                  NaN      NaN               NaN                   NaN
4                  5.3      NaN     Coming of Age  Contemporary Fiction
5                  1.0      NaN               NaN                   NaN
6                  2.0      NaN  Foreign Language                   NaN
7                  1.0      NaN               NaN               Factual
8                  3.3      NaN               NaN                   NaN
9                  3.0      NaN               NaN         Dramatization

                                                 url  \
0  https://www.the-numbers.com/movie/Bakha-Satang...
1        https://www.the-numbers.com/movie/Antitrust
2         https://www.the-numbers.com/movie/Santitos
3  https://www.the-numbers.com/movie/Frank-McKlus...
4  https://www.the-numbers.com/movie/Walk-to-Reme...
5          https://www.the-numbers.com/movie/Zig-Zag
6      https://www.the-numbers.com/movie/Takhte-siah
7  https://www.the-numbers.com/movie/Angry-Monk-R...
8  https://www.the-numbers.com/movie/30-Years-to-...
9  https://www.the-numbers.com/movie/Killing-of-J...

                           title_clean  \
0                         bakha satang
1                            antitrust
2                             santitos
3                    frank mcklusky ci
4                   a walk to remember
5                              zig zag
6                        takhtãƒâ siah
7  angry monk reflections on tibet the
8                     30 years to life
9           the killing of john lennon

                                  movie_key
0                         bakha satang_2000
1                            antitrust_2001
2                             santitos_2000
3                    frank mcklusky ci_2002
4                   a walk to remember_2002
5                              zig zag_2002
6                        takhtãƒâ siah_2002
7  angry monk reflections on tibet the_2009
8                     30 years to life_2002
9           the killing of john lennon_2008

In [ ]:
#this code works but its too early to use it
df1.insert(0, "movie_id", range(1, len(df1) + 1))

In [121]:
#sorting by longest runtime to ingvestigate
sort1 = df1.sort_values(["runtime"],ascending=False).head(20)
sort1

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,Unnamed: 8,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url
24691,2019,August 2nd,La Flor,Drama,1520.0,NaN,1520.0,NaN,NaN,NaN,NaN,NaN,803.0,NaN,Fantasy,https://www.the-numbers.com/movie/Flor-La-(Arg...
3427,2015,November 27th,"Out 1, noli me tangere",Drama,6204.0,NaN,6204.0,NaN,NaN,NaN,NaN,NaN,760.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Out-1-noli-m...
28613,2021,July 16th,The Works and Days,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,480.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Works-and-Da...
22311,2004,April 9th,The Cremaster Cycle,Drama,11219.0,151239.0,162458.0,NaN,NaN,7982.0,1.0,12.0,398.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Cremaster-Cy...
21828,2004,March 2nd,La meglio gioventÃƒÂ¹,Drama,2419029.0,270810.0,2689839.0,NaN,NaN,7490.0,1.0,9.0,366.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Meglio-giove...
1608,2018,October 26th,Royal Opera House: Die Walkure,Concert/Performance,257146.0,NaN,257146.0,NaN,NaN,NaN,NaN,NaN,350.0,Opera,NaN,https://www.the-numbers.com/movie/Royal-Opera-...
14346,2007,November 7th,La commune,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,345.0,NaN,Dramatization,https://www.the-numbers.com/movie/commune-Pari...
3359,2016,October 6th,Homeland: Iraq Year Zero,Documentary,NaN,2491.0,NaN,NaN,NaN,560.0,1.0,1.0,334.0,2000s,Factual,https://www.the-numbers.com/movie/Homeland-Ira...
13452,2018,February 9th,2018 Oscar Shorts,Multiple Genres,2345.0,3508777.0,3511122.0,NaN,NaN,695044.0,198.0,3.8,328.0,Compilations,Multiple Creative Types,https://www.the-numbers.com/movie/2018-Oscar-S...
3145,2015,December 4th,River of Fundament,Drama,NaN,44840.0,NaN,NaN,NaN,4938.0,1.0,7.0,319.0,Experimental Film,Fantasy,https://www.the-numbers.com/movie/River-of-Fun...
18436,2006,August 18th,The Pusher Trilogy,NaN,NaN,4815.0,NaN,NaN,NaN,1792.0,1.0,2.0,318.0,NaN,NaN,https://www.the-numbers.com/movie/Pusher-Trilo...
20057,2010,January 26th,The Weathered Underground,Multiple Genres,NaN,140091.0,NaN,NaN,NaN,1010.0,3.0,3.1,310.0,Directing Yourself,Contemporary Fiction,https://www.the-numbers.com/movie/Weathered-Un...
1412,2018,November 2nd,League Of Legends World Championship 2018,Concert/Performance,45349.0,NaN,45349.0,NaN,NaN,NaN,NaN,NaN,300.0,NaN,NaN,https://www.the-numbers.com/movie/League-Of-Le...
835,2018,November 16th,Opera De Paris: Les Huguenots,Concert/Performance,4223.0,NaN,4223.0,NaN,NaN,NaN,NaN,NaN,300.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Opera-De-Par...
27899,2019,March 29th,Met Opera: Die Walkure,Concert/Performance,941763.0,NaN,941763.0,NaN,NaN,NaN,NaN,NaN,295.0,Opera,Historical Fiction,https://www.the-numbers.com/movie/Met-Opera-Di...
3244,2016,October 7th,Tristan und Isolde - Met Opera 2016,Concert/Performance,290749.0,NaN,290749.0,NaN,NaN,NaN,NaN,NaN,287.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Met-Opera-Tr...
585,2017,December 1st,Opera De Paris: Don Carlos,Concert/Performance,10610.0,NaN,10610.0,NaN,NaN,NaN,NaN,NaN,280.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Opera-De-Par...
19105,2014,January 15th,"Unsere Mutter, unsere Vater",Drama,NaN,91595.0,NaN,NaN,NaN,7386.0,1.0,4.3,279.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Unsere-Mutte...
1013,2018,November 14th,Shoah Four Sisters,Documentary,NaN,5512.0,NaN,NaN,NaN,2840.0,1.0,1.3,273.0,Holocaust,Factual,https://www.the-numbers.com/movie/Shoah-Four-S...
22957,2019,November 23rd,Wilder vs. Ortiz,Concert/Performance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,270.0,NaN,Factual,https://www.the-numbers.com/movie/Wilder-vs-Ortiz

In [120]:
#some runtimes are unusually long, investigated all movies with runtimes over 350 minutes to check if they are actually that long
# some runtimes are wrong, replacing them with correct values
df1.loc[df1["title"] =="Barbara Lee: Speaking Truth to Power", "runtime" ] = 82
df1.loc[df1["title"] =="Amazonia", "runtime" ] = 67
df1.loc[df1["title"] =="Meesterspion", "runtime" ] = 100
df1.loc[df1["title"] =="AmÃ…Â¾inai kartu", "runtime" ] = 88

In [97]:
#investigating weird release dates
df1["release_date"].unique()

<ArrowStringArray>
[             'January 1st',             'January 12th',
             'January 28th',          '2002 (Wide) by ',
             'January 25th',                'June 21st',
                 'May 10th',              'January 2nd',
                 'June 7th',             'January 18th',
 ...
           '2003 (Limited)',              '2002 (Wide)',
            '2020 (Wide) (',      '2020 (Canceled) by ',
 'Fall 2020 (Canceled) by ',          '2022 (Wide) by ',
            '2021 (Wide) (',                   'Summer',
      '2022 (Canceled) by ',      '2021 (Canceled) by ']
Length: 392, dtype: str

In [98]:
#some release dates dont actually contain date but different information
#to preserve the extra information we create an extra date column to clean it
df1["release_date_clean"] = df1["release_date"]

In [99]:
df1

,movie_id,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key,release_date_clean
0,1,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000,January 1st
1,2,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001,January 12th
2,3,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000,January 28th
3,4,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002,2002 (Wide) by
4,5,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002,January 25th
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,30608,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021,January 1st
30608,30609,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021,March 5th
30609,30610,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021,January 1st
30610,30611,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021,May 21st
30611,30612,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021,January 1st

In [100]:
#seeing how many rows contain information different from date
df1["release_date"].str.contains("Wide", case=False, na=False).sum()

np.int64(9)

In [101]:
df1["release_date"].str.contains("Canceled", case=False, na=False).sum()

np.int64(13)

In [102]:
#in the clean release date column, we replace those unfittting values with nan
df1.loc[df1["release_date_clean"].str.contains("Wide|Canceled",case=False,na=False),"release_date_clean"] = np.nan

In [103]:
df1

,movie_id,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key,release_date_clean
0,1,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000,January 1st
1,2,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001,January 12th
2,3,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000,January 28th
3,4,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002,NaN
4,5,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002,January 25th
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,30608,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021,January 1st
30608,30609,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021,March 5th
30609,30610,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021,January 1st
30610,30611,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021,May 21st
30611,30612,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021,January 1st

In [104]:
df1["release_date_clean"] = (
    df1["release_date_clean"]
    .str.replace("st", "")
    .str.replace("nd", "")
    .str.replace("rd", "")
    .str.replace("th", "")
)

In [105]:
df1

,movie_id,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key,release_date_clean
0,1,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000,January 1
1,2,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001,January 12
2,3,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000,January 28
3,4,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002,NaN
4,5,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002,January 25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,30608,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021,January 1
30608,30609,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021,March 5
30609,30610,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021,January 1
30610,30611,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021,May 21
30611,30612,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021,January 1

In [ ]:
#combining 2 column to create full data column
#errors="coerce" tells pandas: If you find a value that you can't convert, don't give me an error — turn it into a missing value instead.
df1["full_release_date"] = pd.to_datetime(
    df1["release_date_clean"] + " " + df1["release_year"].astype(str),
    errors="coerce"
)

In [109]:
df1

,movie_id,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key,release_date_clean,full_release_date
0,1,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000,January 1,2000-01-01
1,2,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001,January 12,2001-01-12
2,3,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000,January 28,2000-01-28
3,4,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002,NaN,NaT
4,5,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002,January 25,2002-01-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,30608,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021,January 1,2021-01-01
30608,30609,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021,March 5,2021-03-05
30609,30610,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021,January 1,2021-01-01
30610,30611,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021,May 21,2021-05-21
30611,30612,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021,January 1,2021-01-01

In [110]:
df1.drop("movie_id",axis=1)

,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key,release_date_clean,full_release_date
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000,January 1,2000-01-01
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001,January 12,2001-01-12
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000,January 28,2000-01-28
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002,NaN,NaT
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002,January 25,2002-01-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021,January 1,2021-01-01
30608,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021,March 5,2021-03-05
30609,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021,January 1,2021-01-01
30610,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021,May 21,2021-05-21
30611,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021,January 1,2021-01-01