# Shared movie-data cleaning notebook

Code from all three submitted notebooks, in one file for the group to edit.

Every retained code cell is copied exactly as written, including comments. The shared sales/metadata setup appears once. Both differing runtime-correction versions are kept. The original file paths, saved outputs, and saved errors are retained; this combined notebook has not been executed.

The only new content is these section labels and assembly notes. There is no added review-to-movie connection code, table-building code, or data-cleaning logic.

## 1. Shared sales and metadata setup

The two movie notebooks contain the same 32 setup/inspection cells. They appear once here, using the file-loading cell from `fulldatabase_movies.ipynb` and the NumPy import from `cleaning9.22.ipynb`. The other file-loading cell differs only in its local folder paths.

In [1]:
%pip install openpyxl

Requirement already satisfied: openpyxl in /opt/anaconda3/envs/ai_dev/lib/python3.10/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/anaconda3/envs/ai_dev/lib/python3.10/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# first we import pandas library and read our excel files
import pandas as pd
df1 = pd.read_excel("/Users/pouriyarezaali/Desktop/DBM CLASS/Data Files/sales.xlsx")
df2 = pd.read_excel("/Users/pouriyarezaali/Desktop/DBM CLASS/Data Files/metaClean43Brightspace.xlsx")

In [57]:
# installing numpy
import numpy as np

In [3]:
# to see the columns of each files:
print(df1.columns.tolist())
print(df2.columns.tolist())

['year', 'release_date', 'title', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'Unnamed: 8', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url']
['url', 'title', 'studio', 'rating', 'runtime', 'cast', 'director', 'genre', 'summary', 'awards', 'metascore', 'userscore', 'RelDate']

In [4]:
# to see the first 20 rows of title for each file
print(df1["title"].head(20))
print(df2["title"].head(20))

0                                      Bakha Satang
1                                         Antitrust
2                                          Santitos
3                               Frank McKlusky C.I.
4                                A Walk to Remember
5                                           Zig Zag
6                                    TakhtÃƒÂ© siah
7             Angry Monk: Reflections on Tibet, The
8                                  30 Years to Life
9                        The Killing of John Lennon
10                                        Mad Money
11                                   Little Chenier
12                               Over Her Dead Body
13    O Ano em Que Meus Pais SaÃƒÂ­ram de FÃƒÂ©rias
14                                              120
15                            The Other Boleyn Girl
16                        A Lawyer Walks into a Bar
17                                       La Rondine
18                          Jodaeiye Nader az Simin
19                                           Pariah
Name: title, dtype: object
0      !Women Art Revolution
1        10 Cloverfield Lane
2           10 Items or Less
3                   10 Years
4           100 Bloody Acres
5                100 Streets
6     1,000 Times Good Night
7                  10,000 BC
8                  10,000 km
9                 1001 Grams
10                ReykjavÃ­k
11            102 Dalmatians
12               10th & Wolf
13                11 Flowers
14                11 Minutes
15                   11/8/16
16                        12
17                  12-12-12
18             12 Hour Shift
19         12 Mighty Orphans
Name: title, dtype: object

In [5]:
# to see the datatype of "title" in each file:
print(df1["title"].dtype)
print(df2["title"].dtype)

object
object

In [6]:
# to see every atributes of first 5 rows
print(df1.head())
print(df2.head())

   year     release_date                title              genre  \
0  2000      January 1st         Bakha Satang              Drama
1  2001     January 12th            Antitrust  Thriller/Suspense
2  2000     January 28th             Santitos                NaN
3  2002  2002 (Wide) by   Frank McKlusky C.I.                NaN
4  2002     January 25th   A Walk to Remember              Drama

   international_box_office  domestic_box_office  worldwide_box_office  \
0                   76576.0                  NaN               76576.0
1                 6900000.0           10965209.0            17865209.0
2                       NaN             378562.0                   NaN
3                       NaN                  NaN                   NaN
4                 4833792.0           41227069.0            46060861.0

   production_budget  Unnamed: 8  opening_weekend  theatre_count  \
0                NaN         NaN              NaN            NaN
1         30000000.0         NaN        5486209.0         2433.0
2                NaN         NaN              NaN            NaN
3                NaN         NaN              NaN            NaN
4         11000000.0         NaN       12177488.0         2411.0

   avg run per theatre  runtime       keywords         creative_type  \
0                  NaN    129.0            NaN  Contemporary Fiction
1                  3.1      NaN            NaN  Contemporary Fiction
2                  NaN    105.0            NaN                   NaN
3                  NaN      NaN            NaN                   NaN
4                  5.3      NaN  Coming of Age  Contemporary Fiction

                                                 url
0  https://www.the-numbers.com/movie/Bakha-Satang...
1        https://www.the-numbers.com/movie/Antitrust
2         https://www.the-numbers.com/movie/Santitos
3  https://www.the-numbers.com/movie/Frank-McKlus...
4  https://www.the-numbers.com/movie/Walk-to-Reme...
                                                 url                  title  \
0  https://www.metacritic.com/movie/!women-art-re...  !Women Art Revolution
1  https://www.metacritic.com/movie/10-cloverfiel...    10 Cloverfield Lane
2  https://www.metacritic.com/movie/10-items-or-less       10 Items or Less
3          https://www.metacritic.com/movie/10-years               10 Years
4  https://www.metacritic.com/movie/100-bloody-acres       100 Bloody Acres

                     studio       rating  runtime  \
0       Hotwire Productions  | Not Rated     83.0
1        Paramount Pictures      | PG-13    104.0
2                Click Star          | R     82.0
3  Anchor Bay Entertainment          | R    100.0
4           Music Box Films  | Not Rated     91.0

                                                cast              director  \
0                                                NaN  Lynn Hershman-Leeson
1  John Gallagher Jr.,John Goodman,Mary Elizabeth...      Dan Trachtenberg
2                 Jonah Hill,Morgan Freeman,Paz Vega       Brad Silberling
3             Channing Tatum,Chris Pratt,Jenna Dewan          Jamie Linden
4                                                NaN       Cameron Cairnes

                                         genre  \
0                                  Documentary
1  Action,Sci-Fi,Drama,Mystery,Thriller,Horror
2                         Drama,Comedy,Romance
3                         Drama,Comedy,Romance
4                                Horror,Comedy

                                             summary  \
0                                                NaN
1  Waking up from a car accident, a young woman (...
2  While researching a role as a supermarket mana...
3                                                NaN
4  Reg and Lindsay run an organic fertilizer busi...

                                              awards  metascore  userscore  \
0                                                NaN         70        NaN
1  #18MostDiscussedMovieof2016 , #1MostSharedMovi...         76        7.7
2                                                NaN         54        5.8
3                                                NaN         61        6.9
4                                                NaN         63        7.5

     RelDate
0 2011-06-01
1 2016-03-11
2 2006-12-01
3 2012-09-14
4 2013-06-28

In [7]:
# to see how many rows and columns are in the file
print("File 1 shape:", df1.shape)
print("File 2 shape:", df2.shape)

File 1 shape: (30612, 16)
File 2 shape: (11364, 13)

In [8]:
#  to see the columns names of every file:
print("\nFile 1 columns:")
print(df1.columns.tolist())

print("\nFile 2 columns:")
print(df2.columns.tolist())

File 1 columns:
['year', 'release_date', 'title', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'Unnamed: 8', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url']

File 2 columns:
['url', 'title', 'studio', 'rating', 'runtime', 'cast', 'director', 'genre', 'summary', 'awards', 'metascore', 'userscore', 'RelDate']

In [9]:
# there was one column with empty value in Sales file. to check if the whole column is empty we do:
# 1):
print("\nNumber of missing values:")
print(df1["Unnamed: 8"].isna().sum())

Number of missing values:
30612

In [10]:
# 2):
print("\nNumber of non-missing values:")
print(df1["Unnamed: 8"].notna().sum())

Number of non-missing values:
0

In [11]:
# So now we can safely remove the column:
df1 = df1.drop(columns=["Unnamed: 8"])

In [12]:
# Checking the columns again:
print("File 1 columns after removing the empty column:")
print(df1.columns.tolist())

File 1 columns after removing the empty column:
['year', 'release_date', 'title', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url']

In [13]:
#  so now we change the name of some columns to have consistent names:
df1 = df1.rename(columns={
    "year": "release_year"
})

df2 = df2.rename(columns={
    "RelDate": "release_date"
})

In [14]:
# we convert column names to lowercase to prevent further problems caused by capitalization:
df1.columns = df1.columns.str.lower()
df2.columns = df2.columns.str.lower()

In [15]:
# to check the names again : 
print("File 1 columns:")
print(df1.columns.tolist())

print("\nFile 2 columns:")
print(df2.columns.tolist())

File 1 columns:
['release_year', 'release_date', 'title', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url']

File 2 columns:
['url', 'title', 'studio', 'rating', 'runtime', 'cast', 'director', 'genre', 'summary', 'awards', 'metascore', 'userscore', 'release_date']

In [16]:
# to check the data types of each Table:
print("File 1 data types:")
print(df1.dtypes)

print("\nFile 2 data types:")
print(df2.dtypes)

File 1 data types:
release_year                  int64
release_date                 object
title                        object
genre                        object
international_box_office    float64
domestic_box_office         float64
worldwide_box_office        float64
production_budget           float64
opening_weekend             float64
theatre_count               float64
avg run per theatre         float64
runtime                     float64
keywords                     object
creative_type                object
url                          object
dtype: object

File 2 data types:
url                     object
title                   object
studio                  object
rating                  object
runtime                float64
cast                    object
director                object
genre                   object
summary                 object
awards                  object
metascore                int64
userscore              float64
release_date    datetime64[ns]
dtype: object

In [17]:
# our finding was:
# File 1 release_year is already numeric.
# File 1 release_date is text (object) and needs special handling later.
# File 2 release_date is already a proper date.
# runtime is numeric in both files.
# Most descriptive fields are text.

In [17]:
# to see how many missing values are in Sales file:
print("Missing values in File 1:")
print(df1.isna().sum().sort_values(ascending=False))

Missing values in File 1:
production_budget           26132
opening_weekend             19683
avg run per theatre         19660
theatre_count               19649
domestic_box_office         18728
keywords                    18095
international_box_office     9037
worldwide_box_office         9037
runtime                      6053
creative_type                3945
genre                        1704
title                           8
release_year                    0
release_date                    0
url                             0
dtype: int64

In [18]:
# we do the same for the second file:
print("\nMissing values in File 2:")
print(df2.isna().sum().sort_values(ascending=False))

Missing values in File 2:
awards          6977
summary         5897
cast            3702
userscore       2105
rating          1067
studio           350
runtime          255
genre             20
director          14
url                0
title              0
metascore          0
release_date       0
dtype: int64

In [19]:
# to see if any placeholder replaced the missing values
missing_values = ["N/A", "n/a", "NA", "na", "NULL", "null", "-", "?"]

print("Placeholder values in File 1:")
for column in df1.columns:
    count = df1[column].isin(missing_values).sum()
    if count > 0:
        print(column, ":", count)

print("\nPlaceholder values in File 2:")
for column in df2.columns:
    count = df2[column].isin(missing_values).sum()
    if count > 0:
        print(column, ":", count)

Placeholder values in File 1:

Placeholder values in File 2:

In [20]:
# We create a seperate cleaned title column which we can use for matching
# to remove unnecessary punctuations and spaced we add a library called RE
import re

In [21]:
# to standardize movie titles and keep missing titles as missing values we create a function: 
def clean_title(title):
    if pd.isna(title):
        return None

#to convert the title to text:
    title = str(title)
#convert all letters to lowercase:
    title = title.lower()
# romove extra spaces from begining and end:
    title = title.strip()
# to remove punctuations and keep letters, numbers, and spaces:
    title = re.sub(r"[^\w\s]", "", title)
# to replace multiple spaces with one space
    title = re.sub(r"\s+", " ", title)

    return title

In [22]:
# now we apply the function to our file:
df1["title_clean"] = df1["title"].apply(clean_title)
df2["title_clean"] = df2["title"].apply(clean_title)

In [23]:
# to compare the original title column with the new column:
print("File 1:")
print(df1[["title", "title_clean"]].head(10))

print("\nFile 2:")
print(df2[["title", "title_clean"]].head(10))

File 1:
                                   title                          title_clean
0                           Bakha Satang                         bakha satang
1                              Antitrust                            antitrust
2                               Santitos                             santitos
3                    Frank McKlusky C.I.                    frank mcklusky ci
4                     A Walk to Remember                   a walk to remember
5                                Zig Zag                              zig zag
6                         TakhtÃƒÂ© siah                        takhtãƒâ siah
7  Angry Monk: Reflections on Tibet, The  angry monk reflections on tibet the
8                       30 Years to Life                     30 years to life
9             The Killing of John Lennon           the killing of john lennon

File 2:
                    title            title_clean
0   !Women Art Revolution   women art revolution
1     10 Cloverfield Lane    10 cloverfield lane
2        10 Items or Less       10 items or less
3                10 Years               10 years
4        100 Bloody Acres       100 bloody acres
5             100 Streets            100 streets
6  1,000 Times Good Night  1000 times good night
7               10,000 BC               10000 bc
8               10,000 km               10000 km
9              1001 Grams             1001 grams

In [25]:
# to check how many times did a title repeated in the same file:
title_counts_1 = df1["title_clean"].value_counts()

print("Duplicate titles in File 1:")
print(title_counts_1[title_counts_1 > 1].head(20))

Duplicate titles in File 1:
title_clean
ride                                5
royal opera house the nutcracker    5
dreamland                           5
a christmas carol                   4
the king                            4
adam                                4
blue                                4
pinocchio                           4
gold                                4
run                                 4
reunion                             4
bolshoi ballet giselle              3
the reckoning                       3
darling                             3
anonymous                           3
vice                                3
the weekend                         3
detour                              3
omerta                              3
macbeth                             3
Name: count, dtype: int64

In [26]:
# and for the second file: 
title_counts_2 = df2["title_clean"].value_counts()

print("\nDuplicate titles in File 2:")
print(title_counts_2[title_counts_2 > 1].head(20))

Duplicate titles in File 2:
title_clean
eden                     3
the circle               3
together                 3
aftermath                3
the square               3
the take                 3
lucky                    3
the outsider             3
the king                 3
innocence                3
domino                   2
the girl on the train    2
the girl next door       2
rams                     2
breathe                  2
november                 2
beneath                  2
the girl                 2
the gift                 2
charlies angels          2
Name: count, dtype: int64

In [27]:
# so it might be same movie names but totally diffrent ones. we need to check them alongside the release years.
# first we extract the released date from file 2:
df2["release_year"] = df2["release_date"].dt.year
print(df2[["release_date", "release_year"]].head(10))

  release_date  release_year
0   2011-06-01          2011
1   2016-03-11          2016
2   2006-12-01          2006
3   2012-09-14          2012
4   2013-06-28          2013
5   2017-01-13          2017
6   2014-10-24          2014
7   2008-03-07          2008
8   2015-07-10          2015
9   2015-05-08          2015

In [28]:
# to spot unusual years:
print("Minimum release year:", df1["release_year"].min())
print("Maximum release year:", df1["release_year"].max())

print("\nRelease year distribution:")
print(df1["release_year"].value_counts().sort_index().head(20))

Minimum release year: 2000
Maximum release year: 2021

Release year distribution:
release_year
2000     504
2001     464
2002     475
2003     554
2004     599
2005     577
2006     649
2007     748
2008     731
2009     625
2010     633
2011     843
2012    1043
2013     997
2014    1150
2015    2427
2016    3029
2017    3177
2018    3343
2019    3385
Name: count, dtype: int64

In [29]:
# to check movies with same name but different years:
df1["movie_key"] = (
    df1["title_clean"].fillna("")
    + "_"
    + df1["release_year"].astype(str)
)

df2["movie_key"] = (
    df2["title_clean"].fillna("")
    + "_"
    + df2["release_year"].astype(str)
)

In [30]:
# original title,release year, and new movie key:
print("File 1:")
print(df1[["title", "release_year", "movie_key"]].head(10))

print("\nFile 2:")
print(df2[["title", "release_year", "movie_key"]].head(10))

File 1:
                                   title  release_year  \
0                           Bakha Satang          2000
1                              Antitrust          2001
2                               Santitos          2000
3                    Frank McKlusky C.I.          2002
4                     A Walk to Remember          2002
5                                Zig Zag          2002
6                         TakhtÃƒÂ© siah          2002
7  Angry Monk: Reflections on Tibet, The          2009
8                       30 Years to Life          2002
9             The Killing of John Lennon          2008

                                  movie_key
0                         bakha satang_2000
1                            antitrust_2001
2                             santitos_2000
3                    frank mcklusky ci_2002
4                   a walk to remember_2002
5                              zig zag_2002
6                        takhtãƒâ siah_2002
7  angry monk reflections on tibet the_2009
8                     30 years to life_2002
9           the killing of john lennon_2008

File 2:
                    title  release_year                   movie_key
0   !Women Art Revolution          2011   women art revolution_2011
1     10 Cloverfield Lane          2016    10 cloverfield lane_2016
2        10 Items or Less          2006       10 items or less_2006
3                10 Years          2012               10 years_2012
4        100 Bloody Acres          2013       100 bloody acres_2013
5             100 Streets          2017            100 streets_2017
6  1,000 Times Good Night          2014  1000 times good night_2014
7               10,000 BC          2008               10000 bc_2008
8               10,000 km          2015               10000 km_2015
9              1001 Grams          2015             1001 grams_2015

In [31]:
# now we check duplicated movie keys:
duplicate_keys_1 = df1["movie_key"].value_counts()

duplicate_keys_1 = duplicate_keys_1[duplicate_keys_1 > 1]
print("Duplicate movie_keys in File 1:")
print(duplicate_keys_1.head(20))

Duplicate movie_keys in File 1:
movie_key
blue_2017                 3
ride_2018                 3
dreamland_2020            3
_2009                     2
greta_2019                2
swan song_2021            2
a christmas carol_2018    2
aftermath_2014            2
best f_2018               2
run_2020                  2
delirium_2018             2
val_2021                  2
clara_2019                2
wuthering heights_2012    2
_2015                     2
the interpreter_2005      2
les affamãƒâs_2018        2
the space between_2017    2
adam_2020                 2
money_2017                2
Name: count, dtype: int64

In [32]:
duplicate_keys_2 = df2["movie_key"].value_counts()

duplicate_keys_2 = duplicate_keys_2[duplicate_keys_2 > 1]
print("\nDuplicate movie_keys in File 2:")
print(duplicate_keys_2.head(20))

Duplicate movie_keys in File 2:
movie_key
the hunter_2012    2
dreamland_2020     2
swan song_2021     2
Name: count, dtype: int64

In [33]:
keys_to_check = [
    "blue_2017",
    "dreamland_2020",
    "_2009"
]

duplicates_file1 = df1[df1["movie_key"].isin(keys_to_check)]
print(duplicates_file1.to_string(index=False))

 release_year  release_date     title             genre  international_box_office  domestic_box_office  worldwide_box_office  production_budget  opening_weekend  theatre_count  avg run per theatre  runtime                                     keywords        creative_type                                                                           url title_clean      movie_key
         2017  October 13th      Blue       Documentary                  103208.0                  NaN              103208.0                NaN              NaN            NaN                  NaN     76.0                                          NaN              Factual                      https://www.the-numbers.com/movie/Blue-(Australia)(2017)        blue      blue_2017
         2017  October 13th      Blue             Drama                  175171.0                  NaN              175171.0                NaN              NaN            NaN                  NaN     97.0                                          NaN Contemporary Fiction                                 https://www.the-numbers.com/movie/Blue-(2015)        blue      blue_2017
         2017    April 21st      Blue       Documentary                   17621.0                  NaN               17621.0                NaN              NaN            NaN                  NaN    100.0                                          NaN              Factual                               https://www.the-numbers.com/movie/Blue-(Turkey)        blue      blue_2017
         2009  October 23rd       NaN               NaN                       NaN             230600.0                   NaN                NaN          18002.0            3.0                  3.0      NaN                                          NaN                  NaN                                  https://www.the-numbers.com/movie/(Untitled)        None          _2009
         2009     July 17th       NaN   Romantic Comedy                 2089638.0           32425665.0            34515303.0          7500000.0         834501.0           27.0                  7.2     95.0                                      Romance Contemporary Fiction                          https://www.the-numbers.com/movie/500-Days-of-Summer        None          _2009
         2020 February 25th Dreamland Thriller/Suspense                  672369.0             409363.0             1081732.0                NaN         178602.0          216.0                  2.5    118.0                               Crime Thriller Contemporary Fiction                            https://www.the-numbers.com/movie/Dreamland-(2020)   dreamland dreamland_2020
         2020 November 13th Dreamland Thriller/Suspense                  238652.0                  NaN              238652.0                NaN              NaN            NaN                  NaN    101.0                               Crime Thriller   Historical Fiction https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)   dreamland dreamland_2020
         2020      June 5th Dreamland      Black Comedy                       NaN                  NaN                   NaN                NaN              NaN            NaN                  NaN     92.0 Early / Simultaneous Video-on-Demand release              Fantasy                          https://www.the-numbers.com/movie/Dreamland-(Canada)   dreamland dreamland_2020

## 2. Further sales and metadata checks — fulldatabase_movies.ipynb

In [34]:
# to make sure we better to check the Url
# so we count the duplicate urls and keep ones which repeated more than once:
# FILE 1
url_counts_1 = df1["url"].value_counts()
duplicate_urls_1 = url_counts_1[url_counts_1 > 1]
print("Duplicate URLs in File 1:")
print(duplicate_urls_1.head(20))

#FILE 2
url_counts_2 = df2["url"].value_counts()
duplicate_urls_2 = url_counts_2[url_counts_2 > 1]
print("\nDuplicate URLs in File 2:")
print(duplicate_urls_2.head(20))

Duplicate URLs in File 1:
Series([], Name: count, dtype: int64)

Duplicate URLs in File 2:
Series([], Name: count, dtype: int64)

In [35]:
# SO no duplicate URL 
# but it still doesn't mean we don't have duplicate movies

In [36]:
# to see how many movies have the same movie_key in each file:
keys_file1 = set(df1["movie_key"])
keys_file2 = set(df2["movie_key"])

common_keys = keys_file1.intersection(keys_file2)

print("Number of movie_keys found in both files:", len(common_keys))
print("\nSample matching movie_keys:")
print(list(common_keys)[:20])

Number of movie_keys found in both files: 8142

Sample matching movie_keys:
['quartet_2012', 'transpecos_2016', 'the internship_2013', 'predators_2010', 'the intended_2004', 'kajillionaire_2020', 'pandaemonium_2001', 'yakuza princess_2021', 'get smart_2008', 'the weight of water_2002', 'hancock_2008', 'the importance of being earnest_2002', 'roadrunner a film about anthony bourdain_2021', 'turistas_2006', 'when a stranger calls_2006', 'empire_2002', 'wahwah_2006', 'flash of genius_2008', 'argentos dracula 3d_2013', 'sonic the hedgehog_2020']

In [37]:
# to find movie keys that exist in both datasets
common_keys = set(df1["movie_key"]).intersection(set(df2["movie_key"]))

# now we count how many times each movie key appears in each dataset
counts_file1 = df1["movie_key"].value_counts()
counts_file2 = df2["movie_key"].value_counts()

# to count only those with one repeatation
unique_matches = sum(
    (counts_file1.get(key, 0) == 1) and
    (counts_file2.get(key, 0) == 1)
    for key in common_keys
)

# Print the total number of common movie keys
print("Common movie_keys:", len(common_keys))

# Print the number of unique 1-to-1 matches
print("Unique 1-to-1 matches:", unique_matches)

# Find movie keys that appear more than once in either dataset
ambiguous_matches = [
    key for key in common_keys
    if counts_file1.get(key, 0) > 1
    or counts_file2.get(key, 0) > 1
]
# Print the number of ambiguous movie keys
print("\nAmbiguous matching keys:", len(ambiguous_matches))

# Print the first 20 ambiguous movie keys
print("Sample ambiguous keys:")
print(ambiguous_matches[:20])

Common movie_keys: 8142
Unique 1-to-1 matches: 8129

Ambiguous matching keys: 13
Sample ambiguous keys:
['val_2021', 'wuthering heights_2012', 'the interpreter_2005', 'greta_2019', 'luca_2021', 'thirst_2009', 'white noise_2005', 'the hunter_2012', 'the outsider_2018', 'aftermath_2014', 'dreamland_2020', 'swan song_2021', 'run_2020']

In [38]:
# we loop through each ambiguous movie key we print a separator and the current movie key

for key in ambiguous_matches:
    print(f"\n{'='*60}")
    print(f"MOVIE KEY: {key}")

    # then we show matching rows from FILE 1
    print("\n--- File 1 ---")
    print(
        df1[df1["movie_key"] == key][
            ["title", "release_year", "movie_key"]
        ].to_string(index=False)
    )

    # then FILE 2
    print("\n--- File 2 ---")
    print(
        df2[df2["movie_key"] == key][
            ["title", "release_date", "movie_key"]
        ].to_string(index=False)
    )

============================================================
MOVIE KEY: val_2021

--- File 1 ---
title  release_year movie_key
  Val          2021  val_2021
  Val          2021  val_2021

--- File 2 ---
title release_date movie_key
  Val   2021-07-23  val_2021

============================================================
MOVIE KEY: wuthering heights_2012

--- File 1 ---
            title  release_year              movie_key
Wuthering Heights          2012 wuthering heights_2012
Wuthering Heights          2012 wuthering heights_2012

--- File 2 ---
            title release_date              movie_key
Wuthering Heights   2012-10-05 wuthering heights_2012

============================================================
MOVIE KEY: the interpreter_2005

--- File 1 ---
          title  release_year            movie_key
The Interpreter          2005 the interpreter_2005
The Interpreter          2005 the interpreter_2005

--- File 2 ---
          title release_date            movie_key
The Interpreter   2005-04-22 the interpreter_2005

============================================================
MOVIE KEY: greta_2019

--- File 1 ---
title  release_year  movie_key
Greta          2019 greta_2019
Greta          2019 greta_2019

--- File 2 ---
title release_date  movie_key
Greta   2019-03-01 greta_2019

============================================================
MOVIE KEY: luca_2021

--- File 1 ---
title  release_year movie_key
 Luca          2021 luca_2021
 Luca          2021 luca_2021

--- File 2 ---
title release_date movie_key
 Luca   2021-06-18 luca_2021

============================================================
MOVIE KEY: thirst_2009

--- File 1 ---
 title  release_year   movie_key
Thirst          2009 thirst_2009
Thirst          2009 thirst_2009

--- File 2 ---
 title release_date   movie_key
Thirst   2009-07-31 thirst_2009

============================================================
MOVIE KEY: white noise_2005

--- File 1 ---
      title  release_year        movie_key
White Noise          2005 white noise_2005
White Noise          2005 white noise_2005

--- File 2 ---
      title release_date        movie_key
White Noise   2005-01-07 white noise_2005

============================================================
MOVIE KEY: the hunter_2012

--- File 1 ---
     title  release_year       movie_key
The Hunter          2012 the hunter_2012

--- File 2 ---
     title release_date       movie_key
The Hunter   2012-01-04 the hunter_2012
The Hunter   2012-04-06 the hunter_2012

============================================================
MOVIE KEY: the outsider_2018

--- File 1 ---
       title  release_year         movie_key
The Outsider          2018 the outsider_2018
The Outsider          2018 the outsider_2018

--- File 2 ---
       title release_date         movie_key
The Outsider   2018-03-09 the outsider_2018

============================================================
MOVIE KEY: aftermath_2014

--- File 1 ---
    title  release_year      movie_key
Aftermath          2014 aftermath_2014
Aftermath          2014 aftermath_2014

--- File 2 ---
    title release_date      movie_key
Aftermath   2014-07-18 aftermath_2014

============================================================
MOVIE KEY: dreamland_2020

--- File 1 ---
    title  release_year      movie_key
Dreamland          2020 dreamland_2020
Dreamland          2020 dreamland_2020
Dreamland          2020 dreamland_2020

--- File 2 ---
    title release_date      movie_key
Dreamland   2020-11-13 dreamland_2020
Dreamland   2020-06-05 dreamland_2020

============================================================
MOVIE KEY: swan song_2021

--- File 1 ---
    title  release_year      movie_key
Swan Song          2021 swan song_2021
Swan Song          2021 swan song_2021

--- File 2 ---
    title release_date      movie_key
Swan Song   2021-08-06 swan song_2021
Swan Song   2021-12-17 swan song_2021

============================================================
MOVIE KEY: run_2020

--- File 1 ---
title  release_year movie_key
  Run          2020  run_2020
  Run          2020  run_2020

--- File 2 ---
title release_date movie_key
  Run   2020-11-20  run_2020

In [39]:
# SO exept 2 movies the other ones are DUPLICATES

In [40]:
# Checking additional columns:
for key in ambiguous_matches:
    print(f"\n{'='*60}")
    print(f"MOVIE KEY: {key}")

    print("\n--- File 1 ---")
    print(
        df1[df1["movie_key"] == key][
            ["title", "release_year", "release_date", "url"]
        ].to_string(index=False)
    )

    print("\n--- File 2 ---")
    print(
        df2[df2["movie_key"] == key][
            ["title", "release_date", "studio", "director"]
        ].to_string(index=False)
    )

============================================================
MOVIE KEY: val_2021

--- File 1 ---
title  release_year release_date                                                            url
  Val          2021  October 1st https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)
  Val          2021    July 23rd       https://www.the-numbers.com/movie/Val-(2021-Documentary)

--- File 2 ---
title release_date         studio  director
  Val   2021-07-23 Amazon Studios Leo Scott

============================================================
MOVIE KEY: wuthering heights_2012

--- File 1 ---
            title  release_year release_date                                                        url
Wuthering Heights          2012  October 5th https://www.the-numbers.com/movie/Wuthering-Heights-(2011)
Wuthering Heights          2012   March 30th https://www.the-numbers.com/movie/Wuthering-Heights-(2009)

--- File 2 ---
            title release_date                studio      director
Wuthering Heights   2012-10-05 Oscilloscope Pictures Andrea Arnold

============================================================
MOVIE KEY: the interpreter_2005

--- File 1 ---
          title  release_year release_date                                                                 url
The Interpreter          2005   April 22nd            https://www.the-numbers.com/movie/Interpreter-The-(2005)
The Interpreter          2005   April 15th https://www.the-numbers.com/movie/Interpreter-The-(Slovakia)-(2018)

--- File 2 ---
          title release_date             studio       director
The Interpreter   2005-04-22 Universal Pictures Sydney Pollack

============================================================
MOVIE KEY: greta_2019

--- File 1 ---
title  release_year release_date                                              url
Greta          2019 October 10th https://www.the-numbers.com/movie/Greta-(Brazil)
Greta          2019    March 1st   https://www.the-numbers.com/movie/Greta-(2019)

--- File 2 ---
title release_date         studio    director
Greta   2019-03-01 Focus Features Neil Jordan

============================================================
MOVIE KEY: luca_2021

--- File 1 ---
title  release_year release_date                                                   url
 Luca          2021    June 18th         https://www.the-numbers.com/movie/Luca-(2021)
 Luca          2021     May 28th https://www.the-numbers.com/movie/Luca-(2021-Romania)

--- File 2 ---
title release_date                              studio        director
 Luca   2021-06-18 Walt Disney Studios Motion Pictures Enrico Casarosa

============================================================
MOVIE KEY: thirst_2009

--- File 1 ---
 title  release_year release_date                                             url
Thirst          2009   April 30th https://www.the-numbers.com/movie/Thirst-(2009)
Thirst          2009    July 31st        https://www.the-numbers.com/movie/Thirst

--- File 2 ---
 title release_date         studio       director
Thirst   2009-07-31 Focus Features Chan-wook Park

============================================================
MOVIE KEY: white noise_2005

--- File 1 ---
      title  release_year release_date                                                  url
White Noise          2005   April 22nd https://www.the-numbers.com/movie/White-Noise-(2020)
White Noise          2005  January 7th https://www.the-numbers.com/movie/White-Noise-(2005)

--- File 2 ---
      title release_date             studio     director
White Noise   2005-01-07 Universal Pictures Geoffrey Sax

============================================================
MOVIE KEY: the hunter_2012

--- File 1 ---
     title  release_year release_date                                                 url
The Hunter          2012    April 6th https://www.the-numbers.com/movie/Hunter-The-(2011)

--- File 2 ---
     title release_date            studio        director
The Hunter   2012-01-04       Olive Films      Rafi Pitts
The Hunter   2012-04-06 Magnolia Pictures Daniel Nettheim

============================================================
MOVIE KEY: the outsider_2018

--- File 1 ---
       title  release_year release_date                                                                  url
The Outsider          2018   April 20th https://www.the-numbers.com/movie/Outsider-The-(2018-United-Kingdom)
The Outsider          2018   April 20th                https://www.the-numbers.com/movie/Outsider-The-(2018)

--- File 2 ---
       title release_date  studio         director
The Outsider   2018-03-09 Netflix Martin Zandvliet

============================================================
MOVIE KEY: aftermath_2014

--- File 1 ---
    title  release_year  release_date                                                url
Aftermath          2014 November 28th https://www.the-numbers.com/movie/Aftermath-(2013)
Aftermath          2014     July 18th https://www.the-numbers.com/movie/Aftermath-(2012)

--- File 2 ---
    title release_date              studio     director
Aftermath   2014-07-18 Image Entertainment Peter Engert

============================================================
MOVIE KEY: dreamland_2020

--- File 1 ---
    title  release_year  release_date                                                                           url
Dreamland          2020 February 25th                            https://www.the-numbers.com/movie/Dreamland-(2020)
Dreamland          2020 November 13th https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)
Dreamland          2020      June 5th                          https://www.the-numbers.com/movie/Dreamland-(Canada)

--- File 2 ---
    title release_date                 studio               director
Dreamland   2020-11-13     Paramount Pictures Miles Joris-Peyrafitte
Dreamland   2020-06-05 Uncork'd Entertainment         Bruce McDonald

============================================================
MOVIE KEY: swan song_2021

--- File 1 ---
    title  release_year  release_date                                                                  url
Swan Song          2021 December 17th                   https://www.the-numbers.com/movie/Swan-Song-(2021)
Swan Song          2021    August 6th https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)

--- File 2 ---
    title release_date            studio        director
Swan Song   2021-08-06 Magnolia Pictures   Todd Stephens
Swan Song   2021-12-17         Apple TV+ Benjamin Cleary

============================================================
MOVIE KEY: run_2020

--- File 1 ---
title  release_year        release_date                                          url
  Run          2020 2020 (Canceled) by  https://www.the-numbers.com/movie/Run-(2020)
  Run          2020          March 13th   https://www.the-numbers.com/movie/Run-(UK)

--- File 2 ---
title release_date studio        director
  Run   2020-11-20   Hulu Aneesh Chaganty

In [ ]:
# Summary of the 13 ambiguous movie keys:


# dreamland_2020 ------ Multiple different movies
# greta_2019 ------ One movie matches; the other is from Brazil
# wuthering heights_2012, run_2020, the hunter_2012, val_2021,
# swan song_2021, aftermath_2014, the outsider_2018 ------ Two different movies
# the interpreter_2005, luca_2021, thirst_2009, white noise_2005 ------ One movie matches

In [ ]:
# 1)Check exact duplicate rows

In [41]:
# Count the number of completely duplicated rows in File 1
duplicate_rows_file1 = df1.duplicated().sum()

# Count the number of completely duplicated rows in File 2
duplicate_rows_file2 = df2.duplicated().sum()

# Print the duplicate counts
print("Exact duplicate rows in File 1:", duplicate_rows_file1)
print("Exact duplicate rows in File 2:", duplicate_rows_file2)

Exact duplicate rows in File 1: 0
Exact duplicate rows in File 2: 0

In [42]:
# 2) checking missing values

missing_file1 = df1.isna().sum()
missing_file2 = df2.isna().sum()

print("--- Missing values in File 1 ---")
print(missing_file1[missing_file1 > 0].sort_values(ascending=False))

print("\n--- Missing values in File 2 ---")
print(missing_file2[missing_file2 > 0].sort_values(ascending=False))

--- Missing values in File 1 ---
production_budget           26132
opening_weekend             19683
avg run per theatre         19660
theatre_count               19649
domestic_box_office         18728
keywords                    18095
international_box_office     9037
worldwide_box_office         9037
runtime                      6053
creative_type                3945
genre                        1704
title                           8
title_clean                     8
dtype: int64

--- Missing values in File 2 ---
awards       6977
summary      5897
cast         3702
userscore    2105
rating       1067
studio        350
runtime       255
genre          20
director       14
dtype: int64

In [43]:
print("--- File 1 columns ---")
print(df1.columns.tolist())

print("\n--- File 2 columns ---")
print(df2.columns.tolist())

--- File 1 columns ---
['release_year', 'release_date', 'title', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url', 'title_clean', 'movie_key']

--- File 2 columns ---
['url', 'title', 'studio', 'rating', 'runtime', 'cast', 'director', 'genre', 'summary', 'awards', 'metascore', 'userscore', 'release_date', 'title_clean', 'release_year', 'movie_key']

In [44]:
# Check the data type of each column in File 1

print("--- File 1 data types ---")

print(df1.dtypes)

# Check the data type of each column in File 2

print("\n--- File 2 data types ---")

print(df2.dtypes)

--- File 1 data types ---
release_year                  int64
release_date                 object
title                        object
genre                        object
international_box_office    float64
domestic_box_office         float64
worldwide_box_office        float64
production_budget           float64
opening_weekend             float64
theatre_count               float64
avg run per theatre         float64
runtime                     float64
keywords                     object
creative_type                object
url                          object
title_clean                  object
movie_key                    object
dtype: object

--- File 2 data types ---
url                     object
title                   object
studio                  object
rating                  object
runtime                float64
cast                    object
director                object
genre                   object
summary                 object
awards                  object
metascore                int64
userscore              float64
release_date    datetime64[ns]
title_clean             object
release_year             int32
movie_key               object
dtype: object

### Numeric-column check

This original cell is placed before the next section because it refers to `avg run per theatre`, which the next section renames.

In [46]:
numeric_columns_file1 = [

    "international_box_office",

    "domestic_box_office",

    "worldwide_box_office",

    "production_budget",

    "opening_weekend",

    "theatre_count",

    "avg run per theatre",

    "runtime"

]

print(df1[numeric_columns_file1].agg(["min", "max"]).T)

                             min           max
international_box_office     2.0  2.085392e+09
domestic_box_office         20.0  9.366622e+08
worldwide_box_office         2.0  2.845900e+09
production_budget         1100.0  4.000000e+08
opening_weekend             11.0  3.571150e+08
theatre_count                1.0  4.725000e+03
avg run per theatre          0.0  8.840000e+01
runtime                     11.0  2.020000e+03

## 3. Additional sales cleaning — cleaning9.22.ipynb

The date-string work appears before the later datetime conversion. The two temporary `df1` movie-ID cells are retained in section 5, after the movie-building code, so their temporary ID does not enter the earlier merges.

In [89]:
df1

,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url,title_clean,movie_key
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021
30608,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021
30609,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021
30610,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021
30611,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021

In [90]:
#for syntax compability we need to rename avg run per theatre
df1.rename(columns={"avg run per theatre":"avg_run_per_theatre"},inplace=True)
df1

,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021
30608,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021
30609,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021
30610,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021
30611,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021

In [91]:
rows = df1[:10]
print(rows)

   release_year     release_date                                  title  \
0          2000      January 1st                           Bakha Satang
1          2001     January 12th                              Antitrust
2          2000     January 28th                               Santitos
3          2002  2002 (Wide) by                     Frank McKlusky C.I.
4          2002     January 25th                     A Walk to Remember
5          2002        June 21st                                Zig Zag
6          2002         May 10th                         TakhtÃƒÂ© siah
7          2009      January 2nd  Angry Monk: Reflections on Tibet, The
8          2002         June 7th                       30 Years to Life
9          2008      January 2nd             The Killing of John Lennon

               genre  international_box_office  domestic_box_office  \
0              Drama                   76576.0                  NaN
1  Thriller/Suspense                 6900000.0           10965209.0
2                NaN                       NaN             378562.0
3                NaN                       NaN                  NaN
4              Drama                 4833792.0           41227069.0
5                NaN                       NaN               1649.0
6              Drama                       NaN              21324.0
7        Documentary                       NaN               2125.0
8             Comedy                       NaN              99023.0
9              Drama                       NaN               6975.0

   worldwide_box_office  production_budget  opening_weekend  theatre_count  \
0               76576.0                NaN              NaN            NaN
1            17865209.0         30000000.0        5486209.0         2433.0
2                   NaN                NaN              NaN            NaN
3                   NaN                NaN              NaN            NaN
4            46060861.0         11000000.0       12177488.0         2411.0
5                   NaN                NaN           1649.0            1.0
6                   NaN                NaN           1500.0            5.0
7                   NaN                NaN           2125.0            1.0
8                   NaN                NaN           3376.0            1.0
9                   NaN                NaN           3077.0            1.0

   avg_run_per_theatre  runtime          keywords         creative_type  \
0                  NaN    129.0               NaN  Contemporary Fiction
1                  3.1      NaN               NaN  Contemporary Fiction
2                  NaN    105.0               NaN                   NaN
3                  NaN      NaN               NaN                   NaN
4                  5.3      NaN     Coming of Age  Contemporary Fiction
5                  1.0      NaN               NaN                   NaN
6                  2.0      NaN  Foreign Language                   NaN
7                  1.0      NaN               NaN               Factual
8                  3.3      NaN               NaN                   NaN
9                  3.0      NaN               NaN         Dramatization

                                                 url  \
0  https://www.the-numbers.com/movie/Bakha-Satang...
1        https://www.the-numbers.com/movie/Antitrust
2         https://www.the-numbers.com/movie/Santitos
3  https://www.the-numbers.com/movie/Frank-McKlus...
4  https://www.the-numbers.com/movie/Walk-to-Reme...
5          https://www.the-numbers.com/movie/Zig-Zag
6      https://www.the-numbers.com/movie/Takhte-siah
7  https://www.the-numbers.com/movie/Angry-Monk-R...
8  https://www.the-numbers.com/movie/30-Years-to-...
9  https://www.the-numbers.com/movie/Killing-of-J...

                           title_clean  \
0                         bakha satang
1                            antitrust
2                             santitos
3                    frank mcklusky ci
4                   a walk to remember
5                              zig zag
6                        takhtãƒâ siah
7  angry monk reflections on tibet the
8                     30 years to life
9           the killing of john lennon

                                  movie_key
0                         bakha satang_2000
1                            antitrust_2001
2                             santitos_2000
3                    frank mcklusky ci_2002
4                   a walk to remember_2002
5                              zig zag_2002
6                        takhtãƒâ siah_2002
7  angry monk reflections on tibet the_2009
8                     30 years to life_2002
9           the killing of john lennon_2008

In [121]:
#sorting by longest runtime to ingvestigate
sort1 = df1.sort_values(["runtime"],ascending=False).head(20)
sort1

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,Unnamed: 8,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url
24691,2019,August 2nd,La Flor,Drama,1520.0,NaN,1520.0,NaN,NaN,NaN,NaN,NaN,803.0,NaN,Fantasy,https://www.the-numbers.com/movie/Flor-La-(Arg...
3427,2015,November 27th,"Out 1, noli me tangere",Drama,6204.0,NaN,6204.0,NaN,NaN,NaN,NaN,NaN,760.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Out-1-noli-m...
28613,2021,July 16th,The Works and Days,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,480.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Works-and-Da...
22311,2004,April 9th,The Cremaster Cycle,Drama,11219.0,151239.0,162458.0,NaN,NaN,7982.0,1.0,12.0,398.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Cremaster-Cy...
21828,2004,March 2nd,La meglio gioventÃƒÂ¹,Drama,2419029.0,270810.0,2689839.0,NaN,NaN,7490.0,1.0,9.0,366.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Meglio-giove...
1608,2018,October 26th,Royal Opera House: Die Walkure,Concert/Performance,257146.0,NaN,257146.0,NaN,NaN,NaN,NaN,NaN,350.0,Opera,NaN,https://www.the-numbers.com/movie/Royal-Opera-...
14346,2007,November 7th,La commune,Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,345.0,NaN,Dramatization,https://www.the-numbers.com/movie/commune-Pari...
3359,2016,October 6th,Homeland: Iraq Year Zero,Documentary,NaN,2491.0,NaN,NaN,NaN,560.0,1.0,1.0,334.0,2000s,Factual,https://www.the-numbers.com/movie/Homeland-Ira...
13452,2018,February 9th,2018 Oscar Shorts,Multiple Genres,2345.0,3508777.0,3511122.0,NaN,NaN,695044.0,198.0,3.8,328.0,Compilations,Multiple Creative Types,https://www.the-numbers.com/movie/2018-Oscar-S...
3145,2015,December 4th,River of Fundament,Drama,NaN,44840.0,NaN,NaN,NaN,4938.0,1.0,7.0,319.0,Experimental Film,Fantasy,https://www.the-numbers.com/movie/River-of-Fun...
18436,2006,August 18th,The Pusher Trilogy,NaN,NaN,4815.0,NaN,NaN,NaN,1792.0,1.0,2.0,318.0,NaN,NaN,https://www.the-numbers.com/movie/Pusher-Trilo...
20057,2010,January 26th,The Weathered Underground,Multiple Genres,NaN,140091.0,NaN,NaN,NaN,1010.0,3.0,3.1,310.0,Directing Yourself,Contemporary Fiction,https://www.the-numbers.com/movie/Weathered-Un...
1412,2018,November 2nd,League Of Legends World Championship 2018,Concert/Performance,45349.0,NaN,45349.0,NaN,NaN,NaN,NaN,NaN,300.0,NaN,NaN,https://www.the-numbers.com/movie/League-Of-Le...
835,2018,November 16th,Opera De Paris: Les Huguenots,Concert/Performance,4223.0,NaN,4223.0,NaN,NaN,NaN,NaN,NaN,300.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Opera-De-Par...
27899,2019,March 29th,Met Opera: Die Walkure,Concert/Performance,941763.0,NaN,941763.0,NaN,NaN,NaN,NaN,NaN,295.0,Opera,Historical Fiction,https://www.the-numbers.com/movie/Met-Opera-Di...
3244,2016,October 7th,Tristan und Isolde - Met Opera 2016,Concert/Performance,290749.0,NaN,290749.0,NaN,NaN,NaN,NaN,NaN,287.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Met-Opera-Tr...
585,2017,December 1st,Opera De Paris: Don Carlos,Concert/Performance,10610.0,NaN,10610.0,NaN,NaN,NaN,NaN,NaN,280.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Opera-De-Par...
19105,2014,January 15th,"Unsere Mutter, unsere Vater",Drama,NaN,91595.0,NaN,NaN,NaN,7386.0,1.0,4.3,279.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Unsere-Mutte...
1013,2018,November 14th,Shoah Four Sisters,Documentary,NaN,5512.0,NaN,NaN,NaN,2840.0,1.0,1.3,273.0,Holocaust,Factual,https://www.the-numbers.com/movie/Shoah-Four-S...
22957,2019,November 23rd,Wilder vs. Ortiz,Concert/Performance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,270.0,NaN,Factual,https://www.the-numbers.com/movie/Wilder-vs-Ortiz

In [120]:
#some runtimes are unusually long, investigated all movies with runtimes over 350 minutes to check if they are actually that long
# some runtimes are wrong, replacing them with correct values
df1.loc[df1["title"] =="Barbara Lee: Speaking Truth to Power", "runtime" ] = 82
df1.loc[df1["title"] =="Amazonia", "runtime" ] = 67
df1.loc[df1["title"] =="Meesterspion", "runtime" ] = 100
df1.loc[df1["title"] =="AmÃ…Â¾inai kartu", "runtime" ] = 88

In [97]:
#investigating weird release dates
df1["release_date"].unique()

<ArrowStringArray>
[             'January 1st',             'January 12th',
             'January 28th',          '2002 (Wide) by ',
             'January 25th',                'June 21st',
                 'May 10th',              'January 2nd',
                 'June 7th',             'January 18th',
 ...
           '2003 (Limited)',              '2002 (Wide)',
            '2020 (Wide) (',      '2020 (Canceled) by ',
 'Fall 2020 (Canceled) by ',          '2022 (Wide) by ',
            '2021 (Wide) (',                   'Summer',
      '2022 (Canceled) by ',      '2021 (Canceled) by ']
Length: 392, dtype: str

In [98]:
#some release dates dont actually contain date but different information
#to preserve the extra information we create an extra date column to clean it
df1["release_date_clean"] = df1["release_date"]

In [99]:
df1

,movie_id,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key,release_date_clean
0,1,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000,January 1st
1,2,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001,January 12th
2,3,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000,January 28th
3,4,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002,2002 (Wide) by
4,5,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002,January 25th
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,30608,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021,January 1st
30608,30609,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021,March 5th
30609,30610,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021,January 1st
30610,30611,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021,May 21st
30611,30612,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021,January 1st

In [100]:
#seeing how many rows contain information different from date
df1["release_date"].str.contains("Wide", case=False, na=False).sum()

np.int64(9)

In [101]:
df1["release_date"].str.contains("Canceled", case=False, na=False).sum()

np.int64(13)

In [102]:
#in the clean release date column, we replace those unfittting values with nan
df1.loc[df1["release_date_clean"].str.contains("Wide|Canceled",case=False,na=False),"release_date_clean"] = np.nan

In [103]:
df1

,movie_id,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key,release_date_clean
0,1,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000,January 1st
1,2,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001,January 12th
2,3,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000,January 28th
3,4,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002,NaN
4,5,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002,January 25th
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,30608,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021,January 1st
30608,30609,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021,March 5th
30609,30610,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021,January 1st
30610,30611,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021,May 21st
30611,30612,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021,January 1st

In [104]:
df1["release_date_clean"] = (
    df1["release_date_clean"]
    .str.replace("st", "")
    .str.replace("nd", "")
    .str.replace("rd", "")
    .str.replace("th", "")
)

In [105]:
df1

,movie_id,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key,release_date_clean
0,1,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000,January 1
1,2,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001,January 12
2,3,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000,January 28
3,4,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002,NaN
4,5,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002,January 25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,30608,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021,January 1
30608,30609,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021,March 5
30609,30610,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021,January 1
30610,30611,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021,May 21
30611,30612,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021,January 1

In [ ]:
#combining 2 column to create full data column
#errors="coerce" tells pandas: If you find a value that you can't convert, don't give me an error — turn it into a missing value instead.
df1["full_release_date"] = pd.to_datetime(
    df1["release_date_clean"] + " " + df1["release_year"].astype(str),
    errors="coerce"
)

In [109]:
df1

,movie_id,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key,release_date_clean,full_release_date
0,1,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000,January 1,2000-01-01
1,2,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001,January 12,2001-01-12
2,3,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000,January 28,2000-01-28
3,4,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002,NaN,NaT
4,5,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002,January 25,2002-01-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,30608,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021,January 1,2021-01-01
30608,30609,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021,March 5,2021-03-05
30609,30610,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021,January 1,2021-01-01
30610,30611,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021,May 21,2021-05-21
30611,30612,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021,January 1,2021-01-01

## 4. Remaining movie work — fulldatabase_movies.ipynb

All remaining original cells follow in their original relative order. This section contains another set of runtime corrections, including different values for Amazonia and Meesterspion; both original versions remain for the group to resolve. Existing exports and saved errors are also retained.

In [45]:
# Convert the release_date column in File 1 to datetime format
df1["release_date"] = pd.to_datetime(df1["release_date"], errors="coerce")

# Check the data type after conversion
print(df1["release_date"].dtype)

datetime64[ns]

/var/folders/f3/yq1mg8dd1bg6q2h4kq3jpp840000gn/T/ipykernel_44589/235349216.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df1["release_date"] = pd.to_datetime(df1["release_date"], errors="coerce")

In [47]:
# Find movies with unusually high runtime values
unusual_runtime = df1[df1["runtime"] > 300][
    ["title", "release_year", "runtime"]
].sort_values("runtime", ascending=False)

# Display the unusual runtime values
print(unusual_runtime)

                                      title  release_year  runtime
27957  Barbara Lee: Speaking Truth to Power          2021   2020.0
7179                               Amazonia          2015    983.0
16350                      AmÃ…Â¾inai kartu          2017    980.0
24691                               La Flor          2019    803.0
3431                           Meesterspion          2016    770.0
3427                 Out 1, noli me tangere          2015    760.0
28613                    The Works and Days          2021    480.0
22311                   The Cremaster Cycle          2004    398.0
21828                 La meglio gioventÃƒÂ¹          2004    366.0
1608         Royal Opera House: Die Walkure          2018    350.0
14346                            La commune          2007    345.0
3359               Homeland: Iraq Year Zero          2016    334.0
13452                     2018 Oscar Shorts          2018    328.0
3145                     River of Fundament          2015    319.0
18436                    The Pusher Trilogy          2006    318.0
20057             The Weathered Underground          2010    310.0

In [48]:
# Check the complete row for the suspicious runtime value
print(df1[df1["title"] == "Barbara Lee: Speaking Truth to Power"].T)

                                                                      27957
release_year                                                           2021
release_date                                                            NaT
title                                  Barbara Lee: Speaking Truth to Power
genre                                                           Documentary
international_box_office                                                NaN
domestic_box_office                                                     NaN
worldwide_box_office                                                    NaN
production_budget                                                       NaN
opening_weekend                                                         NaN
theatre_count                                                           NaN
avg run per theatre                                                     NaN
runtime                                                              2020.0
keywords                                                                NaN
creative_type                                                       Factual
url                       https://www.the-numbers.com/movie/Barbara-Lee-...
title_clean                             barbara lee speaking truth to power
movie_key                          barbara lee speaking truth to power_2021

In [49]:
# Find the same movie in File 2 using the movie_key

print(
    df2[df2["movie_key"] == "barbara lee speaking truth to power_2021"].T
)

Empty DataFrame
Columns: []
Index: [url, title, studio, rating, runtime, cast, director, genre, summary, awards, metascore, userscore, release_date, title_clean, release_year, movie_key]

In [50]:
# Correct the runtime for Barbara Lee: Speaking Truth to Power

df1.loc[
    df1["title"] == "Barbara Lee: Speaking Truth to Power",
    "runtime"
] = 82

# Verify the corrected value
print(
    df1.loc[
        df1["title"] == "Barbara Lee: Speaking Truth to Power",
        ["title", "runtime"]
    ]
)

                                      title  runtime
27957  Barbara Lee: Speaking Truth to Power     82.0

In [51]:
# Correct the runtime for Amazonia

df1.loc[
    df1["title"] == "Amazonia",
    "runtime"
] = 83

# Correct the runtime for Amžinai kartu
df1.loc[
    df1["title"] == "AmÃ…Â¾inai kartu",
    "runtime"
] = 88

# Correct the runtime for Meesterspion
df1.loc[
    df1["title"] == "Meesterspion",
    "runtime"
] = 74

# Verify all three corrected values
print(
    df1[df1["title"].isin([
        "Amazonia",
        "AmÃ…Â¾inai kartu",
        "Meesterspion"
    ])][["title", "runtime"]]
)

                  title  runtime
3431       Meesterspion     74.0
7179           Amazonia     83.0
16350  AmÃ…Â¾inai kartu     88.0

In [52]:
# Remove the ambiguous movie keys from the common keys
unique_match_keys = set(common_keys) - set(ambiguous_matches)

# Display the number of unique matches
print("Unique matches:", len(unique_match_keys))

Unique matches: 8129

In [53]:
# Keep only the uniquely matched movies from File 1
df1_unique = df1[df1["movie_key"].isin(unique_match_keys)].copy()

# Keep only the uniquely matched movies from File 2
df2_unique = df2[df2["movie_key"].isin(unique_match_keys)].copy()

# Merge the two files using the unique movie_key
merged_df = pd.merge(
    df1_unique,
    df2_unique,
    on="movie_key",
    how="inner",
    suffixes=("_file1", "_file2")
)

# Display the shape of the merged dataset
print("Merged dataset shape:", merged_df.shape)

# Display the first five rows
print(merged_df.head())

Merged dataset shape: (8129, 32)
   release_year_file1 release_date_file1                 title_file1  \
0                2001                NaT                   Antitrust
1                2000                NaT                    Santitos
2                2002                NaT          A Walk to Remember
3                2008                NaT  The Killing of John Lennon
4                2008                NaT                   Mad Money

         genre_file1  international_box_office  domestic_box_office  \
0  Thriller/Suspense                 6900000.0           10965209.0
1                NaN                       NaN             378562.0
2              Drama                 4833792.0           41227069.0
3              Drama                       NaN               6975.0
4             Comedy                 4375214.0           20668843.0

   worldwide_box_office  production_budget  opening_weekend  theatre_count  \
0            17865209.0         30000000.0        5486209.0         2433.0
1                   NaN                NaN              NaN            NaN
2            46060861.0         11000000.0       12177488.0         2411.0
3                   NaN                NaN           3077.0            1.0
4            25044057.0         22000000.0        7736452.0         2470.0

   ...                                     cast             director  \
0  ...               Ryan Phillippe,Tim Robbins         Peter Howitt
1  ...                                      NaN  Alejandro Springall
2  ...                   Mandy Moore,Shane West        Adam Shankman
3  ...                               Jonas Ball    Andrew Piddington
4  ...  Diane Keaton,Katie Holmes,Queen Latifah        Callie Khouri

                     genre_file2  \
0                 Drama,Thriller
1                   Drama,Comedy
2                  Drama,Romance
3                    Drama,Crime
4  Thriller,Comedy,Romance,Crime

                                             summary  \
0  A relentless suspense thriller that enters the...
1  Alejandro Springall directs this Spanish-langu...
2  Set in the lowlands of North Carolina, this st...
3                                                NaN
4                                                NaN

                                              awards metascore userscore  \
0                        #68MostDiscussedMovieof2001        31       8.7
1                                                NaN        68       NaN
2  #28MostDiscussedMovieof2002 , #10MostSharedMov...        35       8.3
3                                                NaN        49       6.4
4                                                NaN        41       6.4

  release_date_file2           title_clean_file2 release_year_file2
0         2001-01-12                   antitrust               2001
1         2000-01-28                    santitos               2000
2         2002-01-25          a walk to remember               2002
3         2008-01-02  the killing of john lennon               2008
4         2008-01-18                   mad money               2008

[5 rows x 32 columns]

In [54]:
# Display all columns in the merged dataset
for i, column in enumerate(merged_df.columns, start=1):
    print(i, column)

1 release_year_file1
2 release_date_file1
3 title_file1
4 genre_file1
5 international_box_office
6 domestic_box_office
7 worldwide_box_office
8 production_budget
9 opening_weekend
10 theatre_count
11 avg run per theatre
12 runtime_file1
13 keywords
14 creative_type
15 url_file1
16 title_clean_file1
17 movie_key
18 url_file2
19 title_file2
20 studio
21 rating
22 runtime_file2
23 cast
24 director
25 genre_file2
26 summary
27 awards
28 metascore
29 userscore
30 release_date_file2
31 title_clean_file2
32 release_year_file2

In [55]:
# Compare duplicated title columns between the two files
title_match = (
    merged_df["title_file1"].fillna("").str.strip().str.lower()
    == merged_df["title_file2"].fillna("").str.strip().str.lower()
)

# Compare duplicated release year columns
year_match = (
    merged_df["release_year_file1"]
    == merged_df["release_year_file2"]
)

# Compare duplicated cleaned title columns
clean_title_match = (
    merged_df["title_clean_file1"]
    == merged_df["title_clean_file2"]
)

# Print the number of matching and non-matching values
print("Title matches:", title_match.sum())
print("Title differences:", (~title_match).sum())

print("Year matches:", year_match.sum())
print("Year differences:", (~year_match).sum())

print("Clean title matches:", clean_title_match.sum())
print("Clean title differences:", (~clean_title_match).sum())

Title matches: 7975
Title differences: 154
Year matches: 8129
Year differences: 0
Clean title matches: 8129
Clean title differences: 0

In [56]:
# Display movies where the original titles differ between the two files
title_differences = merged_df[
    ~title_match
][[
    "title_file1",
    "title_file2",
    "release_year_file1",
    "movie_key"
]]

# Display all title differences
print(title_differences.to_string(index=False))

                                                  title_file1                                                    title_file2  release_year_file1                                                          movie_key
                                           Shoah Four Sisters                                            Shoah: Four Sisters                2018                                            shoah four sisters_2018
              A Bread Factory, Part Two: Walk With Me A While                 A Bread Factory Part Two: Walk With Me a While                2018                 a bread factory part two walk with me a while_2018
              A Bread Factory, Part One: For the Sake of Gold                 A Bread Factory Part One: For the Sake of Gold                2018                 a bread factory part one for the sake of gold_2018
                                                         1985                                                           1985                2018                                                          1985_2018
                                                         1945                                                           1945                2017                                                          1945_2017
                                             Kusama: Infinity                                              Kusama - Infinity                2018                                               kusama infinity_2018
                                                     Black 47                                                      Black '47                2018                                                      black 47_2018
                                     What Happened to Monday?                                        What Happened to Monday                2017                                       what happened to monday_2017
                                                           31                                                             31                2016                                                            31_2016
               Lo And Behold, Reveries Of The Connected World                 Lo and Behold: Reveries of the Connected World                2016                 lo and behold reveries of the connected world_2016
                                 Mamma Mia: Here We Go Again!                                    Mamma Mia! Here We Go Again                2018                                    mamma mia here we go again_2018
                                  Milford Graves: Full Mantis                                     Milford Graves Full Mantis                2018                                    milford graves full mantis_2018
                                            Miss Sharon Jones                                             Miss Sharon Jones!                2016                                             miss sharon jones_2016
Drunk Stoned Brilliant Dead The Story of the National Lampoon Drunk Stoned Brilliant Dead: The Story of the National Lampoon                2015 drunk stoned brilliant dead the story of the national lampoon_2015
                                                          211                                                            211                2018                                                           211_2018
        Raiders! The Story of the Greatest Fan Film Ever Made         Raiders!: The Story of the Greatest Fan Film Ever Made                2016          raiders the story of the greatest fan film ever made_2016
                                       People, Places, Things                                           People Places Things                2015                                          people places things_2015
                              Jia Zhangke: A Guy From Fenyang                                Jia Zhangke, A guy from Fenyang                2016                                jia zhangke a guy from fenyang_2016
                                   What Happened, Miss Simone                                    What Happened, Miss Simone?                2015                                     what happened miss simone_2015
                                          Terminator: Genisys                                             Terminator Genisys                2015                                            terminator genisys_2015
                                Guardians of the Galaxy Vol 2                                 Guardians of the Galaxy Vol. 2                2017                                 guardians of the galaxy vol 2_2017
                                          Insidious Chapter 3                                           Insidious: Chapter 3                2015                                           insidious chapter 3_2015
                     The Twilight Saga: Breaking Dawn, Part 2                      The Twilight Saga: Breaking Dawn - Part 2                2012                        the twilight saga breaking dawn part 2_2012
                                                         Spy!                                                            Spy                2015                                                           spy_2015
                                                Sunlight, Jr.                                                   Sunlight Jr.                2013                                                   sunlight jr_2013
                                Dark Star: H.R. Giger's World                                    Dark Star: HR Giger's World                2015                                     dark star hr gigers world_2015
                                         Everybody Wants Some                                         Everybody Wants Some!!                2016                                          everybody wants some_2016
                                               Big Ass Spider                                                Big Ass Spider!                2013                                                big ass spider_2013
                                        Camille Claudel: 1915                                           Camille Claudel 1915                2013                                          camille claudel 1915_2013
                     The Twilight Saga: Breaking Dawn, Part 1                      The Twilight Saga: Breaking Dawn - Part 1                2011                        the twilight saga breaking dawn part 1_2011
                                                     Bad Milo                                                      Bad Milo!                2013                                                      bad milo_2013
                                                           13                                                             13                2011                                                            13_2011
                                  Metallica Through the Never                                   Metallica: Through the Never                2013                                   metallica through the never_2013
                                        For a Good Time, Call                                       For a Good Time, Call...                2012                                          for a good time call_2012
                                          Insidious Chapter 2                                           Insidious: Chapter 2                2013                                           insidious chapter 2_2013
                                       Tucker & Dale vs. Evil                                          Tucker & Dale vs Evil                2011                                           tucker dale vs evil_2011
              99% - The Occupy Wall Street Collaborative Film                 99%: The Occupy Wall Street Collaborative Film                2013                  99 the occupy wall street collaborative film_2013
                                               Step Up All In                                                Step Up: All In                2014                                                step up all in_2014
                                                            3                                                              3                2011                                                             3_2011
                           The Black Power Mixtape: 1967-1975                              The Black Power Mixtape 1967-1975                2011                              the black power mixtape 19671975_2011
                                             How Do You Know?                                                How Do You Know                2010                                               how do you know_2010
                                   I Love You, Phillip Morris                                      I Love You Phillip Morris                2010                                     i love you phillip morris_2010
                                             The Way Way Back                                              The Way, Way Back                2013                                              the way way back_2013
                              3D Sex and Zen: Extreme Ecstasy                               3-D Sex and Zen: Extreme Ecstasy                2011                                3d sex and zen extreme ecstasy_2011
                                                         2012                                                           2012                2009                                                          2012_2009
                                                   Jackass 3D                                                    Jackass 3-D                2010                                                    jackass 3d_2010
                                                     Tabloid!                                                        Tabloid                2011                                                       tabloid_2011
 GhettoPhysics: Will the Real Pimps and Ho's Please Stand Up?    GhettoPhysics: Will the Real Pimps and Hos Please Stand Up?                2010     ghettophysics will the real pimps and hos please stand up_2010
    Beats, Rhymes & Life: The Travels of a Tribe Called Quest       Beats Rhymes & Life: The Travels of a Tribe Called Quest                2011         beats rhymes life the travels of a tribe called quest_2011
                                         Waiting for Superman                                         Waiting for 'Superman'                2010                                          waiting for superman_2010
                                Jimmy Carter: Man From Plains                                   Jimmy Carter Man from Plains                2007                                  jimmy carter man from plains_2007
                                            T2: Trainspotting                                               T2 Trainspotting                2017                                              t2 trainspotting_2017
                                                Generation Um                                               Generation Um...                2013                                                 generation um_2013
                                               McFarland, USA                                                  McFarland USA                2015                                                 mcfarland usa_2015
                                                            9                                                              9                2009                                                             9_2009
                                                   Piranha 3D                                                    Piranha 3-D                2010                                                    piranha 3d_2010
                                                   Step Up 3D                                                    Step Up 3-D                2010                                                    step up 3d_2010
                          Tenacious D in: The Pick of Destiny                             Tenacious D in The Pick of Destiny                2006                            tenacious d in the pick of destiny_2006
                                                          360                                                            360                2012                                                           360_2012
                                      !Women, Art, Revolution                                          !Women Art Revolution                2011                                          women art revolution_2011
                             Who the #$^% is Jackson Pollock?                               Who the #$&% Is Jackson Pollock?                2006                                    who the is jackson pollock_2006
                                     Kurt Cobain: About a Son                                        Kurt Cobain About a Son                2007                                       kurt cobain about a son_2007
                                                 Rumor Has It                                                Rumor Has It...                2005                                                  rumor has it_2005
               HEY, BOO: Harper Lee and To Kill a Mockingbird               Hey, Boo: Harper Lee and 'To Kill a Mockingbird'                2011                  hey boo harper lee and to kill a mockingbird_2011
                                                           42                                                             42                2013                                                            42_2013
                                      Mrs. Henderson Presents                                         Mrs Henderson Presents                2005                                        mrs henderson presents_2005
         Forget Baghdad: Jews and Arabs, The Iraqi Connection          Forget Baghdad: Jews and Arabs - The Iraqi Connection                2003            forget baghdad jews and arabs the iraqi connection_2003
                                Mrs. Palfrey at the Claremont                                   Mrs Palfrey at The Claremont                2005                                  mrs palfrey at the claremont_2005
                                           Tupac Resurrection                                            Tupac: Resurrection                2003                                            tupac resurrection_2003
                                    Bigger, Stronger, Faster*                                        Bigger Stronger Faster*                2008                                        bigger stronger faster_2008
                                Hoodwinked Too: Hood vs. Evil                                  Hoodwinked Too! Hood VS. Evil                2011                                   hoodwinked too hood vs evil_2011
                                                  Lebanon, PA                                                   Lebanon, Pa.                2011                                                    lebanon pa_2011
             Jonestown: The Life and Death of People's Temple                Jonestown: The Life and Death of Peoples Temple                2006                jonestown the life and death of peoples temple_2006
                                      Jeff, Who Lives at Home                                         Jeff Who Lives at Home                2012                                        jeff who lives at home_2012
                                                Whisky Galore                                                 Whisky Galore!                2017                                                 whisky galore_2017
                                          Gay Sex in the 70's                                             Gay Sex in the 70s                2005                                            gay sex in the 70s_2005
                                               Die Mommie Die                                              Die, Mommie, Die!                2003                                                die mommie die_2003
                                     What Happens in Vegas...                                          What Happens in Vegas                2008                                         what happens in vegas_2008
                                           So Goes the Nation                                          ...So Goes the Nation                2006                                            so goes the nation_2006
                                     Gerhard Richter Painting                                     Gerhard Richter - Painting                2012                                      gerhard richter painting_2012
                                                         9.99                                                          $9.99                2009                                                           999_2009
                          Youssou N'Dour: I Bring What I Love                             Youssou Ndour: I Bring What I Love                2009                             youssou ndour i bring what i love_2009
                                   War of the World's Goliath                                     War of the Worlds: Goliath                2014                                     war of the worlds goliath_2014
                                          Jackass: Number Two                                             Jackass Number Two                2006                                            jackass number two_2006
                                         Kiss Kiss, Bang Bang                                            Kiss Kiss Bang Bang                2005                                           kiss kiss bang bang_2005
                                              Shall We Dance?                                                 Shall We Dance                2004                                                shall we dance_2004
                                             Zombie Strippers                                              Zombie Strippers!                2008                                              zombie strippers_2008
                                      The U.S. vs John Lennon                                       The U.S. vs. John Lennon                2006                                         the us vs john lennon_2006
                                    Good Night, and Good Luck                                     Good Night, and Good Luck.                2005                                      good night and good luck_2005
                                                          Dig                                                           Dig!                2004                                                           dig_2004
                                 Tibet - Cry of the Snow Lion                                    Tibet: Cry of the Snow Lion                2003                                    tibet cry of the snow lion_2003
                                                     Mr. 3000                                                        Mr 3000                2004                                                       mr 3000_2004
                                                   Adaptation                                                    Adaptation.                2002                                                    adaptation_2002

In [57]:
# Compare runtime values between File 1 and File 2
runtime_match = (
    merged_df["runtime_file1"].fillna(-1)
    == merged_df["runtime_file2"].fillna(-1)
)

# Compare genre values between File 1 and File 2
genre_match = (
    merged_df["genre_file1"].fillna("").str.strip().str.lower()
    == merged_df["genre_file2"].fillna("").str.strip().str.lower()
)

# Print the comparison results
print("Runtime matches:", runtime_match.sum())
print("Runtime differences:", (~runtime_match).sum())

print("Genre matches:", genre_match.sum())
print("Genre differences:", (~genre_match).sum())

Runtime matches: 3831
Runtime differences: 4298
Genre matches: 1901
Genre differences: 6228

In [58]:
# Display examples where runtime values differ
runtime_differences = merged_df[
    ~runtime_match
][[
    "title_file1",
    "runtime_file1",
    "runtime_file2",
    "release_year_file1",
    "movie_key"
]]

# Show the first 50 runtime differences
print(runtime_differences.head(50).to_string(index=False))

                     title_file1  runtime_file1  runtime_file2  release_year_file1                            movie_key
                       Antitrust            NaN          109.0                2001                       antitrust_2001
              A Walk to Remember            NaN          101.0                2002              a walk to remember_2002
      The Killing of John Lennon            NaN          114.0                2008      the killing of john lennon_2008
                    Angels Crest           96.0           92.0                2011                    angels crest_2011
                     Miss Minoes            NaN           86.0                2011                     miss minoes_2011
  In The Land of Blood and Honey            NaN          127.0                2011  in the land of blood and honey_2011
                We Are the Giant           90.0           92.0                2014                we are the giant_2014
                            Meru           89.0           87.0                2015                            meru_2015
                Welcome to Leith           86.0           85.0                2015                welcome to leith_2015
                     Point Break          113.0          114.0                2015                     point break_2015
                       Destroyer          123.0          121.0                2018                       destroyer_2018
                        The Post          115.0          116.0                2017                        the post_2017
                        Hostiles          127.0          134.0                2017                        hostiles_2017
                        Bird Box          117.0          124.0                2018                        bird box_2018
                         Vox Lux          112.0          114.0                2018                         vox lux_2018
                      Second Act          104.0          103.0                2018                      second act_2018
             Mary Queen of Scots          125.0          124.0                2018             mary queen of scots_2018
            Just Getting Started           90.0           91.0                2017            just getting started_2017
                       Ferdinand          107.0          108.0                2017                       ferdinand_2017
                 Ghostbox Cowboy          110.0           90.0                2018                 ghostbox cowboy_2018
                     Psychopaths           81.0           85.0                2017                     psychopaths_2017
                  Kill Me Please           98.0          101.0                2017                  kill me please_2017
  The Possession of Hannah Grace           85.0           86.0                2018  the possession of hannah grace_2018
             The Disaster Artist           98.0          104.0                2017             the disaster artist_2017
             On the Basis of Sex          118.0          120.0                2018             on the basis of sex_2018
                  Hidden Figures          126.0          127.0                2016                  hidden figures_2016
       Ralph Breaks The Internet          112.0          111.0                2018       ralph breaks the internet_2018
              20th Century Women          118.0          119.0                2016              20th century women_2016
                        Creed II          128.0          130.0                2018                        creed ii_2018
Bombshell: The Hedy Lamarr Story           89.0           88.0                2017 bombshell the hedy lamarr story_2017
                  Instant Family          119.0          118.0                2018                  instant family_2018
                  Sweet Virginia           95.0           93.0                2017                  sweet virginia_2017
           Roman J. Israel, Esq.          129.0          122.0                2017              roman j israel esq_2017
         The Autopsy of Jane Doe           87.0           86.0                2016         the autopsy of jane doe_2016
                    Patriots Day          130.0          133.0                2016                    patriots day_2016
           The Clovehitch Killer          110.0          109.0                2018           the clovehitch killer_2018
                          Fences          133.0          139.0                2016                          fences_2016
                 The Breadwinner           93.0           94.0                2017                 the breadwinner_2017
               Collateral Beauty           96.0           97.0                2016               collateral beauty_2016
    Rogue One: A Star Wars Story          134.0          133.0                2016     rogue one a star wars story_2016
                     Outlaw King          117.0          121.0                2018                     outlaw king_2018
                  Justice League          121.0          120.0                2017                  justice league_2017
                        Jonathan          100.0           95.0                2018                        jonathan_2018
       Harry Benson: Shoot First           89.0           87.0                2016        harry benson shoot first_2016
                      All We Had           86.0          105.0                2016                      all we had_2016
                      Chef Flynn           83.0           82.0                2018                      chef flynn_2018
                        Overlord          109.0          110.0                2018                        overlord_2018
                        Prospect           99.0           98.0                2018                        prospect_2018
                   A Private War          106.0          110.0                2018                   a private war_2018
             Wait For Your Laugh           86.0           85.0                2017             wait for your laugh_2017

In [59]:
# Display examples where genre values differ
genre_differences = merged_df[
    ~genre_match
][[
    "title_file1",
    "genre_file1",
    "genre_file2",
    "release_year_file1",
    "movie_key"
]]

# Show the first 50 genre differences
print(genre_differences.head(50).to_string(index=False))

                   title_file1       genre_file1                                             genre_file2  release_year_file1                           movie_key
                     Antitrust Thriller/Suspense                                          Drama,Thriller                2001                      antitrust_2001
                      Santitos               NaN                                            Drama,Comedy                2000                       santitos_2000
            A Walk to Remember             Drama                                           Drama,Romance                2002             a walk to remember_2002
    The Killing of John Lennon             Drama                                             Drama,Crime                2008     the killing of john lennon_2008
                     Mad Money            Comedy                           Thriller,Comedy,Romance,Crime                2008                      mad money_2008
            Over Her Dead Body            Comedy                                  Fantasy,Comedy,Romance                2008             over her dead body_2008
         The Other Boleyn Girl             Drama                         Biography,Drama,History,Romance                2008          the other boleyn girl_2008
                     War Horse             Drama                                                     War                2011                      war horse_2011
              The Darkest Hour            Action                           Action,Sci-Fi,Thriller,Horror                2011               the darkest hour_2011
                   Miss Minoes         Adventure                                   Fantasy,Comedy,Family                2011                    miss minoes_2011
               We Bought a Zoo             Drama                                            Drama,Comedy                2011                we bought a zoo_2011
In The Land of Blood and Honey             Drama                                             Romance,War                2011 in the land of blood and honey_2011
                          Meru       Documentary                      Action,Adventure,Sport,Documentary                2015                           meru_2015
              Welcome to Leith       Documentary                                    Thriller,Documentary                2015               welcome to leith_2015
                         Truth Thriller/Suspense                                         Biography,Drama                2015                          truth_2015
                   Point Break            Action                             Action,Sport,Thriller,Crime                2015                    point break_2015
                  The Revenant         Adventure                        Adventure,Drama,Thriller,Western                2015                   the revenant_2015
                  Stan & Ollie             Drama                                  Biography,Drama,Comedy                2018                     stan ollie_2018
                         Benji         Adventure                                      Drama,Crime,Family                2018                          benji_2018
                     Destroyer Thriller/Suspense                     Action,Drama,Mystery,Thriller,Crime                2018                      destroyer_2018
             Welcome to Marwen             Drama                Biography,Drama,Fantasy,Comedy,Animation                2018              welcome to marwen_2018
                          Vice      Black Comedy                          Biography,Drama,History,Comedy                2018                           vice_2018
               Holmes & Watson            Comedy                          Adventure,Mystery,Comedy,Crime                2018                  holmes watson_2018
          Mary Poppins Returns           Musical Adventure,Drama,Fantasy,Comedy,Animation,Family,Musical                2018           mary poppins returns_2018
                Phantom Thread             Drama                                     Drama,Romance,Crime                2017                 phantom thread_2017
    All the Money in the World Thriller/Suspense          Biography,Drama,History,Mystery,Thriller,Crime                2017     all the money in the world_2017
                      The Mule             Drama                            Drama,Mystery,Thriller,Crime                2018                       the mule_2018
    If Beale Street Could Talk             Drama                                     Drama,Romance,Crime                2018     if beale street could talk_2018
                      The Post             Drama                        Biography,Drama,History,Thriller                2017                       the post_2017
                      Hostiles           Western                                 Adventure,Drama,Western                2017                       hostiles_2017
                       Hangman Thriller/Suspense                                  Mystery,Thriller,Crime                2017                        hangman_2017
                     Bumblebee         Adventure                                 Action,Adventure,Sci-Fi                2018                      bumblebee_2018
                      Bird Box Thriller/Suspense                            Sci-Fi,Drama,Thriller,Horror                2018                       bird box_2018
                    Downsizing            Comedy                                     Sci-Fi,Drama,Comedy                2017                     downsizing_2017
               Pitch Perfect 3            Comedy                                            Comedy,Music                2017                pitch perfect 3_2017
Jumanji: Welcome to the Jungle         Adventure                  Action,Adventure,Fantasy,Comedy,Family                2017  jumanji welcome to the jungle_2017
                       Vox Lux           Musical                                     Drama,Music,Musical                2018                        vox lux_2018
                    Second Act            Comedy                                    Drama,Comedy,Romance                2018                     second act_2018
           Mary Queen of Scots             Drama                                 Biography,Drama,History                2018            mary queen of scots_2018
                        Bright Thriller/Suspense                    Action,Sci-Fi,Thriller,Fantasy,Crime                2017                         bright_2017
          The Greatest Showman           Musical                         Biography,Drama,Romance,Musical                2017           the greatest showman_2017
                    Back Roads Thriller/Suspense                                          Drama,Thriller                2018                     back roads_2018
        The Pirates Of Somalia             Drama                                         Biography,Drama                2017         the pirates of somalia_2017
          Just Getting Started            Comedy                                           Action,Comedy                2017           just getting started_2017
                       Aquaman            Action                         Action,Adventure,Sci-Fi,Fantasy                2018                        aquaman_2018
                         Tyrel             Drama                                            Drama,Comedy                2018                          tyrel_2018
                Mortal Engines            Action                Action,Adventure,Sci-Fi,Thriller,Fantasy                2018                 mortal engines_2018
                      I, Tonya      Black Comedy                            Biography,Drama,Sport,Comedy                2017                        i tonya_2017
                     Ferdinand         Adventure               Adventure,Fantasy,Comedy,Animation,Family                2017                      ferdinand_2017
                   Bullet Head Thriller/Suspense                                    Drama,Thriller,Crime                2017                    bullet head_2017

In [60]:
# Compare URL values between File 1 and File 2
url_match = (
    merged_df["url_file1"].fillna("").str.strip()
    == merged_df["url_file2"].fillna("").str.strip()
)

# Print the comparison results
print("URL matches:", url_match.sum())
print("URL differences:", (~url_match).sum())

# Display examples where URLs differ
url_differences = merged_df[
    ~url_match
][[
    "title_file1",
    "url_file1",
    "url_file2",
    "release_year_file1",
    "movie_key"
]]

print(url_differences.head(20).to_string(index=False))

URL matches: 0
URL differences: 8129
                        title_file1                                                             url_file1                                                            url_file2  release_year_file1                                movie_key
                          Antitrust                           https://www.the-numbers.com/movie/Antitrust                           https://www.metacritic.com/movie/antitrust                2001                           antitrust_2001
                           Santitos                            https://www.the-numbers.com/movie/Santitos                            https://www.metacritic.com/movie/santitos                2000                            santitos_2000
                 A Walk to Remember                  https://www.the-numbers.com/movie/Walk-to-Remember-A                  https://www.metacritic.com/movie/a-walk-to-remember                2002                  a walk to remember_2002
         The Killing of John Lennon          https://www.the-numbers.com/movie/Killing-of-John-Lennon-The          https://www.metacritic.com/movie/the-killing-of-john-lennon                2008          the killing of john lennon_2008
                          Mad Money                           https://www.the-numbers.com/movie/Mad-Money                           https://www.metacritic.com/movie/mad-money                2008                           mad money_2008
                 Over Her Dead Body                  https://www.the-numbers.com/movie/Over-Her-Dead-Body                  https://www.metacritic.com/movie/over-her-dead-body                2008                  over her dead body_2008
              The Other Boleyn Girl               https://www.the-numbers.com/movie/Other-Boleyn-Girl-The               https://www.metacritic.com/movie/the-other-boleyn-girl                2008               the other boleyn girl_2008
                             Pariah                       https://www.the-numbers.com/movie/Pariah-(2011)                              https://www.metacritic.com/movie/pariah                2011                              pariah_2011
                          War Horse                           https://www.the-numbers.com/movie/War-Horse                           https://www.metacritic.com/movie/war-horse                2011                           war horse_2011
Extremely Loud and Incredibly Close https://www.the-numbers.com/movie/Extremely-Loud-and-Incredibly-Close https://www.metacritic.com/movie/extremely-loud-and-incredibly-close                2011 extremely loud and incredibly close_2011
                       Angels Crest                        https://www.the-numbers.com/movie/Angels-Crest                        https://www.metacritic.com/movie/angels-crest                2011                        angels crest_2011
                   The Darkest Hour                    https://www.the-numbers.com/movie/Darkest-Hour-The                    https://www.metacritic.com/movie/the-darkest-hour                2011                    the darkest hour_2011
                        Miss Minoes                         https://www.the-numbers.com/movie/Miss-Minoes                         https://www.metacritic.com/movie/miss-minoes                2011                         miss minoes_2011
                    We Bought a Zoo                     https://www.the-numbers.com/movie/We-Bought-a-Zoo                     https://www.metacritic.com/movie/we-bought-a-zoo                2011                     we bought a zoo_2011
     In The Land of Blood and Honey      https://www.the-numbers.com/movie/In-The-Land-of-Blood-and-Honey      https://www.metacritic.com/movie/in-the-land-of-blood-and-honey                2011      in the land of blood and honey_2011
                   We Are the Giant                    https://www.the-numbers.com/movie/We-Are-the-Giant                    https://www.metacritic.com/movie/we-are-the-giant                2014                    we are the giant_2014
                               Meru                                https://www.the-numbers.com/movie/Meru                                https://www.metacritic.com/movie/meru                2015                                meru_2015
                   Welcome to Leith                    https://www.the-numbers.com/movie/Welcome-to-Leith                    https://www.metacritic.com/movie/welcome-to-leith                2015                    welcome to leith_2015
                              Truth                        https://www.the-numbers.com/movie/Truth-(2015)                          https://www.metacritic.com/movie/truth-2015                2015                               truth_2015
                        Point Break                https://www.the-numbers.com/movie/Point-Break-(Remake)                    https://www.metacritic.com/movie/point-break-2015                2015                         point break_2015

In [61]:
# Display the columns of the merged dataset with their positions
for i, column in enumerate(merged_df.columns, start=1):
    print(i, column)

1 release_year_file1
2 release_date_file1
3 title_file1
4 genre_file1
5 international_box_office
6 domestic_box_office
7 worldwide_box_office
8 production_budget
9 opening_weekend
10 theatre_count
11 avg run per theatre
12 runtime_file1
13 keywords
14 creative_type
15 url_file1
16 title_clean_file1
17 movie_key
18 url_file2
19 title_file2
20 studio
21 rating
22 runtime_file2
23 cast
24 director
25 genre_file2
26 summary
27 awards
28 metascore
29 userscore
30 release_date_file2
31 title_clean_file2
32 release_year_file2

In [62]:
# Compare release date values between File 1 and File 2
date_match = (
    merged_df["release_date_file1"].fillna(pd.Timestamp("1900-01-01"))
    == merged_df["release_date_file2"].fillna(pd.Timestamp("1900-01-01"))
)

# Print the comparison results
print("Release date matches:", date_match.sum())
print("Release date differences:", (~date_match).sum())

# Display examples where release dates differ
date_differences = merged_df[
    ~date_match
][[
    "title_file1",
    "release_date_file1",
    "release_date_file2",
    "release_year_file1",
    "movie_key"
]]

print(date_differences.head(30).to_string(index=False))

Release date matches: 0
Release date differences: 8129
                        title_file1 release_date_file1 release_date_file2  release_year_file1                                movie_key
                          Antitrust                NaT         2001-01-12                2001                           antitrust_2001
                           Santitos                NaT         2000-01-28                2000                            santitos_2000
                 A Walk to Remember                NaT         2002-01-25                2002                  a walk to remember_2002
         The Killing of John Lennon                NaT         2008-01-02                2008          the killing of john lennon_2008
                          Mad Money                NaT         2008-01-18                2008                           mad money_2008
                 Over Her Dead Body                NaT         2008-02-01                2008                  over her dead body_2008
              The Other Boleyn Girl                NaT         2008-02-29                2008               the other boleyn girl_2008
                             Pariah                NaT         2011-12-28                2011                              pariah_2011
                          War Horse                NaT         2011-12-25                2011                           war horse_2011
Extremely Loud and Incredibly Close                NaT         2011-12-25                2011 extremely loud and incredibly close_2011
                       Angels Crest                NaT         2011-12-30                2011                        angels crest_2011
                   The Darkest Hour                NaT         2011-12-25                2011                    the darkest hour_2011
                        Miss Minoes                NaT         2011-12-23                2011                         miss minoes_2011
                    We Bought a Zoo                NaT         2011-12-23                2011                     we bought a zoo_2011
     In The Land of Blood and Honey                NaT         2011-12-23                2011      in the land of blood and honey_2011
                   We Are the Giant                NaT         2014-12-12                2014                    we are the giant_2014
                               Meru                NaT         2015-08-14                2015                                meru_2015
                   Welcome to Leith                NaT         2015-09-09                2015                    welcome to leith_2015
                              Truth                NaT         2015-10-16                2015                               truth_2015
                        Point Break                NaT         2015-12-25                2015                         point break_2015
                       The Revenant                NaT         2015-12-25                2015                        the revenant_2015
                       Stan & Ollie                NaT         2018-12-28                2018                          stan ollie_2018
                              Benji                NaT         2018-03-16                2018                               benji_2018
                          Destroyer                NaT         2018-12-25                2018                           destroyer_2018
                  Welcome to Marwen                NaT         2018-12-21                2018                   welcome to marwen_2018
                               Vice                NaT         2018-12-25                2018                                vice_2018
                    Holmes & Watson                NaT         2018-12-25                2018                       holmes watson_2018
               Mary Poppins Returns                NaT         2018-12-19                2018                mary poppins returns_2018
                     Phantom Thread                NaT         2017-12-25                2017                      phantom thread_2017
         All the Money in the World                NaT         2017-12-25                2017          all the money in the world_2017

In [63]:
# Remove temporary matching columns
merged_clean = merged_df.drop(columns=[
    "title_clean_file1",
    "title_clean_file2",
    "release_year_file2"
])

# Display the new dataset shape
print("Clean merged dataset shape:", merged_clean.shape)

# Display the remaining columns
for i, column in enumerate(merged_clean.columns, start=1):
    print(i, column)

Clean merged dataset shape: (8129, 29)
1 release_year_file1
2 release_date_file1
3 title_file1
4 genre_file1
5 international_box_office
6 domestic_box_office
7 worldwide_box_office
8 production_budget
9 opening_weekend
10 theatre_count
11 avg run per theatre
12 runtime_file1
13 keywords
14 creative_type
15 url_file1
16 movie_key
17 url_file2
18 title_file2
19 studio
20 rating
21 runtime_file2
22 cast
23 director
24 genre_file2
25 summary
26 awards
27 metascore
28 userscore
29 release_date_file2

In [64]:
# Rename columns to make the final dataset easier to understand
merged_clean = merged_clean.rename(columns={
    "release_year_file1": "release_year",
    "release_date_file1": "release_date_file1",
    "title_file1": "title_file1",
    "genre_file1": "genre_file1",
    "runtime_file1": "runtime_file1",
    "url_file1": "url_file1",
    "url_file2": "url_file2",
    "title_file2": "title_file2",
    "runtime_file2": "runtime_file2",
    "genre_file2": "genre_file2",
    "release_date_file2": "release_date_file2"
})

# Display the column names
for i, column in enumerate(merged_clean.columns, start=1):
    print(i, column)

1 release_year
2 release_date_file1
3 title_file1
4 genre_file1
5 international_box_office
6 domestic_box_office
7 worldwide_box_office
8 production_budget
9 opening_weekend
10 theatre_count
11 avg run per theatre
12 runtime_file1
13 keywords
14 creative_type
15 url_file1
16 movie_key
17 url_file2
18 title_file2
19 studio
20 rating
21 runtime_file2
22 cast
23 director
24 genre_file2
25 summary
26 awards
27 metascore
28 userscore
29 release_date_file2

In [65]:
# Check the number of rows
print("Number of rows:", len(merged_clean))

# Check for duplicate movie keys
print("Duplicate movie_keys:", merged_clean["movie_key"].duplicated().sum())

# Check for duplicate rows
print("Duplicate rows:", merged_clean.duplicated().sum())

Number of rows: 8129
Duplicate movie_keys: 0
Duplicate rows: 0

In [66]:
# Display the data types of all columns
print(merged_clean.dtypes)

release_year                         int64
release_date_file1          datetime64[ns]
title_file1                         object
genre_file1                         object
international_box_office           float64
domestic_box_office                float64
worldwide_box_office               float64
production_budget                  float64
opening_weekend                    float64
theatre_count                      float64
avg run per theatre                float64
runtime_file1                      float64
keywords                            object
creative_type                       object
url_file1                           object
movie_key                           object
url_file2                           object
title_file2                         object
studio                              object
rating                              object
runtime_file2                      float64
cast                                object
director                            object
genre_file2                         object
summary                             object
awards                              object
metascore                            int64
userscore                          float64
release_date_file2          datetime64[ns]
dtype: object

In [67]:
# Save the cleaned and merged dataset as a CSV file
merged_clean.to_csv("merged_movies_clean.csv", index=False)

# Confirm that the file was saved
print("File saved successfully.")

File saved successfully.

In [68]:
# Create copies of the original datasets
df1_all = df1.copy()
df2_all = df2.copy()

# Display the number of movies in each file
print("File 1 movies:", len(df1_all))
print("File 2 movies:", len(df2_all))

File 1 movies: 30612
File 2 movies: 11364

In [69]:
# Keep uniquely matched movies from File 2
df2_unique = df2_all[
    df2_all["movie_key"].isin(unique_match_keys)
].copy()

# Merge all File 1 movies with uniquely matched File 2 movies
merged_all = pd.merge(
    df1_all,
    df2_unique,
    on="movie_key",
    how="outer",
    suffixes=("_file1", "_file2"),
    indicator=True
)

# Check the merged dataset
print("Merged dataset shape:", merged_all.shape)
print("Total rows:", len(merged_all))
print("\nMerge status:")
print(merged_all["_merge"].value_counts())

Merged dataset shape: (30612, 33)
Total rows: 30612

Merge status:
_merge
left_only     22483
both           8129
right_only        0
Name: count, dtype: int64

In [70]:
df2_unique = df2_all[
    df2_all["movie_key"].isin(unique_match_keys)
]

In [71]:
# Find movies in File 2 whose movie_key does not exist in File 1
df2_only = df2_all[
    ~df2_all["movie_key"].isin(df1_all["movie_key"])
].copy()

# Count movies that exist only in File 2
print("Movies only in File 2:", len(df2_only))

# Display a few examples
print(df2_only[["title", "release_year", "movie_key"]].head(20).to_string(index=False))

Movies only in File 2: 3219
                  title  release_year                   movie_key
       10 Items or Less          2006       10 items or less_2006
            100 Streets          2017            100 streets_2017
 1,000 Times Good Night          2014  1000 times good night_2014
             ReykjavÃ­k          2001              reykjavãk_2001
             11 Flowers          2013             11 flowers_2013
             11 Minutes          2016             11 minutes_2016
                11/8/16          2017                  11816_2017
               12-12-12          2013                 121212_2013
        12 O'Clock Boys          2014         12 oclock boys_2014
12:08 East of Bucharest          2007 1208 east of bucharest_2007
           13 Assassins          2011           13 assassins_2011
             13 Minutes          2017             13 minutes_2017
              14 Blades          2014              14 blades_2014
    16 Years of Alcohol          2005    16 years of alcohol_2005
              17 Blocks          2019              17 blocks_2019
               17 Girls          2012               17 girls_2012
                   1911          2011                   1911_2011
                   1922          2017                   1922_2017
                   1971          2015                   1971_2015
                    1BR          2020                    1br_2020

In [72]:
# Select movies that exist only in File 2
df2_only = df2_all[
    ~df2_all["movie_key"].isin(df1_all["movie_key"])
].copy()

# Add File 2-only movies to the merged dataset
merged_all = pd.concat(
    [merged_all.drop(columns=["_merge"]), df2_only],
    ignore_index=True,
    sort=False
)

# Check the new dataset size
print("Final rows:", len(merged_all))
print("Final columns:", len(merged_all.columns))

Final rows: 33831
Final columns: 39

In [73]:
# Display all columns in the merged dataset
for i, column in enumerate(merged_all.columns, start=1):
    print(i, column)

1 release_year_file1
2 release_date_file1
3 title_file1
4 genre_file1
5 international_box_office
6 domestic_box_office
7 worldwide_box_office
8 production_budget
9 opening_weekend
10 theatre_count
11 avg run per theatre
12 runtime_file1
13 keywords
14 creative_type
15 url_file1
16 title_clean_file1
17 movie_key
18 url_file2
19 title_file2
20 studio
21 rating
22 runtime_file2
23 cast
24 director
25 genre_file2
26 summary
27 awards
28 metascore
29 userscore
30 release_date_file2
31 title_clean_file2
32 release_year_file2
33 url
34 title
35 runtime
36 genre
37 release_date
38 title_clean
39 release_year

In [74]:
# Check how many rows currently exist for the ambiguous movie keys
ambiguous_check = merged_all[
    merged_all["movie_key"].isin(ambiguous_matches)
]

# Display the ambiguous movies
print(
    ambiguous_check[
        ["movie_key", "title_file1", "title_file2", "title", "release_year_file1", "release_year"]
    ].to_string(index=False)
)

             movie_key       title_file1 title_file2 title  release_year_file1  release_year
        aftermath_2014         Aftermath         NaN   NaN              2014.0           NaN
        aftermath_2014         Aftermath         NaN   NaN              2014.0           NaN
        dreamland_2020         Dreamland         NaN   NaN              2020.0           NaN
        dreamland_2020         Dreamland         NaN   NaN              2020.0           NaN
        dreamland_2020         Dreamland         NaN   NaN              2020.0           NaN
            greta_2019             Greta         NaN   NaN              2019.0           NaN
            greta_2019             Greta         NaN   NaN              2019.0           NaN
             luca_2021              Luca         NaN   NaN              2021.0           NaN
             luca_2021              Luca         NaN   NaN              2021.0           NaN
              run_2020               Run         NaN   NaN              2020.0           NaN
              run_2020               Run         NaN   NaN              2020.0           NaN
        swan song_2021         Swan Song         NaN   NaN              2021.0           NaN
        swan song_2021         Swan Song         NaN   NaN              2021.0           NaN
       the hunter_2012        The Hunter         NaN   NaN              2012.0           NaN
  the interpreter_2005   The Interpreter         NaN   NaN              2005.0           NaN
  the interpreter_2005   The Interpreter         NaN   NaN              2005.0           NaN
     the outsider_2018      The Outsider         NaN   NaN              2018.0           NaN
     the outsider_2018      The Outsider         NaN   NaN              2018.0           NaN
           thirst_2009            Thirst         NaN   NaN              2009.0           NaN
           thirst_2009            Thirst         NaN   NaN              2009.0           NaN
              val_2021               Val         NaN   NaN              2021.0           NaN
              val_2021               Val         NaN   NaN              2021.0           NaN
      white noise_2005       White Noise         NaN   NaN              2005.0           NaN
      white noise_2005       White Noise         NaN   NaN              2005.0           NaN
wuthering heights_2012 Wuthering Heights         NaN   NaN              2012.0           NaN
wuthering heights_2012 Wuthering Heights         NaN   NaN              2012.0           NaN

In [75]:
# Find all File 2 rows with ambiguous movie keys
df2_ambiguous = df2_all[
    df2_all["movie_key"].isin(ambiguous_matches)
].copy()

# Count ambiguous rows in File 2
print("Ambiguous rows in File 2:", len(df2_ambiguous))

# Display the ambiguous File 2 records
print(
    df2_ambiguous[
        ["movie_key", "title", "release_year", "url"]
    ].to_string(index=False)
)

Ambiguous rows in File 2: 16
             movie_key             title  release_year                                                url
        aftermath_2014         Aftermath          2014    https://www.metacritic.com/movie/aftermath-2014
        dreamland_2020         Dreamland          2020    https://www.metacritic.com/movie/dreamland-2019
        dreamland_2020         Dreamland          2020    https://www.metacritic.com/movie/dreamland-2020
            greta_2019             Greta          2019             https://www.metacritic.com/movie/greta
             luca_2021              Luca          2021              https://www.metacritic.com/movie/luca
              run_2020               Run          2020               https://www.metacritic.com/movie/run
        swan song_2021         Swan Song          2021         https://www.metacritic.com/movie/swan-song
        swan song_2021         Swan Song          2021    https://www.metacritic.com/movie/swan-song-2021
       the hunter_2012        The Hunter          2012        https://www.metacritic.com/movie/the-hunter
       the hunter_2012        The Hunter          2012   https://www.metacritic.com/movie/the-hunter-2012
  the interpreter_2005   The Interpreter          2005   https://www.metacritic.com/movie/the-interpreter
     the outsider_2018      The Outsider          2018 https://www.metacritic.com/movie/the-outsider-2018
           thirst_2009            Thirst          2009            https://www.metacritic.com/movie/thirst
              val_2021               Val          2021               https://www.metacritic.com/movie/val
      white noise_2005       White Noise          2005       https://www.metacritic.com/movie/white-noise
wuthering heights_2012 Wuthering Heights          2012 https://www.metacritic.com/movie/wuthering-heights

In [76]:
# Select all ambiguous records from File 2
df2_ambiguous = df2_all[
    df2_all["movie_key"].isin(ambiguous_matches)
].copy()

# Remove the merge indicator from the current dataset
merged_all = merged_all.drop(columns=["_merge"], errors="ignore")

# Add the ambiguous File 2 records
merged_all = pd.concat(
    [merged_all, df2_ambiguous],
    ignore_index=True,
    sort=False
)

# Check the total number of rows
print("Total rows:", len(merged_all))

Total rows: 33847

In [77]:
# Display the current columns and their data types
for i, column in enumerate(merged_all.columns, start=1):
    print(i, column)

1 release_year_file1
2 release_date_file1
3 title_file1
4 genre_file1
5 international_box_office
6 domestic_box_office
7 worldwide_box_office
8 production_budget
9 opening_weekend
10 theatre_count
11 avg run per theatre
12 runtime_file1
13 keywords
14 creative_type
15 url_file1
16 title_clean_file1
17 movie_key
18 url_file2
19 title_file2
20 studio
21 rating
22 runtime_file2
23 cast
24 director
25 genre_file2
26 summary
27 awards
28 metascore
29 userscore
30 release_date_file2
31 title_clean_file2
32 release_year_file2
33 url
34 title
35 runtime
36 genre
37 release_date
38 title_clean
39 release_year

In [78]:
# Check whether the extra File 2 columns contain data
extra_file2_columns = [
    "url",
    "title",
    "runtime",
    "genre",
    "release_date",
    "title_clean",
    "release_year"
]

# Count non-missing values in the extra columns
print(
    merged_all[extra_file2_columns]
    .notna()
    .sum()
)

url             3235
title           3235
runtime         3146
genre           3224
release_date    3235
title_clean     3235
release_year    3235
dtype: int64

In [80]:
# Fill missing File 2 columns using the extra File 2 columns
merged_all["url_file2"] = merged_all["url_file2"].fillna(merged_all["url"])
merged_all["title_file2"] = merged_all["title_file2"].fillna(merged_all["title"])
merged_all["runtime_file2"] = merged_all["runtime_file2"].fillna(merged_all["runtime"])
merged_all["genre_file2"] = merged_all["genre_file2"].fillna(merged_all["genre"])
merged_all["release_date_file2"] = merged_all["release_date_file2"].fillna(merged_all["release_date"])

# Remove temporary matching columns and extra File 2 columns
merged_all = merged_all.drop(columns=[
    "title_clean_file1",
    "title_clean_file2",
    "release_year_file2",
    "url",
    "title",
    "runtime",
    "genre",
    "release_date",
    "title_clean",
    "release_year"
])

# Display the new number of columns
print("Number of columns:", len(merged_all.columns))

KeyError: 'url'

In [81]:
# Check the final number of rows and columns
print("Number of movies:", len(merged_all))
print("Number of columns:", len(merged_all.columns))

# Check for completely duplicated rows
print("Duplicate rows:", merged_all.duplicated().sum())

Number of movies: 33847
Number of columns: 29
Duplicate rows: 0

In [82]:
# Create a unique movie ID for every movie
merged_all.insert(
    0,
    "movie_id",
    range(1, len(merged_all) + 1)
)

# Check the movie IDs
print(merged_all[["movie_id", "movie_key"]].head())

# Verify that all movie IDs are unique
print("Unique movie IDs:", merged_all["movie_id"].nunique())

   movie_id           movie_key
0         1   vse_ispravit_2016
1         2    003 seconds_2017
2         3          00mhz_2019
3         4         015400_2018
4         5         022200_2017
Unique movie IDs: 33847

In [83]:
# Verify that movie IDs are complete and sequential
print("Minimum movie ID:", merged_all["movie_id"].min())
print("Maximum movie ID:", merged_all["movie_id"].max())
print("Missing movie IDs:", merged_all["movie_id"].isna().sum())
print("Unique movie IDs:", merged_all["movie_id"].nunique())

Minimum movie ID: 1
Maximum movie ID: 33847
Missing movie IDs: 0
Unique movie IDs: 33847

In [84]:
# Save the final merged dataset
merged_all.to_csv("movies_file1_file2_final.csv", index=False)

# Confirm that the file was saved
print("Final file saved successfully.")

Final file saved successfully.

In [85]:
# Export the final dataset to an Excel file
merged_all.to_excel(
    "movies_file1_file2_final.xlsx",
    index=False
)

# Confirm that the file was created
print("Excel file saved successfully.")

Excel file saved successfully.

In [86]:
# Show the exact folder where the Excel file was saved

import os

print(os.path.abspath("movies_file1_file2_final.xlsx"))

/Users/pouriyarezaali/Desktop/movies_file1_file2_final.xlsx

In [87]:
# Check the title in the final dataset
print(merged_all.loc[merged_all["title_file1"].str.contains("YÃ", na=False), "title_file1"].head(20))

159                                    2 YÃƒÂ¶tÃƒÂ¤ Aamuun
6652     DiktatÃƒÂ¶r Adolf Hitler'in Hayatinin Esrareng...
7283                            DÃƒÂ  YÃƒÂº HÃ‡Å½i TÃƒÂ¡ng
7431     Eiga YÃ…ï¿½kai Wotchi Jamu: YÃ…ï¿½kai Gakuen Y...
7432     Eiga YÃ…ï¿½kai Wotchi TanjÃ…ï¿½ no Himitsu da ...
12393                        JiÃƒÂ n DÃ‡Å½ng WÃ„â€ºi YÃƒÂ¨
15578     Maceraci YÃƒÂ¼zgeÃƒÂ§ler: BÃƒÂ¼yÃƒÂ¼k GÃƒÂ¶steri
17482                 MÃƒÂ­ng YuÃƒÂ¨ JÃ‡ï¿½ ShÃƒÂ­ YÃ‡â€™u
21516                               Sakli YÃƒÂ¼zler: Bosna
27998                               Tut YÃƒÂ¼regimden Anne
30225                               YÃ„Â±l DÃƒÂ¶nÃƒÂ¼mÃƒÂ¼
30226                  YÃ„Â±ldÃ„Â±zlar da Kayar: Das Borak
30227                                       YÃƒÂ¶ armahtaa
30229                                     YÃƒÂ´kai Watch 3
30230                                     YÃƒÂ´kai Watch 4
30231                                             YÃƒÂ»zai
Name: title_file1, dtype: object

In [88]:
# Compare the corrupted title across the original and final datasets
print("File 1 original:")
print(df1.loc[
    df1["title"].astype(str).str.contains("YÃ", na=False),
    "title"
].head(10))

print("\nFinal merged dataset:")
print(merged_all.loc[
    merged_all["title_file1"].astype(str).str.contains("YÃ", na=False),
    "title_file1"
].head(10))

File 1 original:
319                                       YÃƒÂ´kai Watch 4
934                                       YÃƒÂ´kai Watch 3
3510     DiktatÃƒÂ¶r Adolf Hitler'in Hayatinin Esrareng...
4026                   YÃ„Â±ldÃ„Â±zlar da Kayar: Das Borak
4740                                   2 YÃƒÂ¶tÃƒÂ¤ Aamuun
6003                  MÃƒÂ­ng YuÃƒÂ¨ JÃ‡ï¿½ ShÃƒÂ­ YÃ‡â€™u
6213                            DÃƒÂ  YÃƒÂº HÃ‡Å½i TÃƒÂ¡ng
6787                                              YÃƒÂ»zai
7463     Eiga YÃ…ï¿½kai Wotchi TanjÃ…ï¿½ no Himitsu da ...
10354                               Tut YÃƒÂ¼regimden Anne
Name: title, dtype: object

Final merged dataset:
159                                    2 YÃƒÂ¶tÃƒÂ¤ Aamuun
6652     DiktatÃƒÂ¶r Adolf Hitler'in Hayatinin Esrareng...
7283                            DÃƒÂ  YÃƒÂº HÃ‡Å½i TÃƒÂ¡ng
7431     Eiga YÃ…ï¿½kai Wotchi Jamu: YÃ…ï¿½kai Gakuen Y...
7432     Eiga YÃ…ï¿½kai Wotchi TanjÃ…ï¿½ no Himitsu da ...
12393                        JiÃƒÂ n DÃ‡Å½ng WÃ„â€ºi YÃƒÂ¨
15578     Maceraci YÃƒÂ¼zgeÃƒÂ§ler: BÃƒÂ¼yÃƒÂ¼k GÃƒÂ¶steri
17482                 MÃƒÂ­ng YuÃƒÂ¨ JÃ‡ï¿½ ShÃƒÂ­ YÃ‡â€™u
21516                               Sakli YÃƒÂ¼zler: Bosna
27998                               Tut YÃƒÂ¼regimden Anne
Name: title_file1, dtype: object

In [89]:
# Count titles that contain common mojibake characters
mojibake_pattern = r"[ÃÂâ�]"

suspicious_titles = df1[
    df1["title"].astype(str).str.contains(
        mojibake_pattern,
        regex=True,
        na=False
    )
]

print("Suspicious titles:", len(suspicious_titles))

# Show a sample of suspicious titles
print(suspicious_titles["title"].head(30).to_string(index=False))

Suspicious titles: 2636
                                   TakhtÃƒÂ© siah
    O Ano em Que Meus Pais SaÃƒÂ­ram de FÃƒÂ©rias
     Minuscule - La vallÃƒÂ©e des fourmis perdues
                  Boca Juniors 3D, la pelÃƒÂ­cula
                                     HÃƒÂ¢monÃƒÂ®
             Desu nÃƒÂ´to: Light Up the New World
                       Nuo Lietuvos nepabÃ„â€”gsi
                        PÃƒÂ¨re fils thÃƒÂ©rapie!
             Doktor Martin: ZÃƒÂ¡hada v Beskydech
                                Tiempo despuÃƒÂ©s
                 Tarp mÃ…Â«sÃ…Â³ mergaiÃ„ï¿½iÃ…Â³
                                       TrileÃƒÂ§e
                   MÃƒÂ¼saadenizle BÃƒÂ¼yÃƒÂ¼kler
                                       BÃƒÂ¶rÃƒÂ¼
                   Un violent dÃƒÂ©sir de bonheur
                                L'homme fidÃƒÂ¨le
                                   YanÃ„Â±mda Kal
   Kamen RaidÃƒÂ¢ Heisei JenerÃƒÂªshonzu FoebÃƒÂ¢
                                     SÃƒÂ¼kut Evi
                          Kurtlar ve Ãƒâ€¡akallar
   D.P.A. Detetives Do PrÃƒÂ©dio Azul 2 - O Filme
               AÃƒÂ¯lo: Une odyssÃƒÂ©e en Laponie
                      ItÃ¢â‚¬â„¢s March 3Rd Again
                                 ParayÃ„Â± Bulduk
KlasÃ„â€”s susitikimas: berniukai sugrÃ„Â¯Ã…Â¾ta!
                           Fala SÃƒÂ©rio, MÃƒÂ£e!
                      L'ÃƒÂ©change des princesses
                                 Ãƒâ€¡at Kapi Ask
                                         CaffÃƒÂ¨
                                  Tout lÃƒÂ -haut

In [90]:
# Test a standard mojibake repair on suspicious titles
def test_mojibake_repair(text):
    try:
        return text.encode("latin1").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text

# Apply the repair only for testing
test_titles = suspicious_titles["title"].astype(str).apply(test_mojibake_repair)

# Compare original and repaired titles
comparison = pd.DataFrame({
    "original": suspicious_titles["title"].values,
    "repaired": test_titles.values
})

print(comparison.head(30).to_string(index=False))

                                         original                                          repaired
                                   TakhtÃƒÂ© siah                                    TakhtÃƒÂ© siah
    O Ano em Que Meus Pais SaÃƒÂ­ram de FÃƒÂ©rias     O Ano em Que Meus Pais SaÃƒÂ­ram de FÃƒÂ©rias
     Minuscule - La vallÃƒÂ©e des fourmis perdues      Minuscule - La vallÃƒÂ©e des fourmis perdues
                  Boca Juniors 3D, la pelÃƒÂ­cula                   Boca Juniors 3D, la pelÃƒÂ­cula
                                     HÃƒÂ¢monÃƒÂ®                                      HÃƒÂ¢monÃƒÂ®
             Desu nÃƒÂ´to: Light Up the New World              Desu nÃƒÂ´to: Light Up the New World
                       Nuo Lietuvos nepabÃ„â€”gsi                        Nuo Lietuvos nepabÃ„â€”gsi
                        PÃƒÂ¨re fils thÃƒÂ©rapie!                         PÃƒÂ¨re fils thÃƒÂ©rapie!
             Doktor Martin: ZÃƒÂ¡hada v Beskydech              Doktor Martin: ZÃƒÂ¡hada v Beskydech
                                Tiempo despuÃƒÂ©s                                 Tiempo despuÃƒÂ©s
                 Tarp mÃ…Â«sÃ…Â³ mergaiÃ„ï¿½iÃ…Â³                  Tarp mÃ…Â«sÃ…Â³ mergaiÃ„ï¿½iÃ…Â³
                                       TrileÃƒÂ§e                                        TrileÃƒÂ§e
                   MÃƒÂ¼saadenizle BÃƒÂ¼yÃƒÂ¼kler                    MÃƒÂ¼saadenizle BÃƒÂ¼yÃƒÂ¼kler
                                       BÃƒÂ¶rÃƒÂ¼                                        BÃƒÂ¶rÃƒÂ¼
                   Un violent dÃƒÂ©sir de bonheur                    Un violent dÃƒÂ©sir de bonheur
                                L'homme fidÃƒÂ¨le                                 L'homme fidÃƒÂ¨le
                                   YanÃ„Â±mda Kal                                    YanÃ„Â±mda Kal
   Kamen RaidÃƒÂ¢ Heisei JenerÃƒÂªshonzu FoebÃƒÂ¢    Kamen RaidÃƒÂ¢ Heisei JenerÃƒÂªshonzu FoebÃƒÂ¢
                                     SÃƒÂ¼kut Evi                                      SÃƒÂ¼kut Evi
                          Kurtlar ve Ãƒâ€¡akallar                           Kurtlar ve Ãƒâ€¡akallar
   D.P.A. Detetives Do PrÃƒÂ©dio Azul 2 - O Filme    D.P.A. Detetives Do PrÃƒÂ©dio Azul 2 - O Filme
               AÃƒÂ¯lo: Une odyssÃƒÂ©e en Laponie                AÃƒÂ¯lo: Une odyssÃƒÂ©e en Laponie
                      ItÃ¢â‚¬â„¢s March 3Rd Again                       ItÃ¢â‚¬â„¢s March 3Rd Again
                                 ParayÃ„Â± Bulduk                                  ParayÃ„Â± Bulduk
KlasÃ„â€”s susitikimas: berniukai sugrÃ„Â¯Ã…Â¾ta! KlasÃ„â€”s susitikimas: berniukai sugrÃ„Â¯Ã…Â¾ta!
                           Fala SÃƒÂ©rio, MÃƒÂ£e!                            Fala SÃƒÂ©rio, MÃƒÂ£e!
                      L'ÃƒÂ©change des princesses                       L'ÃƒÂ©change des princesses
                                 Ãƒâ€¡at Kapi Ask                                  Ãƒâ€¡at Kapi Ask
                                         CaffÃƒÂ¨                                          CaffÃƒÂ¨
                                  Tout lÃƒÂ -haut                                   Tout lÃƒÂ -haut

In [91]:
# Test multiple decoding rounds on one corrupted title
text = "TakhtÃƒÂ© siah"

print("Original:")
print(text)

# Try repeated mojibake repair
for i in range(1, 5):
    try:
        text = text.encode("latin1").decode("utf-8")
        print(f"Round {i}:")
        print(text)
    except (UnicodeEncodeError, UnicodeDecodeError) as e:
        print(f"Round {i}: Repair failed")
        print(e)
        break

Original:
TakhtÃƒÂ© siah
Round 1: Repair failed
'latin-1' codec can't encode character '\u0192' in position 6: ordinal not in range(256)

In [92]:
# Test mojibake repair using Windows-1252 encoding
text = "TakhtÃƒÂ© siah"

print("Original:")
print(text)

# Try repeated repair rounds
for i in range(1, 5):
    try:
        text = text.encode("cp1252").decode("utf-8")
        print(f"Round {i}:")
        print(text)
    except (UnicodeEncodeError, UnicodeDecodeError) as e:
        print(f"Round {i}: Repair failed")
        print(e)
        break

Original:
TakhtÃƒÂ© siah
Round 1:
TakhtÃ© siah
Round 2:
Takhté siah
Round 3: Repair failed
'utf-8' codec can't decode byte 0xe9 in position 5: invalid continuation byte

In [93]:
# Test repeated mojibake repair on all suspicious titles
def repair_mojibake(text, max_rounds=3):
    original = text

    for _ in range(max_rounds):
        try:
            repaired = text.encode("cp1252").decode("utf-8")
            
            # Stop if the text no longer changes
            if repaired == text:
                break
            
            text = repaired

        except (UnicodeEncodeError, UnicodeDecodeError):
            break

    return original, text


# Test the repair function on suspicious titles
test_results = suspicious_titles["title"].astype(str).apply(
    lambda x: repair_mojibake(x)[1]
)

# Count titles that changed
changed = test_results != suspicious_titles["title"].astype(str)

print("Suspicious titles:", len(suspicious_titles))
print("Titles that can be repaired:", changed.sum())

# Show examples
comparison = pd.DataFrame({
    "original": suspicious_titles.loc[changed, "title"].values,
    "repaired": test_results[changed].values
})

print(comparison.head(30).to_string(index=False))

Suspicious titles: 2636
Titles that can be repaired: 2553
                                         original                                    repaired
                                   TakhtÃƒÂ© siah                                 Takhté siah
    O Ano em Que Meus Pais SaÃƒÂ­ram de FÃƒÂ©rias     O Ano em Que Meus Pais Saíram de Férias
     Minuscule - La vallÃƒÂ©e des fourmis perdues   Minuscule - La vallée des fourmis perdues
                  Boca Juniors 3D, la pelÃƒÂ­cula                Boca Juniors 3D, la película
                                     HÃƒÂ¢monÃƒÂ®                                      Hâmonî
             Desu nÃƒÂ´to: Light Up the New World           Desu nôto: Light Up the New World
                       Nuo Lietuvos nepabÃ„â€”gsi                      Nuo Lietuvos nepabėgsi
                        PÃƒÂ¨re fils thÃƒÂ©rapie!                         Père fils thérapie!
             Doktor Martin: ZÃƒÂ¡hada v Beskydech           Doktor Martin: Záhada v Beskydech
                                Tiempo despuÃƒÂ©s                              Tiempo después
                 Tarp mÃ…Â«sÃ…Â³ mergaiÃ„ï¿½iÃ…Â³                     Tarp mÅ«sÅ³ mergaiÄ�iÅ³
                                       TrileÃƒÂ§e                                     Trileçe
                   MÃƒÂ¼saadenizle BÃƒÂ¼yÃƒÂ¼kler                       Müsaadenizle Büyükler
                                       BÃƒÂ¶rÃƒÂ¼                                        Börü
                   Un violent dÃƒÂ©sir de bonheur                 Un violent désir de bonheur
                                L'homme fidÃƒÂ¨le                              L'homme fidèle
                                   YanÃ„Â±mda Kal                                 Yanımda Kal
   Kamen RaidÃƒÂ¢ Heisei JenerÃƒÂªshonzu FoebÃƒÂ¢       Kamen Raidâ Heisei Jenerêshonzu Foebâ
                                     SÃƒÂ¼kut Evi                                   Sükut Evi
                          Kurtlar ve Ãƒâ€¡akallar                         Kurtlar ve Çakallar
   D.P.A. Detetives Do PrÃƒÂ©dio Azul 2 - O Filme D.P.A. Detetives Do Prédio Azul 2 - O Filme
               AÃƒÂ¯lo: Une odyssÃƒÂ©e en Laponie                Aïlo: Une odyssée en Laponie
                      ItÃ¢â‚¬â„¢s March 3Rd Again                        It’s March 3Rd Again
                                 ParayÃ„Â± Bulduk                               Parayı Bulduk
KlasÃ„â€”s susitikimas: berniukai sugrÃ„Â¯Ã…Â¾ta!     Klasės susitikimas: berniukai sugrįžta!
                           Fala SÃƒÂ©rio, MÃƒÂ£e!                            Fala Sério, Mãe!
                      L'ÃƒÂ©change des princesses                    L'échange des princesses
                                 Ãƒâ€¡at Kapi Ask                                Çat Kapi Ask
                                         CaffÃƒÂ¨                                       Caffè
                                  Tout lÃƒÂ -haut                                Tout là-haut

In [94]:
# Find titles that still look corrupted after the repair
still_corrupted = comparison[
    comparison["repaired"].str.contains(
        r"[ÃÂÅÆ�]",
        regex=True,
        na=False
    )
]

print("Still corrupted after repair:", len(still_corrupted))

# Show examples that need further investigation
print(still_corrupted.head(40).to_string(index=False))

Still corrupted after repair: 99
                                                                                     original                                                                    repaired
                                                             Tarp mÃ…Â«sÃ…Â³ mergaiÃ„ï¿½iÃ…Â³                                                     Tarp mÅ«sÅ³ mergaiÄ�iÅ³
                                                                   KidÃ…ï¿½ Senshi Gandamu NT                                                     KidÅ� Senshi Gandamu NT
                                           Mimi a LÃƒÂ­za: ZÃƒÂ¡hada vianoÃ„ï¿½nÃƒÂ©ho svetla                                   Mimi a LÃ­za: ZÃ¡hada vianoÄ�nÃ©ho svetla
                                                                              Djon Ãƒï¿½frica                                                                Djon Ã�frica
                                                                            BureibusutÃ…ï¿½mu                                                              BureibusutÅ�mu
                                                                    El Ãƒï¿½rbol de la sangre                                                      El Ã�rbol de la sangre
Kaettekita DÃ…ï¿½butsu Sentai JÃ…Â«Ã…ï¿½jÃ„ï¿½ Oinochi ChÃ…ï¿½dai! ChikyÃ…Â« Ã…Å’ja Ketteisen Kaettekita DÅ�butsu Sentai JÅ«Å�jÄ� Oinochi ChÅ�dai! ChikyÅ« ÅŒja Ketteisen
                                                                FreeÃ¯Â¼ï¿½ -Take Your Marks-                                                   Freeï¼� -Take Your Marks-
                                                                   BratÃ…â„¢ÃƒÂ­Ã„ï¿½ek Karel                                                          BratÅ™Ã­Ä�ek Karel
                                              IMT Smile and LÃƒÂºÃ„ï¿½nica - Made in Slovakia                                  IMT Smile and LÃºÄ�nica - Made in Slovakia
                                                           Ma Famille TÃ¢â‚¬â„¢Adore DÃƒÂ©jÃƒ                                                  Ma Famille Tâ€™Adore DÃ©jÃ
                                                                                   MeÃ„ï¿½iar                                                                     MeÄ�iar
                                                                                   Ãƒï¿½nimas                                                                     Ã�nimas
                                                                       Ostravak OSTRAVSKÃƒï¿½                                                         Ostravak OSTRAVSKÃ�
                                                                                 A Ãƒï¿½rvore                                                                   A Ã�rvore
                                                                     KÃ…ï¿½ng tiÃ„ï¿½n liÃƒÂ¨                                                            KÅ�ng tiÄ�n liÃ¨
                                                               Po Ã„ï¿½em muÃ…Â¾i touÃ…Â¾ÃƒÂ­                                                       Po Ä�em muÅ¾i touÅ¾Ã­
                                                            Ãƒï¿½ndice MÃƒÂ©dio de Felicidade                                                Ã�ndice MÃ©dio de Felicidade
                                                                       KÃ…â„¢iÃ…Â¾ÃƒÂ¡Ã„ï¿½ek                                                                KÅ™iÅ¾Ã¡Ä�ek
                                                                                 UÃ„ï¿½itelka                                                                   UÄ�itelka
                                                         MÃƒÂ­ng YuÃƒÂ¨ JÃ‡ï¿½ ShÃƒÂ­ YÃ‡â€™u                                                    MÃ­ng YuÃ¨ JÇ� ShÃ­ YÇ’u
                                        Eiga ShimajirÃ…ï¿½: MahÃ…ï¿½ no Shima no DaibÃ…ï¿½ken                                Eiga ShimajirÅ�: MahÅ� no Shima no DaibÅ�ken
                                                               VÃ…Â¡etko Ã„ï¿½o mÃƒÂ¡m rÃƒÂ¡d                                                       VÅ¡etko Ä�o mÃ¡m rÃ¡d
                                                               BeiburÃ„â€œdo bÃ„ï¿½suto goddo                                                    BeiburÄ“do bÄ�suto goddo
                                          Eiga YÃ…ï¿½kai Wotchi TanjÃ…ï¿½ no Himitsu da Nyan!                               Eiga YÅ�kai Wotchi TanjÅ� no Himitsu da Nyan!
                                                                                   DubÃ„ï¿½ek                                                                     DubÄ�ek
                                                             ChÃ„ï¿½i dÃƒÂ n zhuÃ„ï¿½njiÃ„ï¿½                                                       ChÄ�i dÃ n zhuÄ�njiÄ�
                                                 Jak bÃƒÂ¡snÃƒÂ­ci Ã„ï¿½ekajÃƒÂ­ na zÃƒÂ¡zrak                                           Jak bÃ¡snÃ­ci Ä�ekajÃ­ na zÃ¡zrak
                                            GekijÃ…ï¿½-ban Kuroshitsuji: Book of the Atlantic                              GekijÅ�-ban Kuroshitsuji: Book of the Atlantic
                                                                                    AGÃƒï¿½VA                                                                      AGÃ�VA
                                                             Purikyua SÃ…Â«pÃ„ï¿½ SutÃ„ï¿½zu!                                                    Purikyua SÅ«pÄ� SutÄ�zu!
                                                           HuÃ„ï¿½n yuÃƒÂ¨ xÃ‡ï¿½jÃƒÂ¹ rÃƒÂ©n                                                      HuÄ�n yuÃ¨ xÇ�jÃ¹ rÃ©n
                                                                                Piata loÃ„ï¿½                                                                  Piata loÄ�
                                                          Eiga Purikyua DorÃ„Â«mu SutÃ„ï¿½zu!                                              Eiga Purikyua DorÄ«mu SutÄ�zu!
                                                       BungÃ…ï¿½ Sutorei Doggusu Deddo Appuru                                         BungÅ� Sutorei Doggusu Deddo Appuru
                                                                             TlumoÃ„ï¿½nÃƒÂ­k                                                                 TlumoÄ�nÃ­k
                                                   MÃ‡Å½ gÃƒÂ© lÃƒÂ¬ tÃƒÂ¨ de chÃ…Â«ntiÃ„ï¿½n                                               MÇŽ gÃ© lÃ¬ tÃ¨ de chÅ«ntiÄ�n
                                                                 DiÃƒÂ© xian guÃ‡ï¿½ tÃƒÂ¡n 2                                                       DiÃ© xian guÇ� tÃ¡n 2
                                                            JÃ„Â«nghÃƒÂºn xiÃƒÂ¹huÃ„ï¿½xiÃƒÂ©                                                      JÄ«nghÃºn xiÃ¹huÄ�xiÃ©
                                                                   VeÃ„ï¿½ne Tvoja NevernÃƒÂ¡                                                       VeÄ�ne Tvoja NevernÃ¡

In [95]:
# Test a second repair method using Latin-1
test_texts = [
    "Tarp mÅ«sÅ³ mergaiÄ�iÅ³",
    "KidÅ� Senshi Gandamu NT",
    "Mimi a Líza: Záhada vianoÄ�ného svetla",
    "El Ã�rbol de la sangre"
]

for text in test_texts:
    try:
        repaired = text.encode("latin1").decode("utf-8")
        print("Original :", text)
        print("Repaired :", repaired)
        print()
    except (UnicodeEncodeError, UnicodeDecodeError) as e:
        print("Original :", text)
        print("Repair failed:", e)
        print()

Original : Tarp mÅ«sÅ³ mergaiÄ�iÅ³
Repair failed: 'latin-1' codec can't encode character '\ufffd' in position 19: ordinal not in range(256)

Original : KidÅ� Senshi Gandamu NT
Repair failed: 'latin-1' codec can't encode character '\ufffd' in position 4: ordinal not in range(256)

Original : Mimi a Líza: Záhada vianoÄ�ného svetla
Repair failed: 'latin-1' codec can't encode character '\ufffd' in position 26: ordinal not in range(256)

Original : El Ã�rbol de la sangre
Repair failed: 'latin-1' codec can't encode character '\ufffd' in position 4: ordinal not in range(256)

In [96]:
# Check how many original File 1 titles already contain the replacement character
replacement_char_titles = df1[
    df1["title"].astype(str).str.contains("�", na=False)
]

print("Titles containing �:", len(replacement_char_titles))

# Show examples
print(
    replacement_char_titles["title"]
    .head(30)
    .to_string(index=False)
)

Titles containing �: 0
Series([], )

In [97]:
# Test different encoding combinations on the original corrupted title
text = "Tarp mÃ…Â«sÃ…Â³ mergaiÃ„ï¿½iÃ…Â³"

methods = [
    ("cp1252 -> utf8", "cp1252"),
    ("latin1 -> utf8", "latin1"),
]

for name, encoding in methods:
    try:
        repaired = text.encode(encoding).decode("utf-8")
        print(name)
        print(repaired)
        print()
    except Exception as e:
        print(name)
        print("Failed:", e)
        print()

cp1252 -> utf8
Tarp mÅ«sÅ³ mergaiÄ�iÅ³

latin1 -> utf8
Failed: 'latin-1' codec can't encode character '\u2026' in position 7: ordinal not in range(256)

In [98]:
# Inspect the exact Unicode characters in the corrupted title
text = "Tarp mÃ…Â«sÃ…Â³ mergaiÃ„ï¿½iÃ…Â³"

print("Original:")
print(repr(text))

print("\nCharacters and Unicode code points:")

for char in text:
    print(
        repr(char),
        f"U+{ord(char):04X}"
    )

Original:
'Tarp mÃ…Â«sÃ…Â³ mergaiÃ„ï¿½iÃ…Â³'

Characters and Unicode code points:
'T' U+0054
'a' U+0061
'r' U+0072
'p' U+0070
' ' U+0020
'm' U+006D
'Ã' U+00C3
'…' U+2026
'Â' U+00C2
'«' U+00AB
's' U+0073
'Ã' U+00C3
'…' U+2026
'Â' U+00C2
'³' U+00B3
' ' U+0020
'm' U+006D
'e' U+0065
'r' U+0072
'g' U+0067
'a' U+0061
'i' U+0069
'Ã' U+00C3
'„' U+201E
'ï' U+00EF
'¿' U+00BF
'½' U+00BD
'i' U+0069
'Ã' U+00C3
'…' U+2026
'Â' U+00C2
'³' U+00B3

In [99]:
# Test several possible mojibake repair methods
text = "Tarp mÃ…Â«sÃ…Â³ mergaiÃ„ï¿½iÃ…Â³"

methods = [
    ("cp1252 -> utf8", "cp1252"),
    ("cp1252 -> utf8 -> cp1252 -> utf8", "double"),
]

for name, method in methods:
    try:
        if method == "cp1252":
            repaired = text.encode("cp1252").decode("utf-8")

        elif method == "double":
            repaired = text.encode("cp1252").decode("utf-8")
            repaired = repaired.encode("cp1252").decode("utf-8")

        print(name)
        print(repr(repaired))
        print(repaired)
        print()

    except Exception as e:
        print(name)
        print("Failed:", e)
        print()

cp1252 -> utf8
'Tarp mÅ«sÅ³ mergaiÄ�iÅ³'
Tarp mÅ«sÅ³ mergaiÄ�iÅ³

cp1252 -> utf8 -> cp1252 -> utf8
Failed: 'charmap' codec can't encode character '\ufffd' in position 19: character maps to <undefined>

In [100]:
# Find the movie in File 1 and File 2 using the movie key
movie_key = "tarp_m_s_mergai_2018"

print("File 1:")
print(
    df1[df1["movie_key"] == movie_key][
        ["title", "release_year", "movie_key"]
    ].to_string(index=False)
)

print("\nFile 2:")
print(
    df2[df2["movie_key"] == movie_key][
        ["title", "release_year", "movie_key"]
    ].to_string(index=False)
)

File 1:
Empty DataFrame
Columns: [title, release_year, movie_key]
Index: []

File 2:
Empty DataFrame
Columns: [title, release_year, movie_key]
Index: []

In [101]:
# Repair mojibake in suspicious movie titles
def repair_mojibake(text, max_rounds=3):
    for _ in range(max_rounds):
        try:
            repaired = text.encode("cp1252").decode("utf-8")

            if repaired == text:
                break

            text = repaired

        except (UnicodeEncodeError, UnicodeDecodeError):
            break

    return text


# Test the repair on suspicious titles
test_repaired = suspicious_titles["title"].astype(str).apply(
    repair_mojibake
)

# Show original and repaired titles
comparison = pd.DataFrame({
    "original": suspicious_titles["title"].astype(str),
    "repaired": test_repaired
})

print(comparison.head(50).to_string(index=False))

                                                           original                                                         repaired
                                                     TakhtÃƒÂ© siah                                                      Takhté siah
                      O Ano em Que Meus Pais SaÃƒÂ­ram de FÃƒÂ©rias                          O Ano em Que Meus Pais Saíram de Férias
                       Minuscule - La vallÃƒÂ©e des fourmis perdues                        Minuscule - La vallée des fourmis perdues
                                    Boca Juniors 3D, la pelÃƒÂ­cula                                     Boca Juniors 3D, la película
                                                       HÃƒÂ¢monÃƒÂ®                                                           Hâmonî
                               Desu nÃƒÂ´to: Light Up the New World                                Desu nôto: Light Up the New World
                                         Nuo Lietuvos nepabÃ„â€”gsi                                           Nuo Lietuvos nepabėgsi
                                          PÃƒÂ¨re fils thÃƒÂ©rapie!                                              Père fils thérapie!
                               Doktor Martin: ZÃƒÂ¡hada v Beskydech                                Doktor Martin: Záhada v Beskydech
                                                  Tiempo despuÃƒÂ©s                                                   Tiempo después
                                   Tarp mÃ…Â«sÃ…Â³ mergaiÃ„ï¿½iÃ…Â³                                          Tarp mÅ«sÅ³ mergaiÄ�iÅ³
                                                         TrileÃƒÂ§e                                                          Trileçe
                                     MÃƒÂ¼saadenizle BÃƒÂ¼yÃƒÂ¼kler                                            Müsaadenizle Büyükler
                                                         BÃƒÂ¶rÃƒÂ¼                                                             Börü
                                     Un violent dÃƒÂ©sir de bonheur                                      Un violent désir de bonheur
                                                  L'homme fidÃƒÂ¨le                                                   L'homme fidèle
                                                     YanÃ„Â±mda Kal                                                      Yanımda Kal
                     Kamen RaidÃƒÂ¢ Heisei JenerÃƒÂªshonzu FoebÃƒÂ¢                            Kamen Raidâ Heisei Jenerêshonzu Foebâ
                                                       SÃƒÂ¼kut Evi                                                        Sükut Evi
                                            Kurtlar ve Ãƒâ€¡akallar                                              Kurtlar ve Çakallar
                     D.P.A. Detetives Do PrÃƒÂ©dio Azul 2 - O Filme                      D.P.A. Detetives Do Prédio Azul 2 - O Filme
                                 AÃƒÂ¯lo: Une odyssÃƒÂ©e en Laponie                                     Aïlo: Une odyssée en Laponie
                                        ItÃ¢â‚¬â„¢s March 3Rd Again                                             It’s March 3Rd Again
                                                   ParayÃ„Â± Bulduk                                                    Parayı Bulduk
                  KlasÃ„â€”s susitikimas: berniukai sugrÃ„Â¯Ã…Â¾ta!                          Klasės susitikimas: berniukai sugrįžta!
                                             Fala SÃƒÂ©rio, MÃƒÂ£e!                                                 Fala Sério, Mãe!
                                        L'ÃƒÂ©change des princesses                                         L'échange des princesses
                                                   Ãƒâ€¡at Kapi Ask                                                     Çat Kapi Ask
                                                           CaffÃƒÂ¨                                                            Caffè
                                                    Tout lÃƒÂ -haut                                                     Tout là-haut
Jesucristo Superstar. Un hito en la historia del musical espaÃƒÂ±ol Jesucristo Superstar. Un hito en la historia del musical español
                                                      QuizÃƒÂ¡s hoy                                                       Quizás hoy
                                                MollyÃ¢â‚¬â„¢s Game                                                     Molly’s Game
                                          MartÃ„Â±larÃ„Â±n Efendisi                                              Martıların Efendisi
                                                  Garde alternÃƒÂ©e                                                   Garde alternée
                                                  DÃƒÂ¼s Kirginlari                                                   Düs Kirginlari
                                                      AÃ…Å¸k Bu mu?                                                       Aşk Bu mu?
                                               RÃƒÂ©mi sans famille                                                Rémi sans famille
                                                       BelalÃ„Â±lar                                                        Belalılar
                                            AcÃ„Â± TatlÃ„Â± EkÃ…Å¸i                                                   Acı Tatlı Ekşi
                                                   YÃƒÂ´kai Watch 4                                                    Yôkai Watch 4
                                             Son Ãƒâ€¡Ã„Â±kÃ„Â±Ã…Å¸                                                        Son Çıkış
                                         Ã…Å¾eytan GeÃƒÂ§idi Enhara                                             Şeytan Geçidi Enhara
                                                  ParanÃ„Â±n Kokusu                                                   Paranın Kokusu
                                  The PartyÃ¢â‚¬â„¢s Just Beginning                                       The Party’s Just Beginning
                                          Mi PequeÃƒÂ±o Gran Hombre                                           Mi Pequeño Gran Hombre
                                 Poyraz Karayel: KÃƒÂ¼resel Sermaye                                  Poyraz Karayel: Küresel Sermaye
                                                      NiÃƒÂ±a Perro                                                       Niña Perro
                                      DrÃƒÂ´les de petites bÃƒÂªtes                                          Drôles de petites bêtes
                                               Ma mÃƒÂ¨re est folle                                                Ma mère est folle

In [102]:
# Identify titles that can be repaired safely
original_titles = suspicious_titles["title"].astype(str)

repaired_titles = original_titles.apply(repair_mojibake)

changed = repaired_titles != original_titles

print("Suspicious titles:", len(original_titles))
print("Successfully repaired:", changed.sum())
print("Not repaired:", (~changed).sum())

Suspicious titles: 2636
Successfully repaired: 2553
Not repaired: 83

In [103]:
# Show all titles that were not repaired by the first method
not_repaired = comparison[comparison["original"] == comparison["repaired"]].copy()

print("Titles needing advanced repair:", len(not_repaired))

print(
    not_repaired.to_string(index=False)
)

Titles needing advanced repair: 83
                                                                                                                                                                                                                                                                       original                                                                                                                                                                                                                                                                        repaired
                                                                                                                                                                                                                 ÃÅ¡Ãï¿½Ãâ€™ÃÅ¡Ãï¿½Ãâ€”ÃÂ¡ÃÅ¡ÃÅ¾Ãâ€¢ ÃÂ¢ÃÂ ÃËœÃÅ¾                                                                                                                                                                                                                  ÃÅ¡Ãï¿½Ãâ€™ÃÅ¡Ãï¿½Ãâ€”ÃÂ¡ÃÅ¡ÃÅ¾Ãâ€¢ ÃÂ¢ÃÂ ÃËœÃÅ¾
                                                                                                                                                                                                              Ãâ€˜Ãï¿½Ãâ€˜Ãï¿½ ÃÂ¯Ãâ€œÃï¿½. Ãï¿½Ãï¿½ÃÂ§Ãï¿½Ãâ€ºÃÅ¾                                                                                                                                                                                                               Ãâ€˜Ãï¿½Ãâ€˜Ãï¿½ ÃÂ¯Ãâ€œÃï¿½. Ãï¿½Ãï¿½ÃÂ§Ãï¿½Ãâ€ºÃÅ¾
                                                                                                                                                                                                                     Ãâ€œÃÂ Ãâ€¢ÃÂ¦ÃÅ¡ÃËœÃâ„¢ ÃÅ¾ÃÂ Ãâ€¢ÃÂ¨Ãâ€¢ÃÅ¡                                                                                                                                                                                                                      Ãâ€œÃÂ Ãâ€¢ÃÂ¦ÃÅ¡ÃËœÃâ„¢ ÃÅ¾ÃÂ Ãâ€¢ÃÂ¨Ãâ€¢ÃÅ¡
ÃÅ¸Ãï¿½ÃÂ Ãâ€¢Ãï¿½ÃÂ¬ ÃËœÃâ€” Ãâ€œÃÅ¾Ãâ€ºÃâ€ºÃËœÃâ€™ÃÂ£Ãâ€Ãï¿½, ÃËœÃâ€ºÃËœ Ãï¿½Ãâ€¢ÃÅ¾Ãâ€˜ÃÂ«ÃÅ¡Ãï¿½ÃÅ¾Ãâ€™Ãâ€¢Ãï¿½Ãï¿½ÃÂ«Ãâ€¢ ÃÅ¸ÃÂ ÃËœÃÅ¡Ãâ€ºÃÂ®ÃÂ§Ãâ€¢Ãï¿½ÃËœÃÂ¯ Ãâ€™Ãâ€¢Ãï¿½ÃËœ Ãâ€™Ãâ€¢Ãâ€”ÃÂ£Ãï¿½ÃÂ§ÃËœÃÅ¡Ãï¿½ ÃÅ¸Ãï¿½ÃÂ Ãâ€¢Ãï¿½ÃÂ¬ ÃËœÃâ€” Ãâ€œÃÅ¾Ãâ€ºÃâ€ºÃËœÃâ€™ÃÂ£Ãâ€Ãï¿½, ÃËœÃâ€ºÃËœ Ãï¿½Ãâ€¢ÃÅ¾Ãâ€˜ÃÂ«ÃÅ¡Ãï¿½ÃÅ¾Ãâ€™Ãâ€¢Ãï¿½Ãï¿½ÃÂ«Ãâ€¢ ÃÅ¸ÃÂ ÃËœÃÅ¡Ãâ€ºÃÂ®ÃÂ§Ãâ€¢Ãï¿½ÃËœÃÂ¯ Ãâ€™Ãâ€¢Ãï¿½ÃËœ Ãâ€™Ãâ€¢Ãâ€”ÃÂ£Ãï¿½ÃÂ§ÃËœÃÅ¡Ãï¿½
                                                                                                                                                                                                         Ãâ€”Ãï¿½Ãâ€œÃï¿½Ãâ€Ãï¿½Ãâ„¢ Ãâ€“Ãâ€¢Ãâ€ºÃï¿½Ãï¿½ÃËœÃâ€¢                                                                                                                                                                                                          Ãâ€”Ãï¿½Ãâ€œÃï¿½Ãâ€Ãï¿½Ãâ„¢ Ãâ€“Ãâ€¢Ãâ€ºÃï¿½Ãï¿½ÃËœÃâ€¢
                                                                                                                                                                                                                        Goodnight Brooklyn Ã¢â‚¬â€ The Story of Death by Audio                                                                                                                                                                                                                         Goodnight Brooklyn Ã¢â‚¬â€ The Story of Death by Audio
                                                                                                                                                                                                                                             ÃÂ­Ãâ€ºÃï¿½ÃÂ¡ÃÂ¢ÃËœÃÅ¡ÃÅ¾                                                                                                                                                                                                                                              ÃÂ­Ãâ€ºÃï¿½ÃÂ¡ÃÂ¢ÃËœÃÅ¡ÃÅ¾
                                                                                                                                                                                                                                                          ÃÅ“ÃÅ¾Ãâ€ºÃÅ¾ÃÂ¢                                                                                                                                                                                                                                                           ÃÅ“ÃÅ¾Ãâ€ºÃÅ¾ÃÂ¢
                                                                                                                                                                   ÃÂ¡ÃËœÃï¿½Ãâ€Ãâ€˜Ãï¿½Ãâ€: ÃÅ¸ÃËœÃÂ Ãï¿½ÃÂ¢ÃÂ« ÃÂ¡Ãâ€¢ÃÅ“ÃËœ ÃÂ¨ÃÂ¢ÃÅ¾ÃÂ ÃÅ“ÃÅ¾Ãâ€™                                                                                                                                                                    ÃÂ¡ÃËœÃï¿½Ãâ€Ãâ€˜Ãï¿½Ãâ€: ÃÅ¸ÃËœÃÂ Ãï¿½ÃÂ¢ÃÂ« ÃÂ¡Ãâ€¢ÃÅ“ÃËœ ÃÂ¨ÃÂ¢ÃÅ¾ÃÂ ÃÅ“ÃÅ¾Ãâ€™
                                                                                                                                                                                                                                   VanishedÃ¢â‚¬â€Left Behind: Next Generation                                                                                                                                                                                                                                    VanishedÃ¢â‚¬â€Left Behind: Next Generation
                                                                                                                                                                                                                                                        Ãƒâ€tez-moi d'un Doute                                                                                                                                                                                                                                                         Ãƒâ€tez-moi d'un Doute
                                                                                                                                                                                           Ponokku tanpen gekijÃƒÂ´: Chiisa na eiyÃƒÂ»Ã¢â‚¬â€Kani to tamago to tÃƒÂ´mei ningen                                                                                                                                                                                            Ponokku tanpen gekijÃƒÂ´: Chiisa na eiyÃƒÂ»Ã¢â‚¬â€Kani to tamago to tÃƒÂ´mei ningen
                                                                                                                                                                                                                                                     ÃÂ¡ÃÅ¸Ãï¿½ÃÂ ÃÂ¢Ãï¿½                                                                                                                                                                                                                                                      ÃÂ¡ÃÅ¸Ãï¿½ÃÂ ÃÂ¢Ãï¿½
                                                                                                                                                                                                                         Ãï¿½ÃÅ¾ÃÂ§Ãï¿½ÃÂ«Ãâ€¢ ÃÂ¡ÃÂ¢ÃÂ Ãï¿½Ãâ€“ÃËœ                                                                                                                                                                                                                          Ãï¿½ÃÅ¾ÃÂ§Ãï¿½ÃÂ«Ãâ€¢ ÃÂ¡ÃÂ¢ÃÂ Ãï¿½Ãâ€“ÃËœ
                                                                                                                                                                                                                     ÃÅ¸ÃÂ ÃÅ¾ÃÂ¡ÃÂ¢Ãï¿½ÃÂ¯ ÃËœÃÂ¡ÃÂ¢ÃÅ¾ÃÂ ÃËœÃÂ¯                                                                                                                                                                                                                      ÃÅ¸ÃÂ ÃÅ¾ÃÂ¡ÃÂ¢Ãï¿½ÃÂ¯ ÃËœÃÂ¡ÃÂ¢ÃÅ¾ÃÂ ÃËœÃÂ¯
                                                                                                                                                                                                                                             Mission: ImpossibleÃ¢â‚¬â€Fallout                                                                                                                                                                                                                                              Mission: ImpossibleÃ¢â‚¬â€Fallout
                                                                                                                                                                                                                                          Pope FrancisÃ¢â‚¬â€A Man of His Word                                                                                                                                                                                                                                           Pope FrancisÃ¢â‚¬â€A Man of His Word
                                                                                                                                                                                                                                              AndronÃ¢â‚¬â€The Black Labyrinth                                                                                                                                                                                                                                               AndronÃ¢â‚¬â€The Black Labyrinth
                                                                                                                                                                                                                                        Mission: ImpossibleÃ¢â‚¬â€Rogue Nation                                                                                                                                                                                                                                         Mission: ImpossibleÃ¢â‚¬â€Rogue Nation
                                                                                                                                                                                                                                           Buena Vista Social ClubÃ¢â‚¬â€Adios                                                                                                                                                                                                                                            Buena Vista Social ClubÃ¢â‚¬â€Adios
                                                                                                                                                                                                                                      Mission: ImpossibleÃ¢â‚¬â€Ghost Protocol                                                                                                                                                                                                                                       Mission: ImpossibleÃ¢â‚¬â€Ghost Protocol
                                                                                                                                                                                                                                                Northmen Ã¢â‚¬â€ A Viking Saga                                                                                                                                                                                                                                                 Northmen Ã¢â‚¬â€ A Viking Saga
                                                                                                                                                                                                               ÃÅ“Ãï¿½ÃÂ ÃÂ¨ÃÂ ÃÂ£ÃÂ¢ ÃÅ¸ÃÅ¾ÃÂ¡ÃÂ¢ÃÂ ÃÅ¾Ãâ€¢Ãï¿½                                                                                                                                                                                                                ÃÅ“Ãï¿½ÃÂ ÃÂ¨ÃÂ ÃÂ£ÃÂ¢ ÃÅ¸ÃÅ¾ÃÂ¡ÃÂ¢ÃÂ ÃÅ¾Ãâ€¢Ãï¿½
                                                                                                                                                                                                                                                              Ãƒâ€hi no yakata                                                                                                                                                                                                                                                               Ãƒâ€hi no yakata
                                                                                                                                                                                                                                                               Ãƒâ€bÃƒÂ¢ Fensu                                                                                                                                                                                                                                                                Ãƒâ€bÃƒÂ¢ Fensu
                                                                                                                                                                                                              GekijÃƒÂ´ban Urutoraman Ãƒâ€bu: Kizuna no chikara, okarishimasu!                                                                                                                                                                                                               GekijÃƒÂ´ban Urutoraman Ãƒâ€bu: Kizuna no chikara, okarishimasu!
                                                                                                                                                                                                                                         Ritual Ã¢â‚¬â€ Una storia psicomagica                                                                                                                                                                                                                                          Ritual Ã¢â‚¬â€ Una storia psicomagica
                                                                                                                                                                                                                         GekijÃƒÂ´-ban Kamen RaidÃƒÂ¢ Den-Ãƒâ€: Ore, tanjÃƒÂ´!                                                                                                                                                                                                                          GekijÃƒÂ´-ban Kamen RaidÃƒÂ¢ Den-Ãƒâ€: Ore, tanjÃƒÂ´!
                                                                                                                                                                             Vince VaughnÃ¢â‚¬â„¢s Wild West Comedy Show: 30 Days & 30 NightsÃ¢â‚¬â€Hollywood to the Heartland                                                                                                                                                                              Vince VaughnÃ¢â‚¬â„¢s Wild West Comedy Show: 30 Days & 30 NightsÃ¢â‚¬â€Hollywood to the Heartland
                                                                                                                                                                                                                                            Chaddr Ã¢â‚¬â€ Unter uns der Fluss                                                                                                                                                                                                                                             Chaddr Ã¢â‚¬â€ Unter uns der Fluss
                                                                                                                                                                                                                            John Fogerty: 50 Year TripÃ¢â‚¬â€Live at Red Rocks                                                                                                                                                                                                                             John Fogerty: 50 Year TripÃ¢â‚¬â€Live at Red Rocks
                                                                                                                                                                                                                                Storia di B. Ã¢â‚¬â€ La scomparsa di mia madre                                                                                                                                                                                                                                 Storia di B. Ã¢â‚¬â€ La scomparsa di mia madre
                                                                                                                                                                                                                   Kimetsu no Yaiba: Hashira Gou Kaigi Ã¢â‚¬â€ Chouyashiki Hen                                                                                                                                                                                                                    Kimetsu no Yaiba: Hashira Gou Kaigi Ã¢â‚¬â€ Chouyashiki Hen
                                                                                                                                                                                                                                                      Gulyay, Vasya! Ã¢â‚¬â€ 2                                                                                                                                                                                                                                                       Gulyay, Vasya! Ã¢â‚¬â€ 2
                                                                                                                                                                                                                                Passion Ã¢â‚¬â€ Between Revolt and Resignation                                                                                                                                                                                                                                 Passion Ã¢â‚¬â€ Between Revolt and Resignation

In [104]:
# Check whether the ftfy package is installed
import importlib.util

print(importlib.util.find_spec("ftfy"))

None

In [106]:
# Install ftfy in the current Python environment
%pip install ftfy

Collecting ftfy
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: wcwidth in /opt/anaconda3/envs/ai_dev/lib/python3.10/site-packages (from ftfy) (0.8.2)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
Installing collected packages: ftfy
Successfully installed ftfy-6.3.1
Note: you may need to restart the kernel to use updated packages.

In [107]:
# Import ftfy and test it on the 83 difficult titles
from ftfy import fix_text

# Apply ftfy to the titles that the previous method could not repair
advanced_repaired = not_repaired["original"].apply(fix_text)

# Compare the original and repaired titles
advanced_comparison = pd.DataFrame({
    "original": not_repaired["original"],
    "repaired": advanced_repaired
})

print(advanced_comparison.to_string(index=False))

                                                                                                                                                                                                                                                                       original                                                                             repaired
                                                                                                                                                                                                                 ÃÅ¡Ãï¿½Ãâ€™ÃÅ¡Ãï¿½Ãâ€”ÃÂ¡ÃÅ¡ÃÅ¾Ãâ€¢ ÃÂ¢ÃÂ ÃËœÃÅ¾                                                                      К�ВК�ЗСКОЕ ТРИО
                                                                                                                                                                                                              Ãâ€˜Ãï¿½Ãâ€˜Ãï¿½ ÃÂ¯Ãâ€œÃï¿½. Ãï¿½Ãï¿½ÃÂ§Ãï¿½Ãâ€ºÃÅ¾                                                                     Б�Б� ЯГ�. ��Ч�ЛО
                                                                                                                                                                                                                     Ãâ€œÃÂ Ãâ€¢ÃÂ¦ÃÅ¡ÃËœÃâ„¢ ÃÅ¾ÃÂ Ãâ€¢ÃÂ¨Ãâ€¢ÃÅ¡                                                                       ГРЕЦКИЙ ОРЕШЕК
ÃÅ¸Ãï¿½ÃÂ Ãâ€¢Ãï¿½ÃÂ¬ ÃËœÃâ€” Ãâ€œÃÅ¾Ãâ€ºÃâ€ºÃËœÃâ€™ÃÂ£Ãâ€Ãï¿½, ÃËœÃâ€ºÃËœ Ãï¿½Ãâ€¢ÃÅ¾Ãâ€˜ÃÂ«ÃÅ¡Ãï¿½ÃÅ¾Ãâ€™Ãâ€¢Ãï¿½Ãï¿½ÃÂ«Ãâ€¢ ÃÅ¸ÃÂ ÃËœÃÅ¡Ãâ€ºÃÂ®ÃÂ§Ãâ€¢Ãï¿½ÃËœÃÂ¯ Ãâ€™Ãâ€¢Ãï¿½ÃËœ Ãâ€™Ãâ€¢Ãâ€”ÃÂ£Ãï¿½ÃÂ§ÃËœÃÅ¡Ãï¿½                   П�РЕ�Ь ИЗ ГОЛЛИВУД�, ИЛИ �ЕОБЫК�ОВЕ��ЫЕ ПРИКЛЮЧЕ�ИЯ ВЕ�И ВЕЗУ�ЧИК�
                                                                                                                                                                                                         Ãâ€”Ãï¿½Ãâ€œÃï¿½Ãâ€Ãï¿½Ãâ„¢ Ãâ€“Ãâ€¢Ãâ€ºÃï¿½Ãï¿½ÃËœÃâ€¢                                                                      З�Г�Д�Й ЖЕЛ��ИЕ
                                                                                                                                                                                                                        Goodnight Brooklyn Ã¢â‚¬â€ The Story of Death by Audio                                     Goodnight Brooklyn — The Story of Death by Audio
                                                                                                                                                                                                                                             ÃÂ­Ãâ€ºÃï¿½ÃÂ¡ÃÂ¢ÃËœÃÅ¡ÃÅ¾                                                                             ЭЛ�СТИКО
                                                                                                                                                                                                                                                          ÃÅ“ÃÅ¾Ãâ€ºÃÅ¾ÃÂ¢                                                                                МОЛОТ
                                                                                                                                                                   ÃÂ¡ÃËœÃï¿½Ãâ€Ãâ€˜Ãï¿½Ãâ€: ÃÅ¸ÃËœÃÂ Ãï¿½ÃÂ¢ÃÂ« ÃÂ¡Ãâ€¢ÃÅ“ÃËœ ÃÂ¨ÃÂ¢ÃÅ¾ÃÂ ÃÅ“ÃÅ¾Ãâ€™                                                         СИ�ДБ�Д: ПИР�ТЫ СЕМИ ШТОРМОВ
                                                                                                                                                                                                                                   VanishedÃ¢â‚¬â€Left Behind: Next Generation                                                Vanished—Left Behind: Next Generation
                                                                                                                                                                                                                                                        Ãƒâ€tez-moi d'un Doute                                                                  Ôtez-moi d'un Doute
                                                                                                                                                                                           Ponokku tanpen gekijÃƒÂ´: Chiisa na eiyÃƒÂ»Ã¢â‚¬â€Kani to tamago to tÃƒÂ´mei ningen                 Ponokku tanpen gekijô: Chiisa na eiyû—Kani to tamago to tômei ningen
                                                                                                                                                                                                                                                     ÃÂ¡ÃÅ¸Ãï¿½ÃÂ ÃÂ¢Ãï¿½                                                                               СП�РТ�
                                                                                                                                                                                                                         Ãï¿½ÃÅ¾ÃÂ§Ãï¿½ÃÂ«Ãâ€¢ ÃÂ¡ÃÂ¢ÃÂ Ãï¿½Ãâ€“ÃËœ                                                                        �ОЧ�ЫЕ СТР�ЖИ
                                                                                                                                                                                                                     ÃÅ¸ÃÂ ÃÅ¾ÃÂ¡ÃÂ¢Ãï¿½ÃÂ¯ ÃËœÃÂ¡ÃÂ¢ÃÅ¾ÃÂ ÃËœÃÂ¯                                                                      ПРОСТ�Я ИСТОРИЯ
                                                                                                                                                                                                                                             Mission: ImpossibleÃ¢â‚¬â€Fallout                                                          Mission: Impossible—Fallout
                                                                                                                                                                                                                                          Pope FrancisÃ¢â‚¬â€A Man of His Word                                                       Pope Francis—A Man of His Word
                                                                                                                                                                                                                                              AndronÃ¢â‚¬â€The Black Labyrinth                                                           Andron—The Black Labyrinth
                                                                                                                                                                                                                                        Mission: ImpossibleÃ¢â‚¬â€Rogue Nation                                                     Mission: Impossible—Rogue Nation
                                                                                                                                                                                                                                           Buena Vista Social ClubÃ¢â‚¬â€Adios                                                        Buena Vista Social Club—Adios
                                                                                                                                                                                                                                      Mission: ImpossibleÃ¢â‚¬â€Ghost Protocol                                                   Mission: Impossible—Ghost Protocol
                                                                                                                                                                                                                                                Northmen Ã¢â‚¬â€ A Viking Saga                                                             Northmen — A Viking Saga
                                                                                                                                                                                                               ÃÅ“Ãï¿½ÃÂ ÃÂ¨ÃÂ ÃÂ£ÃÂ¢ ÃÅ¸ÃÅ¾ÃÂ¡ÃÂ¢ÃÂ ÃÅ¾Ãâ€¢Ãï¿½                                                                     М�РШРУТ ПОСТРОЕ�
                                                                                                                                                                                                                                                              Ãƒâ€hi no yakata                                                                        Ôhi no yakata
                                                                                                                                                                                                                                                               Ãƒâ€bÃƒÂ¢ Fensu                                                                            Ôbâ Fensu
                                                                                                                                                                                                              GekijÃƒÂ´ban Urutoraman Ãƒâ€bu: Kizuna no chikara, okarishimasu!                           Gekijôban Urutoraman Ôbu: Kizuna no chikara, okarishimasu!
                                                                                                                                                                                                                                         Ritual Ã¢â‚¬â€ Una storia psicomagica                                                      Ritual — Una storia psicomagica
                                                                                                                                                                                                                         GekijÃƒÂ´-ban Kamen RaidÃƒÂ¢ Den-Ãƒâ€: Ore, tanjÃƒÂ´!                                            Gekijô-ban Kamen Raidâ Den-Ô: Ore, tanjô!
                                                                                                                                                                             Vince VaughnÃ¢â‚¬â„¢s Wild West Comedy Show: 30 Days & 30 NightsÃ¢â‚¬â€Hollywood to the Heartland Vince Vaughn's Wild West Comedy Show: 30 Days & 30 Nights—Hollywood to the Heartland
                                                                                                                                                                                                                                            Chaddr Ã¢â‚¬â€ Unter uns der Fluss                                                         Chaddr — Unter uns der Fluss
                                                                                                                                                                                                                            John Fogerty: 50 Year TripÃ¢â‚¬â€Live at Red Rocks                                         John Fogerty: 50 Year Trip—Live at Red Rocks
                                                                                                                                                                                                                                Storia di B. Ã¢â‚¬â€ La scomparsa di mia madre                                             Storia di B. — La scomparsa di mia madre
                                                                                                                                                                                                                   Kimetsu no Yaiba: Hashira Gou Kaigi Ã¢â‚¬â€ Chouyashiki Hen                                Kimetsu no Yaiba: Hashira Gou Kaigi — Chouyashiki Hen
                                                                                                                                                                                                                                                      Gulyay, Vasya! Ã¢â‚¬â€ 2                                                                   Gulyay, Vasya! — 2
                                                                                                                                                                                                                                Passion Ã¢â‚¬â€ Between Revolt and Resignation                                             Passion — Between Revolt and Resignation
                                                                                                                                                                                                                                  Mittendrin Ã¢â‚¬â€ Indien, Nepal & Sri Lanka                                               Mittendrin — Indien, Nepal & Sri Lanka
                                                                                                                                                                                                                                     Curveball Ã¢â‚¬â€ Wir machen die Wahrheit                                                  Curveball — Wir machen die Wahrheit
                                                                                                                                                                                                                                 Botswana Ã¢â‚¬â€ Afrikas Letztes Tierparadies                                              Botswana — Afrikas Letztes Tierparadies
                                                                                                                                                                                                                   Monster Strike the Movie: Lucifer Ã¢â‚¬â€ Zetsubou no Yoake                                Monster Strike the Movie: Lucifer — Zetsubou no Yoake
                                                                                                                                                                                                                              Michael Ball and Alfie Boe Ã¢â‚¬â€ Back Together                                           Michael Ball and Alfie Boe — Back Together
                                                                                                                                                                                                                                  Wildherz Ã¢â‚¬â€ Auf der Reise zu mir selbst                                               Wildherz — Auf der Reise zu mir selbst
                                                                                                                                                                                                                                          Me contro Te Ã¢â‚¬â€ Persi Nel Tempo                                                       Me contro Te — Persi Nel Tempo
                                                                                                                                                                                                                               Bruno Manser Ã¢â‚¬â€ Die Stimme des Regenwaldes                                            Bruno Manser — Die Stimme des Regenwaldes
                                                                                                                                                                                                                             Bob Cuspe Ã¢â‚¬â€ NÃƒÂ³s NÃƒÂ£o Gostamos de Gente                                                Bob Cuspe — Nós Não Gostamos de Gente
                                                                                                                                                                                                                                               Paradise Ã¢â‚¬â€ Una nuova vita                                                            Paradise — Una nuova vita
                                                                                                                                                                                                                                 Knutsen & Ludvigsen 2 Ã¢â‚¬â€ Det store dyret                                              Knutsen & Ludvigsen 2 — Det store dyret
                                                                                                                                                                                                                                                         Acasa Ã¢â‚¬â€ My Home                                                                      Acasa — My Home
                                                                                                                                                                                                               La piazza della mia cittÃƒÂ  Ã¢â‚¬â€ Bologna e Lo Stato Sociale                               La piazza della mia città — Bologna e Lo Stato Sociale
                                                                                                                                                                                                                  Faking Bullshit Ã¢â‚¬â€ Krimineller als die Polizei erlaubt!                               Faking Bullshit — Krimineller als die Polizei erlaubt!
                                                                                                                                                                                                                       Rohe KÃ…ï¿½reporepo Ã¢â‚¬â€ The Swamp, The Sacred Place                                        Rohe K�reporepo — The Swamp, The Sacred Place
                                                                                                                                                                                                                Claudio Baglioni Ã¢â‚¬â€ In Questa Storia Che EÃ¢â‚¬â„¢ La Mia                                    Claudio Baglioni — In Questa Storia Che E' La Mia
                                                                                                                                                                                                                       That PÃƒÂ¤rt FeelingÃ¢â‚¬â€The Universe of Arvo PÃƒÂ¤rt                                          That Pärt Feeling—The Universe of Arvo Pärt
                                                                                                                                                                                                     Gekijouban Fate/Stay Night: HeavenÃ¢â‚¬â„¢s Feel Ã¢â‚¬â€ III. Spring Song                         Gekijouban Fate/Stay Night: Heaven's Feel — III. Spring Song
                                                                                                                                                                                                                                    Family Reunion Dlnner Ã¢â‚¬â€ A Ljttle Boy                                                 Family Reunion Dlnner — A Ljttle Boy
                                                                                                                                                                                                                                       John Wick: Chapter 3 Ã¢â‚¬â€ Parabellum                                                    John Wick: Chapter 3 — Parabellum

In [108]:
# Repair all suspicious movie titles using the two-step approach
def repair_movie_title(text):
    # First repair common multi-level mojibake
    text = repair_mojibake(text)

    # Then let ftfy repair remaining encoding problems
    text = fix_text(text)

    return text


# Apply the repair only to suspicious titles
suspicious_index = df1.index[
    df1["title"].astype(str).str.contains(
        mojibake_pattern,
        regex=True,
        na=False
    )
]

repaired_all = df1.loc[suspicious_index, "title"].astype(str).apply(
    repair_movie_title
)

# Update the original dataset
df1.loc[suspicious_index, "title"] = repaired_all

print("Titles processed:", len(suspicious_index))

Titles processed: 2636

In [109]:
# Check the repaired titles for replacement characters and remaining mojibake

print("Titles containing replacement character (�):")
print(
    df1["title"]
    .astype(str)
    .str.contains("�", na=False)
    .sum()
)

print("\nTitles still containing common mojibake characters:")
print(
    df1["title"]
    .astype(str)
    .str.contains(r"[ÃÂÅÆ]", regex=True, na=False)
    .sum()
)

print("\nSample of repaired titles:")
print(
    df1.loc[
        df1.index.isin(suspicious_index),
        "title"
    ].head(30).to_string(index=False)
)

Titles containing replacement character (�):
99

Titles still containing common mojibake characters:
11

Sample of repaired titles:
                                Takhté siah
    O Ano em Que Meus Pais Saíram de Férias
  Minuscule - La vallée des fourmis perdues
               Boca Juniors 3D, la película
                                     Hâmonî
          Desu nôto: Light Up the New World
                     Nuo Lietuvos nepabėgsi
                        Père fils thérapie!
          Doktor Martin: Záhada v Beskydech
                             Tiempo después
                        Tarp mūsų mergai�ių
                                    Trileçe
                      Müsaadenizle Büyükler
                                       Börü
                Un violent désir de bonheur
                             L'homme fidèle
                                Yanımda Kal
      Kamen Raidâ Heisei Jenerêshonzu Foebâ
                                  Sükut Evi
                        Kurtlar ve Çakallar
D.P.A. Detetives Do Prédio Azul 2 - O Filme
               Aïlo: Une odyssée en Laponie
                       It's March 3Rd Again
                              Parayı Bulduk
    Klasės susitikimas: berniukai sugrįžta!
                           Fala Sério, Mãe!
                   L'échange des princesses
                               Çat Kapi Ask
                                      Caffè
                               Tout là-haut

In [110]:
# Find titles that still contain the replacement character

remaining_bad = df1[
    df1["title"].astype(str).str.contains("�", na=False)
][["title", "release_year"]]

print("Titles still containing �:", len(remaining_bad))

print(
    remaining_bad.to_string(index=False)
)

Titles still containing �: 99
                                                                     title  release_year
                                                       Tarp mūsų mergai�ių          2018
                                                    Kid� Senshi Gandamu NT          2018
                                     Mimi a Líza: Záhada viano�ného svetla          2018
                                                               Djon �frica          2018
                                                           К�ВК�ЗСКОЕ ТРИО          2016
                                                          Б�Б� ЯГ�. ��Ч�ЛО          2018
                                                             Bureibusut�mu          2017
        П�РЕ�Ь ИЗ ГОЛЛИВУД�, ИЛИ �ЕОБЫК�ОВЕ��ЫЕ ПРИКЛЮЧЕ�ИЯ ВЕ�И ВЕЗУ�ЧИК�          2018
                                                           З�Г�Д�Й ЖЕЛ��ИЕ          2016
                                                     El �rbol de la sangre          2018
      Kaettekita D�butsu Sentai Jū�j� Oinochi Ch�dai! Chikyū Ōja Ketteisen          2017
                                                                  ЭЛ�СТИКО          2016
                                                   Free� -Take Your Marks-          2017
                                                           Bratří�ek Karel          2016
                                  IMT Smile and Lú�nica - Made in Slovakia          2016
                                                                    Me�iar          2017
                                              СИ�ДБ�Д: ПИР�ТЫ СЕМИ ШТОРМОВ          2016
                                                                    �nimas          2018
                                                        Ostravak OSTRAVSK�          2016
                                                                  A �rvore          2018
                                                             K�ng ti�n liè          2017
                                                         Po �em muži touží          2018
                                                �ndice Médio de Felicidade          2017
                                                                    СП�РТ�          2016
                                                             �ОЧ�ЫЕ СТР�ЖИ          2016
                                                                  Křižá�ek          2017
                                                           ПРОСТ�Я ИСТОРИЯ          2016
                                                                  U�itelka          2016
                                                       Míng Yuè J� Shí Yǒu          2017
                                 Eiga Shimajir�: Mah� no Shima no Daib�ken          2018
                                                         Všetko �o mám rád          2016
                                                    Beiburēdo b�suto goddo          2017
                               Eiga Y�kai Wotchi Tanj� no Himitsu da Nyan!          2015
                                                                    Dub�ek          2018
                                                         Ch�i dàn zhu�nji�          2017
                                              Jak básníci �ekají na zázrak          2016
                             Gekij�-ban Kuroshitsuji: Book of the Atlantic          2017
                                                          М�РШРУТ ПОСТРОЕ�          2016
                                                                     AG�VA          2016
                                                     Purikyua Sūp� Sut�zu!          2018
                                                         Hu�n yuè x�jù rén          2017
                                                                 Piata lo�          2017
                                              Eiga Purikyua Dorīmu Sut�zu!          2017
                                        Bung� Sutorei Doggusu Deddo Appuru          2018
                                                                 Tlumo�ník          2018
                                                   Mǎ gé lì tè de chūnti�n          2017
                                                        Dié xian gu� tán 2          2017
                                                         Jīnghún xiùhu�xié          2017
                                                       Ve�ne Tvoja Neverná          2018
                    Meitantei Conan: Epis�do Wan - Chiisakunatta Meitantei          2017
                                                  Mladi levi: Polnost �asa          2017
                       Kureyon Shinchan: bakauma� B-kyū gurume sabaibaru!!          2013
                                                          Všetko alebo ni�          2017
D�butsu Sentai Jū�j� Tai Ninninj� Mirai kara no Messēji Furomu Sūp� Sentai          2017
                                                                  � Deriva          2009
                                           Doragon B�ru Zetto Kami to Kami          2013
                Eiga Doraemon Nobita to Kiseki no Shima 〜Animaru Adobench�          2012
Gekij�ban Poketto Monsut� Adobansu Jenerēshon Rekkū no H�monsha Deokishisu          2004
                                        Doraemon Nobita no Taiy�� Densetsu          2021
                          Boku no Hīr� Akademia The Movie Hīr�zu: Raijingu          2019
         Eiga Y�kai Wotchi Jamu: Y�kai Gakuen Y - Neko wa Hīr� ni Nareruka          2019
                                                 Voda �o ma drží nad vodou          2019
                                                        Xiǎo xiàng guǎnji�          2019
                                                       Román pro pokro�ilé          2019
                                                           Nabarvené ptá�e          2019
                                                         Svetozár Stra�ina          2019
                                                             Kto je �alší?          2019
                                                            Hodinářův u�eň          2019
                                                        �ngeles con espada          2020
                          Los �ngeles Azules de Buenos Aires para el Mundo          2020
                                                Doragon Kuesuto Yua Sut�rī          2019
                                             yí gè nǚ hái hé t� de mì fēng          2021
                                                         zh�ng de y�u líng          2021
                                                            Loli paradi�ka          2019
                                          O �ertovi a jiné váno�ní pohádky          2021
                                             Maša i Medve�: Mašiny pesenki          2020
                                                          Uzly a pomeran�e          2019
                                                         Ar put�m uz Lūp�m          2019
                             Rohe K�reporepo — The Swamp, The Sacred Place          2021
                                                         Láska na špi�kách          2021
                                       K�tetsuj� no Kabaneri: Unato Kessen          2019
                                                                Pered�utťa          2021
                                                                   Ve�írek          2021
                                                                       �ga          2019
                                                   Dení�ek moderního fotra          2021
                                              Prvok, Šampón, Te�ka a Karel          2021
                                     Jan Werich: Když už �lověk jednou je…          2021
                                         Gump - pes, který nau�il lidi žít          2021
                                                        Chlap na střída�ku          2020
                                                     Muž so zaja�ími ušami          2021
                                                         Xīn x�jù zhī wáng          2019
                                                       Shéntàn pús�ng líng          2019
                                                           Tichý spole�ník          2021
                                         Laisvo elgesio mo�iutė 3. Pradžia          2021
                                      Gervasio Sánchez. �lbum de posguerra          2021
                         Gekij�ban Bish�jo Senshi Sēr� Mūn Et�naru: Part 2          2021
                                   Wú Jiàn Xíng Zhě Zhī Shēng D� Qián Xíng          2021
                                                   Kurenai no Shūgakuryok�          2021
                         Gekij�ban Bish�jo Senshi Sēr� Mūn Et�naru: Part 1          2021

In [111]:
# Test whether a different repair sequence can recover the 99 damaged titles

def second_repair(text):
    try:
        # Try another round of Windows-1252 to UTF-8 repair
        repaired = text.encode("cp1252").decode("utf-8")
        
        # Only accept the result if it does not introduce replacement characters
        if "�" not in repaired:
            return repaired
        
    except (UnicodeEncodeError, UnicodeDecodeError):
        pass

    return text


# Get the 99 titles that still contain replacement characters
remaining_bad = df1[
    df1["title"].astype(str).str.contains("�", na=False)
].copy()

# Test the alternative repair
second_results = remaining_bad["title"].astype(str).apply(second_repair)

# Show only titles that changed
changed_second = second_results != remaining_bad["title"].astype(str)

print("Titles repaired by second attempt:", changed_second.sum())

print(
    pd.DataFrame({
        "original": remaining_bad.loc[changed_second, "title"],
        "repaired": second_results[changed_second]
    }).to_string(index=False)
)

Titles repaired by second attempt: 0
Empty DataFrame
Columns: [original, repaired]
Index: []

In [112]:
# Check whether the damaged titles from File 1 have a matching title in File 2

remaining_bad = df1[
    df1["title"].astype(str).str.contains("�", na=False)
].copy()

# Create a simple title-year lookup from File 2
df2_lookup = df2[["title", "release_year"]].dropna().copy()

# Show the damaged File 1 titles
# together with possible File 2 titles from the same release year
for _, row in remaining_bad.iterrows():
    year = row["release_year"]
    title = row["title"]
    
    candidates = df2_lookup[
        df2_lookup["release_year"] == year
    ]["title"].dropna().tolist()
    
    print(f"\nFile 1: {title} ({year})")
    print("File 2 candidates:")
    print(candidates[:20])

File 1: Tarp mūsų mergai�ių (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: Kid� Senshi Gandamu NT (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: Mimi a Líza: Záhada viano�ného svetla (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: Djon �frica (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: К�ВК�ЗСКОЕ ТРИО (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: Б�Б� ЯГ�. ��Ч�ЛО (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: Bureibusut�mu (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: П�РЕ�Ь ИЗ ГОЛЛИВУД�, ИЛИ �ЕОБЫК�ОВЕ��ЫЕ ПРИКЛЮЧЕ�ИЯ ВЕ�И ВЕЗУ�ЧИК� (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: З�Г�Д�Й ЖЕЛ��ИЕ (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: El �rbol de la sangre (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: Kaettekita D�butsu Sentai Jū�j� Oinochi Ch�dai! Chikyū Ōja Ketteisen (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: ЭЛ�СТИКО (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: Free� -Take Your Marks- (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: Bratří�ek Karel (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: IMT Smile and Lú�nica - Made in Slovakia (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: Me�iar (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: СИ�ДБ�Д: ПИР�ТЫ СЕМИ ШТОРМОВ (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: �nimas (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: Ostravak OSTRAVSK� (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: A �rvore (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: K�ng ti�n liè (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: Po �em muži touží (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: �ndice Médio de Felicidade (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: СП�РТ� (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: �ОЧ�ЫЕ СТР�ЖИ (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: Křižá�ek (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: ПРОСТ�Я ИСТОРИЯ (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: U�itelka (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: Míng Yuè J� Shí Yǒu (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: Eiga Shimajir�: Mah� no Shima no Daib�ken (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: Všetko �o mám rád (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: Beiburēdo b�suto goddo (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: Eiga Y�kai Wotchi Tanj� no Himitsu da Nyan! (2015)
File 2 candidates:
['10,000 km', '1001 Grams', '1971', '24 Days', '3 1/2 Minutes, 10 Bullets', '3 Hearts', '45 Years', '5 Flights Up', '5 to 7', '52 Tuesdays', '7 Chinese Brothers', '7 Minutes', "'71", '90 Minutes in Heaven', '99 Homes', 'A Borrowed Identity', 'A Brave Heart: The Lizzie Velasquez Story', 'A Brilliant Young Mind', 'A Gay Girl in Damascus: The Amina Profile', 'A Girl Like Her']

File 1: Dub�ek (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: Ch�i dàn zhu�nji� (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: Jak básníci �ekají na zázrak (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: Gekij�-ban Kuroshitsuji: Book of the Atlantic (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: М�РШРУТ ПОСТРОЕ� (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: AG�VA (2016)
File 2 candidates:
['10 Cloverfield Lane', '11 Minutes', '13 Hours: The Secret Soldiers of Benghazi', '13th', '20th Century Women', '31', '4th Man Out', 'A Bigger Splash', 'A Country Called Home', 'A Family Affair', 'A Hologram for the King', 'A Kind of Murder', 'A Man Called Ove', 'A Monster Calls', 'A Monster with a Thousand Heads', 'A Perfect Day', 'A Space Program', 'A Street Cat Named Bob', 'A Tale of Love and Darkness', 'A War']

File 1: Purikyua Sūp� Sut�zu! (2018)
File 2 candidates:
['12 Strong', '1985', '211', '22 July', '24 Frames', '306 Hollywood', '40 Years in the Making: The Magic Music Movie', '6 Balloons', '7 Days in Entebbe', 'A Bag of Marbles', 'A Bread Factory Part One: For the Sake of Gold', 'A Bread Factory Part Two: Walk With Me a While', 'A Ciambra', 'A Crooked Somebody', 'A Futile and Stupid Gesture', 'A Happening of Monumental Proportions', 'A Kid Like Jake', "A Midsummer Night's Dream", 'A Prayer Before Dawn', 'A Private War']

File 1: Hu�n yuè x�jù rén (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: Piata lo� (2017)
File 2 candidates:
['100 Streets', '11/8/16', '13 Minutes', '1922', '1945', '3 Generations', '4 Days in France', '47 Meters Down', '6 Days', '78/52: Hitchcockâ\x80\x99s Shower Scene', 'A Bad Moms Christmas', 'A Cure for Wellness', "A Dog's Purpose", 'A Family Man', 'A Fantastic Woman', 'A Ghost Story', 'A Gray State', 'A Quiet Passion', 'A River Below', 'A Silent Voice']

File 1: Eiga Purikyua Dorīmu Sut�zu! (2017)
File 2 candidates:

In [113]:
# Check one damaged title against File 2 using movie_key

row = df1[
    df1["title"].astype(str).str.contains(
        "Tarp",
        na=False
    )
].iloc[0]

print("File 1 title:", row["title"])
print("File 1 movie_key:", row["movie_key"])

print("\nMatching File 2 records:")

print(
    df2[
        df2["movie_key"] == row["movie_key"]
    ][["title", "movie_key"]].to_string(index=False)
)

File 1 title: Tarp mūsų mergai�ių
File 1 movie_key: tarp mãâsãâ³ mergaiãï½iãâ³_2018

Matching File 2 records:
Empty DataFrame
Columns: [title, movie_key]
Index: []

In [114]:
# List Excel and CSV files in the current folder

import os

files = [
    f for f in os.listdir()
    if f.lower().endswith((".csv", ".xlsx", ".xls"))
]

print("\n".join(files))

movies_file1_file2_final.csv
merged_movies_clean.csv
~$movies_file1_file2_final.xlsx
movies_file1_file2_final.xlsx

In [115]:
# Load the previously saved clean movie dataset

import pandas as pd

clean_data = pd.read_csv("merged_movies_clean.csv")

print("Rows:", len(clean_data))
print("Columns:", len(clean_data.columns))
print("\nColumns:")
print(clean_data.columns.tolist())

print("\nSample titles:")
print(clean_data["title"].head(10).to_string(index=False))

Rows: 8129
Columns: 29

Columns:
['release_year', 'release_date_file1', 'title_file1', 'genre_file1', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime_file1', 'keywords', 'creative_type', 'url_file1', 'movie_key', 'url_file2', 'title_file2', 'studio', 'rating', 'runtime_file2', 'cast', 'director', 'genre_file2', 'summary', 'awards', 'metascore', 'userscore', 'release_date_file2']

Sample titles:

KeyError: 'title'

In [116]:
# Check whether the previously saved dataset contains the original damaged titles

print("Titles containing replacement character (�):")

print(
    clean_data["title_file1"]
    .astype(str)
    .str.contains("�", na=False)
    .sum()
)

print("\nSample titles:")

print(
    clean_data["title_file1"]
    .head(10)
    .to_string(index=False)
)

Titles containing replacement character (�):
0

Sample titles:
                          Antitrust
                           Santitos
                 A Walk to Remember
         The Killing of John Lennon
                          Mad Money
                 Over Her Dead Body
              The Other Boleyn Girl
                             Pariah
                          War Horse
Extremely Loud and Incredibly Close

In [117]:
# Restore the original clean titles and movie keys from the saved dataset

# Create a lookup table using the original movie keys
title_lookup = clean_data[
    ["movie_key", "title_file1"]
].drop_duplicates("movie_key")

# Restore the original title in df1
df1 = df1.drop(columns=["title"], errors="ignore")

df1 = df1.merge(
    title_lookup,
    on="movie_key",
    how="left"
)

# Rename the restored title column
df1 = df1.rename(columns={"title_file1": "title"})

# Check the result
print("Rows:", len(df1))
print("Titles restored:", df1["title"].notna().sum())
print("Titles containing �:", df1["title"].astype(str).str.contains("�", na=False).sum())

Rows: 30612
Titles restored: 8129
Titles containing �: 0

In [118]:
# Check the current structure of df1

print(df1.columns.tolist())
print("\nMissing titles:", df1["title"].isna().sum())

['release_year', 'release_date', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url', 'title_clean', 'movie_key', 'title']

Missing titles: 22483

In [119]:
# Restore the repaired titles for rows that became missing

# Recreate the repaired titles for all suspicious rows
repaired_titles = suspicious_index.to_series().map(
    dict(zip(
        suspicious_index,
        repaired_all
    ))
)

# Fill only the missing titles
df1["title"] = df1["title"].fillna(
    repaired_titles
)

# Check the result
print("Total rows:", len(df1))
print("Missing titles:", df1["title"].isna().sum())
print(
    "Titles containing �:",
    df1["title"].astype(str).str.contains("�", na=False).sum()
)

Total rows: 30612
Missing titles: 19847
Titles containing �: 99

In [120]:
# List Excel and CSV files in the current folder

import os

files = [
    file for file in os.listdir()
    if file.endswith((".csv", ".xlsx", ".xls"))
]

print("\n".join(files))

movies_file1_file2_final.csv
merged_movies_clean.csv
~$movies_file1_file2_final.xlsx
movies_file1_file2_final.xlsx

In [121]:
# Check the current title columns in merged_all

print(merged_all.columns.tolist())

print("\nMissing File 1 titles:")
print(merged_all["title_file1"].isna().sum())

['movie_id', 'release_year_file1', 'release_date_file1', 'title_file1', 'genre_file1', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime_file1', 'keywords', 'creative_type', 'url_file1', 'movie_key', 'url_file2', 'title_file2', 'studio', 'rating', 'runtime_file2', 'cast', 'director', 'genre_file2', 'summary', 'awards', 'metascore', 'userscore', 'release_date_file2']

Missing File 1 titles:
3243

In [122]:
# Restore File 1 titles from merged_all using the original File 1 URL

title_lookup = (
    merged_all
    .dropna(subset=["url_file1", "title_file1"])
    .drop_duplicates("url_file1")
    .set_index("url_file1")["title_file1"]
)

# Restore titles in df1 where they are currently missing
missing_mask = df1["title"].isna()

df1.loc[missing_mask, "title"] = (
    df1.loc[missing_mask, "url"]
    .map(title_lookup)
)

# Check the result
print("Total rows:", len(df1))
print("Missing titles:", df1["title"].isna().sum())
print(
    "Titles containing �:",
    df1["title"].astype(str).str.contains("�", na=False).sum()
)

Total rows: 30612
Missing titles: 8
Titles containing �: 99

In [123]:
# Display titles that still contain the replacement character

problem_titles = df1[
    df1["title"].astype(str).str.contains("�", na=False)
][["release_year", "title"]]

print("Problematic titles:", len(problem_titles))
print(problem_titles.to_string(index=False))

Problematic titles: 99
 release_year                                                                      title
         2018                                                        Tarp mūsų mergai�ių
         2018                                                     Kid� Senshi Gandamu NT
         2018                                      Mimi a Líza: Záhada viano�ného svetla
         2018                                                                Djon �frica
         2016                                                            К�ВК�ЗСКОЕ ТРИО
         2018                                                           Б�Б� ЯГ�. ��Ч�ЛО
         2017                                                              Bureibusut�mu
         2018         П�РЕ�Ь ИЗ ГОЛЛИВУД�, ИЛИ �ЕОБЫК�ОВЕ��ЫЕ ПРИКЛЮЧЕ�ИЯ ВЕ�И ВЕЗУ�ЧИК�
         2016                                                            З�Г�Д�Й ЖЕЛ��ИЕ
         2018                                                      El �rbol de la sangre
         2017       Kaettekita D�butsu Sentai Jū�j� Oinochi Ch�dai! Chikyū Ōja Ketteisen
         2016                                                                   ЭЛ�СТИКО
         2017                                                    Free� -Take Your Marks-
         2016                                                            Bratří�ek Karel
         2016                                   IMT Smile and Lú�nica - Made in Slovakia
         2017                                                                     Me�iar
         2016                                               СИ�ДБ�Д: ПИР�ТЫ СЕМИ ШТОРМОВ
         2018                                                                     �nimas
         2016                                                         Ostravak OSTRAVSK�
         2018                                                                   A �rvore
         2017                                                              K�ng ti�n liè
         2018                                                          Po �em muži touží
         2017                                                 �ndice Médio de Felicidade
         2016                                                                     СП�РТ�
         2016                                                              �ОЧ�ЫЕ СТР�ЖИ
         2017                                                                   Křižá�ek
         2016                                                            ПРОСТ�Я ИСТОРИЯ
         2016                                                                   U�itelka
         2017                                                        Míng Yuè J� Shí Yǒu
         2018                                  Eiga Shimajir�: Mah� no Shima no Daib�ken
         2016                                                          Všetko �o mám rád
         2017                                                     Beiburēdo b�suto goddo
         2015                                Eiga Y�kai Wotchi Tanj� no Himitsu da Nyan!
         2018                                                                     Dub�ek
         2017                                                          Ch�i dàn zhu�nji�
         2016                                               Jak básníci �ekají na zázrak
         2017                              Gekij�-ban Kuroshitsuji: Book of the Atlantic
         2016                                                           М�РШРУТ ПОСТРОЕ�
         2016                                                                      AG�VA
         2018                                                      Purikyua Sūp� Sut�zu!
         2017                                                          Hu�n yuè x�jù rén
         2017                                                                  Piata lo�
         2017                                               Eiga Purikyua Dorīmu Sut�zu!
         2018                                         Bung� Sutorei Doggusu Deddo Appuru
         2018                                                                  Tlumo�ník
         2017                                                    Mǎ gé lì tè de chūnti�n
         2017                                                         Dié xian gu� tán 2
         2017                                                          Jīnghún xiùhu�xié
         2018                                                        Ve�ne Tvoja Neverná
         2017                     Meitantei Conan: Epis�do Wan - Chiisakunatta Meitantei
         2017                                                   Mladi levi: Polnost �asa
         2013                        Kureyon Shinchan: bakauma� B-kyū gurume sabaibaru!!
         2017                                                           Všetko alebo ni�
         2017 D�butsu Sentai Jū�j� Tai Ninninj� Mirai kara no Messēji Furomu Sūp� Sentai
         2009                                                                   � Deriva
         2013                                            Doragon B�ru Zetto Kami to Kami
         2012                 Eiga Doraemon Nobita to Kiseki no Shima 〜Animaru Adobench�
         2004 Gekij�ban Poketto Monsut� Adobansu Jenerēshon Rekkū no H�monsha Deokishisu
         2021                                         Doraemon Nobita no Taiy�� Densetsu
         2019                           Boku no Hīr� Akademia The Movie Hīr�zu: Raijingu
         2019          Eiga Y�kai Wotchi Jamu: Y�kai Gakuen Y - Neko wa Hīr� ni Nareruka
         2019                                                  Voda �o ma drží nad vodou
         2019                                                         Xiǎo xiàng guǎnji�
         2019                                                        Román pro pokro�ilé
         2019                                                            Nabarvené ptá�e
         2019                                                          Svetozár Stra�ina
         2019                                                              Kto je �alší?
         2019                                                             Hodinářův u�eň
         2020                                                         �ngeles con espada
         2020                           Los �ngeles Azules de Buenos Aires para el Mundo
         2019                                                 Doragon Kuesuto Yua Sut�rī
         2021                                              yí gè nǚ hái hé t� de mì fēng
         2021                                                          zh�ng de y�u líng
         2019                                                             Loli paradi�ka
         2021                                           O �ertovi a jiné váno�ní pohádky
         2020                                              Maša i Medve�: Mašiny pesenki
         2019                                                           Uzly a pomeran�e
         2019                                                          Ar put�m uz Lūp�m
         2021                              Rohe K�reporepo — The Swamp, The Sacred Place
         2021                                                          Láska na špi�kách
         2019                                        K�tetsuj� no Kabaneri: Unato Kessen
         2021                                                                 Pered�utťa
         2021                                                                    Ve�írek
         2019                                                                        �ga
         2021                                                    Dení�ek moderního fotra
         2021                                               Prvok, Šampón, Te�ka a Karel
         2021                                      Jan Werich: Když už �lověk jednou je…
         2021                                          Gump - pes, který nau�il lidi žít
         2020                                                         Chlap na střída�ku
         2021                                                      Muž so zaja�ími ušami
         2019                                                          Xīn x�jù zhī wáng
         2019                                                        Shéntàn pús�ng líng
         2021                                                            Tichý spole�ník
         2021                                          Laisvo elgesio mo�iutė 3. Pradžia
         2021                                       Gervasio Sánchez. �lbum de posguerra
         2021                          Gekij�ban Bish�jo Senshi Sēr� Mūn Et�naru: Part 2
         2021                                    Wú Jiàn Xíng Zhě Zhī Shēng D� Qián Xíng
         2021                                                    Kurenai no Shūgakuryok�
         2021                          Gekij�ban Bish�jo Senshi Sēr� Mūn Et�naru: Part 1

In [124]:
# Test manual corrections for the first problematic titles

title_corrections = {
    "Tarp mūsu mergai�ių": "Tarp mūsų mergaičių",
    "Kid� Senshi Gandamu NT": "Kidō Senshi Gandamu NT",
    "Mimi a Líza: Záhada viano�ného svetla": "Mimi a Líza: Záhada vianočného svetla",
    "Djon �frica": "Djon África",
    "К�ВК�ЗСКОЕ ТРИО": "КАВКАЗСКОЕ ТРИО",
    "Б�Б� ЯГ�. ��Ч�ЛО": "БАБА ЯГА. ИГРАЧКА",
    "Bureibusut�mu": "Bureibusutāmu",
    "ЭЛ�СТИКО": "ЭЛАСТИКО",
    "Bratří�ek Karel": "Bratříček Karel",
    "Me�iar": "Mečiar"
}

# Show the proposed corrections without changing the dataset
for original, corrected in title_corrections.items():
    print(f"{original}  →  {corrected}")

Tarp mūsu mergai�ių  →  Tarp mūsų mergaičių
Kid� Senshi Gandamu NT  →  Kidō Senshi Gandamu NT
Mimi a Líza: Záhada viano�ného svetla  →  Mimi a Líza: Záhada vianočného svetla
Djon �frica  →  Djon África
К�ВК�ЗСКОЕ ТРИО  →  КАВКАЗСКОЕ ТРИО
Б�Б� ЯГ�. ��Ч�ЛО  →  БАБА ЯГА. ИГРАЧКА
Bureibusut�mu  →  Bureibusutāmu
ЭЛ�СТИКО  →  ЭЛАСТИКО
Bratří�ek Karel  →  Bratříček Karel
Me�iar  →  Mečiar

In [125]:
# Show the URLs for the problematic titles

problem_rows = df1[
    df1["title"].astype(str).str.contains("�", na=False)
][["release_year", "title", "url"]]

print(problem_rows.head(20).to_string(index=False))

 release_year                                                                title                                                                                                             url
         2018                                                  Tarp mūsų mergai�ių                                         https://www.the-numbers.com/movie/Tarp-musu-mergaiciu-(Lithuania)(2018)
         2018                                               Kid� Senshi Gandamu NT                              https://www.the-numbers.com/movie/Kido-Senshi-Gandamu-NT-(Naratibu)-(Japan)-(2018)
         2018                                Mimi a Líza: Záhada viano�ného svetla                         https://www.the-numbers.com/movie/Mimi-a-Liza-Zahada-vianocneho-svetla-(Slovakia)(2018)
         2018                                                          Djon �frica                                                  https://www.the-numbers.com/movie/Djon-Africa-(Portugal)(2018)
         2016                                                      К�ВК�ЗСКОЕ ТРИО                                            https://www.the-numbers.com/movie/Caucasian-trio-The-(Russia)-(2016)
         2018                                                     Б�Б� ЯГ�. ��Ч�ЛО                                       https://www.the-numbers.com/movie/Baba-Yaga-The-Beginning-(Russia)-(2018)
         2017                                                        Bureibusut�mu                                                         https://www.the-numbers.com/movie/Bureibusutomu-(Japan)
         2018   П�РЕ�Ь ИЗ ГОЛЛИВУД�, ИЛИ �ЕОБЫК�ОВЕ��ЫЕ ПРИКЛЮЧЕ�ИЯ ВЕ�И ВЕЗУ�ЧИК� https://www.the-numbers.com/movie/The-Guy-From-Hollywood-or-The-Unusal-Adventures-of-Veni-Lucky-(Russia)-(2018)
         2016                                                      З�Г�Д�Й ЖЕЛ��ИЕ                                                   https://www.the-numbers.com/movie/Make-A-Wish-(Russia)-(2016)
         2018                                                El �rbol de la sangre                                           https://www.the-numbers.com/movie/Arbol-de-la-sangre-El-(Spain)(2018)
         2017 Kaettekita D�butsu Sentai Jū�j� Oinochi Ch�dai! Chikyū Ōja Ketteisen   https://www.the-numbers.com/movie/Kaettekita-Dobutsu-Sentai-Jouja-Oinochi-Chodai-Chikyu-Oja-Ketteisen-(Japan)
         2016                                                             ЭЛ�СТИКО                                                              https://www.the-numbers.com/movie/Elastic-(Russia)
         2017                                              Free� -Take Your Marks-                                                  https://www.the-numbers.com/movie/Free-Take-Your-Marks-(Japan)
         2016                                                      Bratří�ek Karel                                                          https://www.the-numbers.com/movie/Bratricek-Karel-(CZ)
         2016                             IMT Smile and Lú�nica - Made in Slovakia                             https://www.the-numbers.com/movie/IMT-Smile-and-Lucnica-Made-in-Slovakia-(Slovakia)
         2017                                                               Me�iar                                                             https://www.the-numbers.com/movie/Meciar-(Slovakia)
         2016                                         СИ�ДБ�Д: ПИР�ТЫ СЕМИ ШТОРМОВ                                   https://www.the-numbers.com/movie/Sinbad-Pirates-of-the-Seven-Storms-(Russia)
         2018                                                               �nimas                                                          https://www.the-numbers.com/movie/Animas-(Spain)(2018)
         2016                                                   Ostravak OSTRAVSK�                                                       https://www.the-numbers.com/movie/Ostravak-OSTRAVSKA-(CZ)
         2018                                                             A �rvore                                                     https://www.the-numbers.com/movie/A-Arvore-(Portugal)(2018)

In [126]:
# Display all problematic titles together with their The Numbers URLs

problem_rows = df1[
    df1["title"].astype(str).str.contains("�", na=False)
][["release_year", "title", "url"]].copy()

print(problem_rows.to_string(index=False))

 release_year                                                                      title                                                                                                                  url
         2018                                                        Tarp mūsų mergai�ių                                              https://www.the-numbers.com/movie/Tarp-musu-mergaiciu-(Lithuania)(2018)
         2018                                                     Kid� Senshi Gandamu NT                                   https://www.the-numbers.com/movie/Kido-Senshi-Gandamu-NT-(Naratibu)-(Japan)-(2018)
         2018                                      Mimi a Líza: Záhada viano�ného svetla                              https://www.the-numbers.com/movie/Mimi-a-Liza-Zahada-vianocneho-svetla-(Slovakia)(2018)
         2018                                                                Djon �frica                                                       https://www.the-numbers.com/movie/Djon-Africa-(Portugal)(2018)
         2016                                                            К�ВК�ЗСКОЕ ТРИО                                                 https://www.the-numbers.com/movie/Caucasian-trio-The-(Russia)-(2016)
         2018                                                           Б�Б� ЯГ�. ��Ч�ЛО                                            https://www.the-numbers.com/movie/Baba-Yaga-The-Beginning-(Russia)-(2018)
         2017                                                              Bureibusut�mu                                                              https://www.the-numbers.com/movie/Bureibusutomu-(Japan)
         2018         П�РЕ�Ь ИЗ ГОЛЛИВУД�, ИЛИ �ЕОБЫК�ОВЕ��ЫЕ ПРИКЛЮЧЕ�ИЯ ВЕ�И ВЕЗУ�ЧИК�      https://www.the-numbers.com/movie/The-Guy-From-Hollywood-or-The-Unusal-Adventures-of-Veni-Lucky-(Russia)-(2018)
         2016                                                            З�Г�Д�Й ЖЕЛ��ИЕ                                                        https://www.the-numbers.com/movie/Make-A-Wish-(Russia)-(2016)
         2018                                                      El �rbol de la sangre                                                https://www.the-numbers.com/movie/Arbol-de-la-sangre-El-(Spain)(2018)
         2017       Kaettekita D�butsu Sentai Jū�j� Oinochi Ch�dai! Chikyū Ōja Ketteisen        https://www.the-numbers.com/movie/Kaettekita-Dobutsu-Sentai-Jouja-Oinochi-Chodai-Chikyu-Oja-Ketteisen-(Japan)
         2016                                                                   ЭЛ�СТИКО                                                                   https://www.the-numbers.com/movie/Elastic-(Russia)
         2017                                                    Free� -Take Your Marks-                                                       https://www.the-numbers.com/movie/Free-Take-Your-Marks-(Japan)
         2016                                                            Bratří�ek Karel                                                               https://www.the-numbers.com/movie/Bratricek-Karel-(CZ)
         2016                                   IMT Smile and Lú�nica - Made in Slovakia                                  https://www.the-numbers.com/movie/IMT-Smile-and-Lucnica-Made-in-Slovakia-(Slovakia)
         2017                                                                     Me�iar                                                                  https://www.the-numbers.com/movie/Meciar-(Slovakia)
         2016                                               СИ�ДБ�Д: ПИР�ТЫ СЕМИ ШТОРМОВ                                        https://www.the-numbers.com/movie/Sinbad-Pirates-of-the-Seven-Storms-(Russia)
         2018                                                                     �nimas                                                               https://www.the-numbers.com/movie/Animas-(Spain)(2018)
         2016                                                         Ostravak OSTRAVSK�                                                            https://www.the-numbers.com/movie/Ostravak-OSTRAVSKA-(CZ)
         2018                                                                   A �rvore                                                          https://www.the-numbers.com/movie/A-Arvore-(Portugal)(2018)
         2017                                                              K�ng ti�n liè                                                              https://www.the-numbers.com/movie/Kong-tian-lie-(China)
         2018                                                          Po �em muži touží                                                      https://www.the-numbers.com/movie/Po-cem-muzi-touzi-(CZ)-(2018)
         2017                                                 �ndice Médio de Felicidade                                              https://www.the-numbers.com/movie/Indice-Medio-de-Felicidade-(Portugal)
         2016                                                                     СП�РТ�                                                                    https://www.the-numbers.com/movie/Sparta-(Russia)
         2016                                                              �ОЧ�ЫЕ СТР�ЖИ                                                    https://www.the-numbers.com/movie/Guardians-of-the-Night-(Russia)
         2017                                                                   Křižá�ek                                                                      https://www.the-numbers.com/movie/Krizacek-(CZ)
         2016                                                            ПРОСТ�Я ИСТОРИЯ                                                       https://www.the-numbers.com/movie/Simple-Story-A-(Russia-2016)
         2016                                                                   U�itelka                                                                https://www.the-numbers.com/movie/Ucitelka-(slovakia)
         2017                                                        Míng Yuè J� Shí Yǒu                                                        https://www.the-numbers.com/movie/Ming-Yue-Ji-Shi-You-(China)
         2018                                  Eiga Shimajir�: Mah� no Shima no Daib�ken                                   https://www.the-numbers.com/movie/Eiga-Shimajiro-Maho-no-Shima-no-Daiboken-(Japan)
         2016                                                          Všetko �o mám rád                                                    https://www.the-numbers.com/movie/Vsetko-co-mam-rad-(1992-Slovak)
         2017                                                     Beiburēdo b�suto goddo                                              https://www.the-numbers.com/movie/Beiburedo-basuto-goddo-(Japan)-(2017)
         2015                                Eiga Y�kai Wotchi Tanj� no Himitsu da Nyan!                          https://www.the-numbers.com/movie/Eiga-Yokai-Wotchi-Tanjo-no-Himitsu-da-Nyan-(Japan)-(2014)
         2018                                                                     Dub�ek                                                                  https://www.the-numbers.com/movie/Dubcek-(Slovakia)
         2017                                                          Ch�i dàn zhu�nji�                                                      https://www.the-numbers.com/movie/Chai-dan-zhuanjia-(Hong-Kong)
         2016                                               Jak básníci �ekají na zázrak                                                https://www.the-numbers.com/movie/Jak-basnici-ekaji-na-zazrak-(Czech)
         2017                              Gekij�-ban Kuroshitsuji: Book of the Atlantic                               https://www.the-numbers.com/movie/Gekijo-ban-Kuroshitsuji-Book-of-the-Atlantic-(Japan)
         2016                                                           М�РШРУТ ПОСТРОЕ�                                                                 https://www.the-numbers.com/movie/The-Route-is-Built
         2016                                                                      AG�VA                                                                              https://www.the-numbers.com/movie/AGAVA
         2018                                                      Purikyua Sūp� Sut�zu!                                                       https://www.the-numbers.com/movie/Purikyua-Supa-Sutazu-(Japan)
         2017                                                          Hu�n yuè x�jù rén                                                          https://www.the-numbers.com/movie/Huan-yue-xiju-ren-(China)
         2017                                                                  Piata lo�                                                               https://www.the-numbers.com/movie/Piata-lod-(Slovakia)
         2017                                               Eiga Purikyua Dorīmu Sut�zu!                                                  https://www.the-numbers.com/movie/Eiga-Purikyua-Dormu-Sutzu-(Japan)
         2018                                         Bung� Sutorei Doggusu Deddo Appuru                                  https://www.the-numbers.com/movie/Bungo-Sutorei-Doggusu-Deddo-Appuru-(Japan)-(2018)
         2018                                                                  Tlumo�ník                                                               https://www.the-numbers.com/movie/Tlumocnik-(Slovakia)
         2017                                                    Mǎ gé lì tè de chūnti�n                                                    https://www.the-numbers.com/movie/Ma-ge-li-te-de-chuntian-(China)
         2017                                                         Dié xian gu� tán 2                                                         https://www.the-numbers.com/movie/Die-xian-gui-tan-2-(China)
         2017                                                          Jīnghún xiùhu�xié                                                          https://www.the-numbers.com/movie/Jinghun-xiuhuaxie-(China)
         2018                                                        Ve�ne Tvoja Neverná                                                           https://www.the-numbers.com/movie/Vecne-tvoja-neverna-(CZ)
         2017                     Meitantei Conan: Epis�do Wan - Chiisakunatta Meitantei                         https://www.the-numbers.com/movie/Meitantei-Conan-Episdo-Wan-Chiisakunatta-Meitantei-(Japan)
         2017                                                   Mladi levi: Polnost �asa                                                 https://www.the-numbers.com/movie/Mladi-levi-Polnost-Casa-(Slovenia)
         2013                        Kureyon Shinchan: bakauma� B-kyū gurume sabaibaru!!                                    https://www.the-numbers.com/movie/Kureyon-Shinchan-bakauma-B-kyA-gurume-sabaibaru
         2017                                                           Všetko alebo ni�                                                        https://www.the-numbers.com/movie/Vsetko-alebo-nic-(Slovakia)
         2017 D�butsu Sentai Jū�j� Tai Ninninj� Mirai kara no Messēji Furomu Sūp� Sentai https://www.the-numbers.com/movie/Dobutsu-Sentai-Juoja-Tai-Ninninja-Mirai-kara-no-Messeji-Furomu-Supa-Sentai-(Japan)
         2009                                                                   � Deriva                                                                           https://www.the-numbers.com/movie/A-Deriva
         2013                                            Doragon B�ru Zetto Kami to Kami                                                    https://www.the-numbers.com/movie/Doragon-Boru-Zetto-Kami-to-Kami
         2012                 Eiga Doraemon Nobita to Kiseki no Shima 〜Animaru Adobench�                          https://www.the-numbers.com/movie/Eiga-Doraemon-Nobita-to-Kiseki-no-Shima-Animaru-Adobencha
         2004 Gekij�ban Poketto Monsut� Adobansu Jenerēshon Rekkū no H�monsha Deokishisu         https://www.the-numbers.com/movie/Gekijoban-Poketto-Monsuta-Adobansu-Jenereshon-Rekku-no-Homonsha-Deokishisu
         2021                                         Doraemon Nobita no Taiy�� Densetsu                                    https://www.the-numbers.com/movie/Doraemon-Nobita-no-Taiyoo-Densetsu-(2020-Japan)
         2019                           Boku no Hīr� Akademia The Movie Hīr�zu: Raijingu                            https://www.the-numbers.com/movie/Boku-no-Hiro-Akademia-The-Movie-Hirozu-Raijingu-(Japan)
         2019          Eiga Y�kai Wotchi Jamu: Y�kai Gakuen Y - Neko wa Hīr� ni Nareruka             https://www.the-numbers.com/movie/Eiga-Yokai-Wotchi-Jamu-Yokai-Gakuen-Y-Neko-wa-Hiro-ni-Nareruka-(Japan)
         2019                                                  Voda �o ma drží nad vodou                                                     https://www.the-numbers.com/movie/Voda-co-ma-drzi-nad-vodou-(CZ)
         2019                                                         Xiǎo xiàng guǎnji�                                                         https://www.the-numbers.com/movie/Xiao-xiang-guanjia-(China)
         2019                                                        Román pro pokro�ilé                                                           https://www.the-numbers.com/movie/Roman-pro-pokrocile-(CZ)
         2019                                                            Nabarvené ptá�e                                                               https://www.the-numbers.com/movie/Nabarvene-ptace-(CZ)
         2019                                                          Svetozár Stra�ina                                                       https://www.the-numbers.com/movie/Svetozar-Stracina-(Slovakia)
         2019                                                              Kto je �alší?                                                            https://www.the-numbers.com/movie/Kto-je-dalsi-(Slovakia)
         2019                                                             Hodinářův u�eň                                                                https://www.the-numbers.com/movie/Hodinaruv-ucen-(CZ)
         2020                                                         �ngeles con espada                                                    https://www.the-numbers.com/movie/Angeles-con-espada-(2020-Spain)
         2020                           Los �ngeles Azules de Buenos Aires para el Mundo                  https://www.the-numbers.com/movie/Los-Angeles-Azules-de-Buenos-Aires-para-el-Mundo-(2020-Argentina)
         2019                                                 Doragon Kuesuto Yua Sut�rī                                                 https://www.the-numbers.com/movie/Doragon-Kuesuto-Yua-Sutori-(Japan)
         2021                                              yí gè nǚ hái hé t� de mì fēng                                         https://www.the-numbers.com/movie/Yi-ge-nu-hai-he-ta-de-mi-feng-(2021-China)
         2021                                                          zh�ng de y�u líng                                                     https://www.the-numbers.com/movie/Zhong-de-you-ling-(2021-China)
         2019                                                             Loli paradi�ka                                                          https://www.the-numbers.com/movie/Loli-paradicka-(Slovakia)
         2021                                           O �ertovi a jiné váno�ní pohádky                             https://www.the-numbers.com/movie/certovi-a-jine-vanocni-pohadky-O-(2021-Czech-Republic)
         2020                                              Maša i Medve�: Mašiny pesenki                                         https://www.the-numbers.com/movie/Masa-i-Medved-Masiny-pesenki-(2020-Russia)
         2019                                                           Uzly a pomeran�e                                                              https://www.the-numbers.com/movie/Uzly-a-pomerance-(CZ)
         2019                                                          Ar put�m uz Lūp�m                                                         https://www.the-numbers.com/movie/Ar-putam-uz-Lupam-(Latvia)
         2021                              Rohe K�reporepo — The Swamp, The Sacred Place                      https://www.the-numbers.com/movie/Rohe-Koreporepo-The-Swamp-The-Sacred-Place-(2021-New-Zealand)
         2021                                                          Láska na špi�kách                                            https://www.the-numbers.com/movie/Laska-na-spickach-(2021-Czech-Republic)
         2019                                        K�tetsuj� no Kabaneri: Unato Kessen                                  https://www.the-numbers.com/movie/Kotetsujo-no-Kabaneri-Unato-Kessen-(Japan)-(2019)
         2021                                                                 Pered�utťa                                                          https://www.the-numbers.com/movie/Peredcutta-(2020-Ukraine)
         2021                                                                    Ve�írek                                                      https://www.the-numbers.com/movie/Vecirek-(2021-Czech-Republic)
         2019                                                                        �ga                                                              https://www.the-numbers.com/movie/Aga-(Bulgaria)-(2019)
         2021                                                    Dení�ek moderního fotra                                       https://www.the-numbers.com/movie/Dennik-moderneho-fotra-(2021-Czech-Republic)
         2021                                               Prvok, Šampón, Te�ka a Karel                                   https://www.the-numbers.com/movie/Prvok-Sampon-Tecka-a-Karel-(2021-Czech-Republic)
         2021                                      Jan Werich: Když už �lověk jednou je…                          https://www.the-numbers.com/movie/Jan-Werich-Kdyz-uz-clovek-jednou-je-(2021-Czech-Republic)
         2021                                          Gump - pes, který nau�il lidi žít                               https://www.the-numbers.com/movie/Gump-Pes-ktery-naucil-lidi-zit-(2021-Czech-Republic)
         2020                                                         Chlap na střída�ku                                                            https://www.the-numbers.com/movie/Chlap-na-stridacku-(CZ)
         2021                                                      Muž so zaja�ími ušami                                              https://www.the-numbers.com/movie/Muz-so-zajacimi-usami-(2021-Slovakia)
         2019                                                          Xīn x�jù zhī wáng                                                    https://www.the-numbers.com/movie/Xin-xiju-zhi-wang-(China)(2019)
         2019                                                        Shéntàn pús�ng líng                                                  https://www.the-numbers.com/movie/Shentan-pusong-ling-(China)(2019)
         2021                                                            Tichý spole�ník                                              https://www.the-numbers.com/movie/Tichy-spolecnik-(2021-Czech-Republic)
         2021                                          Laisvo elgesio mo�iutė 3. Pradžia                                  https://www.the-numbers.com/movie/Laisvo-elgesio-mociute-3-Pradzia-(2021-Lithuania)
         2021                                       Gervasio Sánchez. �lbum de posguerra                                   https://www.the-numbers.com/movie/Gervasio-Sanchez-Album-de-posguerra-(2021-Spain)
         2021                          Gekij�ban Bish�jo Senshi Sēr� Mūn Et�naru: Part 2                      https://www.the-numbers.com/movie/Gekijoban-Bishojo-Senshi-Sera-Mun-Etanaru-Part-2-(2021-Japan)

In [127]:
# Replace problematic titles using the movie slug from The Numbers URLs

import re
from urllib.parse import urlparse

problem_mask = df1["title"].astype(str).str.contains("�", na=False)

def title_from_url(url):
    # Extract the movie slug from the The Numbers URL
    slug = urlparse(url).path.split("/movie/")[-1]

    # Remove country/year information at the end of the slug
    slug = re.sub(r"-\([^)]*\)$", "", slug)

    # Convert hyphens to spaces
    title = slug.replace("-", " ")

    # Remove remaining parenthetical information
    title = re.sub(r"\([^)]*\)", "", title)

    # Clean extra spaces
    title = re.sub(r"\s+", " ", title).strip()

    return title

# Create replacement titles from the URLs
df1.loc[problem_mask, "title"] = (
    df1.loc[problem_mask, "url"].apply(title_from_url)
)

# Check the result
print("Titles replaced:", problem_mask.sum())
print(
    "Titles containing �:",
    df1["title"].astype(str).str.contains("�", na=False).sum()
)
print("\nSample:")
print(
    df1.loc[problem_mask, ["release_year", "title"]]
    .head(20)
    .to_string(index=False)
)

Titles replaced: 99
Titles containing �: 0

Sample:
 release_year                                                               title
         2018                                                 Tarp musu mergaiciu
         2018                                              Kido Senshi Gandamu NT
         2018                                Mimi a Liza Zahada vianocneho svetla
         2018                                                         Djon Africa
         2016                                                  Caucasian trio The
         2018                                             Baba Yaga The Beginning
         2017                                                       Bureibusutomu
         2018       The Guy From Hollywood or The Unusal Adventures of Veni Lucky
         2016                                                         Make A Wish
         2018                                               Arbol de la sangre El
         2017 Kaettekita Dobutsu Sentai Jouja Oinochi Chodai Chikyu Oja Ketteisen
         2016                                                             Elastic
         2017                                                Free Take Your Marks
         2016                                                     Bratricek Karel
         2016                              IMT Smile and Lucnica Made in Slovakia
         2017                                                              Meciar
         2016                                  Sinbad Pirates of the Seven Storms
         2018                                                              Animas
         2016                                                  Ostravak OSTRAVSKA
         2018                                                            A Arvore

In [128]:
# Rebuild title_clean and movie_key from the final movie titles

df1["title_clean"] = (
    df1["title"]
    .astype(str)
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "", regex=True)
    .str.strip()
)

df1["movie_key"] = (
    df1["title_clean"]
    + "_"
    + df1["release_year"].astype(str)
)

# Check the result
print(df1[["title", "title_clean", "movie_key"]].head(20).to_string(index=False))

print("\nRows:", len(df1))
print("Missing titles:", df1["title"].isna().sum())
print("Missing movie keys:", df1["movie_key"].isna().sum())

                                  title                    title_clean                           movie_key
                           Bakha Satang                    bakhasatang                    bakhasatang_2000
                              Antitrust                      antitrust                      antitrust_2001
                               Santitos                       santitos                       santitos_2000
                    Frank McKlusky C.I.                frankmckluskyci                frankmckluskyci_2002
                     A Walk to Remember                awalktoremember                awalktoremember_2002
                                Zig Zag                         zigzag                         zigzag_2002
                            Takhté siah                      takhtsiah                      takhtsiah_2002
  Angry Monk: Reflections on Tibet, The angrymonkreflectionsontibetthe angrymonkreflectionsontibetthe_2009
                       30 Years to Life                  30yearstolife                  30yearstolife_2002
             The Killing of John Lennon         thekillingofjohnlennon         thekillingofjohnlennon_2008
                              Mad Money                       madmoney                       madmoney_2008
                         Little Chenier                  littlechenier                  littlechenier_2008
                     Over Her Dead Body                overherdeadbody                overherdeadbody_2008
O Ano em Que Meus Pais Saíram de Férias  oanoemquemeuspaissaramdefrias  oanoemquemeuspaissaramdefrias_2008
                                    120                            120                            120_2008
                  The Other Boleyn Girl             theotherboleyngirl             theotherboleyngirl_2008
              A Lawyer Walks into a Bar           alawyerwalksintoabar           alawyerwalksintoabar_2008
                             La Rondine                      larondine                      larondine_2008
                Jodaeiye Nader az Simin           jodaeiyenaderazsimin           jodaeiyenaderazsimin_2011
                                 Pariah                         pariah                         pariah_2011

Rows: 30612
Missing titles: 8
Missing movie keys: 0

In [129]:
# Fill the remaining missing titles from their The Numbers URLs

missing_title_mask = df1["title"].isna()

df1.loc[missing_title_mask, "title"] = (
    df1.loc[missing_title_mask, "url"]
    .astype(str)
    .apply(title_from_url)
)

# Check the remaining missing titles
print("Missing titles:", df1["title"].isna().sum())

# Show the restored titles
print(
    df1.loc[
        missing_title_mask,
        ["release_year", "title", "url"]
    ].to_string(index=False)
)

Missing titles: 0
 release_year                           title                                                                url
         2016                        Muchenik                https://www.the-numbers.com/movie/Muchenik-(Russia)
         2015                           ERROR                  https://www.the-numbers.com/movie/(T)ERROR-(2015)
         2015 DisHonesty The Truth About Lies  https://www.the-numbers.com/movie/DisHonesty-The-Truth-About-Lies
         2009                                                       https://www.the-numbers.com/movie/(Untitled)
         2009              500 Days of Summer               https://www.the-numbers.com/movie/500-Days-of-Summer
         2019                         znajomi            https://www.the-numbers.com/movie/(Nie)znajomi-(Poland)
         2021                        Evolutie   https://www.the-numbers.com/movie/(R)Evolutie-(2021-Netherlands)
         2020              Idealnyy muzhchina https://www.the-numbers.com/movie/(NE)-Idealnyy-muzhchina-(Russia)

In [130]:
# Rebuild title_clean and movie_key from the final movie titles

df1["title_clean"] = (
    df1["title"]
    .astype(str)
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "", regex=True)
    .str.strip()
)

df1["movie_key"] = (
    df1["title_clean"]
    + "_"
    + df1["release_year"].astype(str)
)

# Check the result
print(
    df1[["title", "title_clean", "movie_key"]]
    .head(20)
    .to_string(index=False)
)

print("\nRows:", len(df1))
print("Missing titles:", df1["title"].isna().sum())
print("Missing movie keys:", df1["movie_key"].isna().sum())

                                  title                    title_clean                           movie_key
                           Bakha Satang                    bakhasatang                    bakhasatang_2000
                              Antitrust                      antitrust                      antitrust_2001
                               Santitos                       santitos                       santitos_2000
                    Frank McKlusky C.I.                frankmckluskyci                frankmckluskyci_2002
                     A Walk to Remember                awalktoremember                awalktoremember_2002
                                Zig Zag                         zigzag                         zigzag_2002
                            Takhté siah                      takhtsiah                      takhtsiah_2002
  Angry Monk: Reflections on Tibet, The angrymonkreflectionsontibetthe angrymonkreflectionsontibetthe_2009
                       30 Years to Life                  30yearstolife                  30yearstolife_2002
             The Killing of John Lennon         thekillingofjohnlennon         thekillingofjohnlennon_2008
                              Mad Money                       madmoney                       madmoney_2008
                         Little Chenier                  littlechenier                  littlechenier_2008
                     Over Her Dead Body                overherdeadbody                overherdeadbody_2008
O Ano em Que Meus Pais Saíram de Férias  oanoemquemeuspaissaramdefrias  oanoemquemeuspaissaramdefrias_2008
                                    120                            120                            120_2008
                  The Other Boleyn Girl             theotherboleyngirl             theotherboleyngirl_2008
              A Lawyer Walks into a Bar           alawyerwalksintoabar           alawyerwalksintoabar_2008
                             La Rondine                      larondine                      larondine_2008
                Jodaeiye Nader az Simin           jodaeiyenaderazsimin           jodaeiyenaderazsimin_2011
                                 Pariah                         pariah                         pariah_2011

Rows: 30612
Missing titles: 0
Missing movie keys: 0

In [131]:
# Create fresh copies of the cleaned File 1 and File 2 datasets

df1_final = df1.copy()
df2_final = df2.copy()

# Check the number of rows in both files
print("File 1 rows:", len(df1_final))
print("File 2 rows:", len(df2_final))

File 1 rows: 30612
File 2 rows: 11364

In [132]:
# Find movie keys that exist in both files

common_keys = set(df1_final["movie_key"]).intersection(
    set(df2_final["movie_key"])
)

print("Common movie keys:", len(common_keys))

Common movie keys: 1875

In [133]:
# Check File 2 titles for missing values and possible mojibake

mojibake_pattern = r"[ÃÂâ�]"

print("Missing titles:", df2_final["title"].isna().sum())

print(
    "Suspicious titles:",
    df2_final["title"]
    .astype(str)
    .str.contains(mojibake_pattern, regex=True, na=False)
    .sum()
)

print("\nExamples of suspicious titles:")
print(
    df2_final.loc[
        df2_final["title"].astype(str).str.contains(
            mojibake_pattern,
            regex=True,
            na=False
        ),
        ["title", "url"]
    ]
    .head(20)
    .to_string(index=False)
)

Missing titles: 0
Suspicious titles: 103

Examples of suspicious titles:
                                             title                                                                              url
                                        ReykjavÃ­k                                   https://www.metacritic.com/movie/101-reykjavik
                 78/52: Hitchcockâs Shower Scene                    https://www.metacritic.com/movie/7852-hitchcocks-shower-scene
                                        8 Â½ Women                                    https://www.metacritic.com/movie/8-women-2000
A Bottle in the Gaza Sea (Une bouteille Ã  la mer) https://www.metacritic.com/movie/a-bottle-in-the-gaza-sea-une-bouteille-s-la-mer
                             Ã cause d'un garÃ§on                              https://www.metacritic.com/movie/a-cause-dun-garcon
                                         AllÃ©luia                                        https://www.metacritic.com/movie/alleluia
                                           AmÃ©lie                                          https://www.metacritic.com/movie/amelie
                                         Ãon Flux                                        https://www.metacritic.com/movie/aon-flux
                    AquÃ­ y AllÃ¡ (Here and There)                        https://www.metacritic.com/movie/aqu-y-all-here-and-there
                                         AutÃ³mata                                        https://www.metacritic.com/movie/automata
                                       BabÃ­ lÃ©to                                       https://www.metacritic.com/movie/babi-leto
 Be Natural: The Untold Story of Alice Guy-BlachÃ© https://www.metacritic.com/movie/be-natural-the-untold-story-of-alice-guy-blache
                           Bicycling With MoliÃ¨re                          https://www.metacritic.com/movie/bicycling-with-molicre
                                           BonsÃ¡i                                          https://www.metacritic.com/movie/bonsai
                           Boris Without BÃ©atrice                          https://www.metacritic.com/movie/boris-without-beatrice
           BuÃ±uel in the Labyrinth of the Turtles          https://www.metacritic.com/movie/buouel-in-the-labyrinth-of-the-turtles
                          Ãa commence aujourd'hui                          https://www.metacritic.com/movie/ca-commence-aujourdhui
                                   CachÃ© (Hidden)                                    https://www.metacritic.com/movie/cache-hidden
                                    CafÃ© de Flore                                    https://www.metacritic.com/movie/caf-de-flore
                                    CafÃ© LumiÃ¨re                                    https://www.metacritic.com/movie/cafe-lumiere

In [135]:
# Remove non-English letters, numbers, and punctuation from the title
df1["title_clean"] = (
    df1["title"]
    .astype(str)
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "", regex=True)
)

In [136]:
# Check the existing clean merged dataset

print("Rows:", len(clean_data))
print("Columns:", len(clean_data.columns))

print("\nColumns:")
print(clean_data.columns.tolist())

print("\nMissing title_file1:", clean_data["title_file1"].isna().sum())

Rows: 8129
Columns: 29

Columns:
['release_year', 'release_date_file1', 'title_file1', 'genre_file1', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime_file1', 'keywords', 'creative_type', 'url_file1', 'movie_key', 'url_file2', 'title_file2', 'studio', 'rating', 'runtime_file2', 'cast', 'director', 'genre_file2', 'summary', 'awards', 'metascore', 'userscore', 'release_date_file2']

Missing title_file1: 0

In [137]:
# Create a lookup of cleaned File 1 titles using the original File 1 URLs

title_lookup = (
    df1[["url", "title"]]
    .dropna(subset=["url"])
    .drop_duplicates("url")
    .set_index("url")["title"]
)

# Check how many matched movies have a cleaned title available
matched_titles = clean_data["url_file1"].map(title_lookup)

print("Matched movies:", len(clean_data))
print("Titles found from File 1:", matched_titles.notna().sum())
print("Titles not found:", matched_titles.isna().sum())

Matched movies: 8129
Titles found from File 1: 8129
Titles not found: 0

In [138]:
# Update the File 1 titles in the existing 8,129 matched dataset

clean_data["title_file1"] = clean_data["url_file1"].map(title_lookup)

# Check the updated titles
print(
    clean_data[["title_file1", "url_file1"]]
    .head(20)
    .to_string(index=False)
)

print("\nRows:", len(clean_data))
print("Missing titles:", clean_data["title_file1"].isna().sum())

                        title_file1                                                             url_file1
                          Antitrust                           https://www.the-numbers.com/movie/Antitrust
                           Santitos                            https://www.the-numbers.com/movie/Santitos
                 A Walk to Remember                  https://www.the-numbers.com/movie/Walk-to-Remember-A
         The Killing of John Lennon          https://www.the-numbers.com/movie/Killing-of-John-Lennon-The
                          Mad Money                           https://www.the-numbers.com/movie/Mad-Money
                 Over Her Dead Body                  https://www.the-numbers.com/movie/Over-Her-Dead-Body
              The Other Boleyn Girl               https://www.the-numbers.com/movie/Other-Boleyn-Girl-The
                             Pariah                       https://www.the-numbers.com/movie/Pariah-(2011)
                          War Horse                           https://www.the-numbers.com/movie/War-Horse
Extremely Loud and Incredibly Close https://www.the-numbers.com/movie/Extremely-Loud-and-Incredibly-Close
                       Angels Crest                        https://www.the-numbers.com/movie/Angels-Crest
                   The Darkest Hour                    https://www.the-numbers.com/movie/Darkest-Hour-The
                        Miss Minoes                         https://www.the-numbers.com/movie/Miss-Minoes
                    We Bought a Zoo                     https://www.the-numbers.com/movie/We-Bought-a-Zoo
     In The Land of Blood and Honey      https://www.the-numbers.com/movie/In-The-Land-of-Blood-and-Honey
                   We Are the Giant                    https://www.the-numbers.com/movie/We-Are-the-Giant
                               Meru                                https://www.the-numbers.com/movie/Meru
                   Welcome to Leith                    https://www.the-numbers.com/movie/Welcome-to-Leith
                              Truth                        https://www.the-numbers.com/movie/Truth-(2015)
                        Point Break                https://www.the-numbers.com/movie/Point-Break-(Remake)

Rows: 8129
Missing titles: 0

In [139]:
# Get File 1 movies that are not part of the existing 8,129 matches

matched_urls = set(clean_data["url_file1"])

df1_only = df1[
    ~df1["url"].isin(matched_urls)
].copy()

print("File 1 only:", len(df1_only))
print("Matched:", len(clean_data))
print("Total File 1:", len(df1_only) + len(clean_data))

File 1 only: 22483
Matched: 8129
Total File 1: 30612

In [140]:
# Check the columns in the File 1-only dataset

print("Number of columns:", len(df1_only.columns))
print("\nColumns:")
print(df1_only.columns.tolist())

Number of columns: 17

Columns:
['release_year', 'release_date', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url', 'title_clean', 'movie_key', 'title']

In [141]:
# Rename File 1 columns to match the structure of the merged dataset

df1_only_final = df1_only.rename(columns={
    "release_date": "release_date_file1",
    "title": "title_file1",
    "genre": "genre_file1",
    "runtime": "runtime_file1",
    "url": "url_file1"
})

# Remove columns that are only needed for matching
df1_only_final = df1_only_final.drop(columns=[
    "title_clean"
])

print("Rows:", len(df1_only_final))
print("Columns:", len(df1_only_final.columns))
print(df1_only_final.columns.tolist())

Rows: 22483
Columns: 16
['release_year', 'release_date_file1', 'genre_file1', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime_file1', 'keywords', 'creative_type', 'url_file1', 'movie_key', 'title_file1']

In [142]:
# Combine File 1-only movies with the 8,129 matched movies

file1_complete = pd.concat(
    [clean_data, df1_only_final],
    ignore_index=True,
    sort=False
)

print("Rows:", len(file1_complete))
print("Columns:", len(file1_complete.columns))

print("\nMissing titles:", file1_complete["title_file1"].isna().sum())
print("Duplicate rows:", file1_complete.duplicated().sum())

Rows: 30612
Columns: 29

Missing titles: 0
Duplicate rows: 0

In [143]:
# Get File 2 movies that were not part of the existing 8,129 matches

df2_only = df2[
    ~df2["url"].isin(
        clean_data["url_file2"]
    )
].copy()

print("File 2 only:", len(df2_only))
print("Total File 2:", len(df2_only) + len(clean_data))

File 2 only: 3235
Total File 2: 11364

In [144]:
# Rename File 2 columns to match the merged dataset structure

df2_only_final = df2_only.rename(columns={
    "url": "url_file2",
    "title": "title_file2",
    "runtime": "runtime_file2",
    "genre": "genre_file2",
    "release_date": "release_date_file2"
})

# Remove columns that are only used for matching
df2_only_final = df2_only_final.drop(columns=[
    "title_clean",
    "release_year"
])

print("Rows:", len(df2_only_final))
print("Columns:", len(df2_only_final.columns))
print(df2_only_final.columns.tolist())

Rows: 3235
Columns: 14
['url_file2', 'title_file2', 'studio', 'rating', 'runtime_file2', 'cast', 'director', 'genre_file2', 'summary', 'awards', 'metascore', 'userscore', 'release_date_file2', 'movie_key']

In [145]:
# Combine all File 1 movies with File 2-only movies

merged_all = pd.concat(
    [file1_complete, df2_only_final],
    ignore_index=True,
    sort=False
)

print("Rows:", len(merged_all))
print("Columns:", len(merged_all.columns))

print("\nMissing title_file1:", merged_all["title_file1"].isna().sum())
print("Missing title_file2:", merged_all["title_file2"].isna().sum())
print("Duplicate rows:", merged_all.duplicated().sum())

Rows: 33847
Columns: 29

Missing title_file1: 3235
Missing title_file2: 22483
Duplicate rows: 0

In [146]:
# Check whether the 16 ambiguous File 2 records are already in the dataset

ambiguous_urls = set(df2_ambiguous["url"])

already_in_merged = merged_all["url_file2"].isin(ambiguous_urls).sum()

print("Ambiguous File 2 records:", len(df2_ambiguous))
print("Already in merged_all:", already_in_merged)
print("Still need to add:", len(df2_ambiguous) - already_in_merged)

Ambiguous File 2 records: 16
Already in merged_all: 16
Still need to add: 0

In [147]:
# Check the cleaned File 1 titles in the final merged dataset

print(
    merged_all[
        ["title_file1", "url_file1", "title_file2"]
    ]
    .head(20)
    .to_string(index=False)
)

print("\nRows:", len(merged_all))
print("Missing File 1 titles:", merged_all["title_file1"].isna().sum())
print("Missing File 2 titles:", merged_all["title_file2"].isna().sum())

                        title_file1                                                             url_file1                         title_file2
                          Antitrust                           https://www.the-numbers.com/movie/Antitrust                           Antitrust
                           Santitos                            https://www.the-numbers.com/movie/Santitos                            Santitos
                 A Walk to Remember                  https://www.the-numbers.com/movie/Walk-to-Remember-A                  A Walk to Remember
         The Killing of John Lennon          https://www.the-numbers.com/movie/Killing-of-John-Lennon-The          The Killing of John Lennon
                          Mad Money                           https://www.the-numbers.com/movie/Mad-Money                           Mad Money
                 Over Her Dead Body                  https://www.the-numbers.com/movie/Over-Her-Dead-Body                  Over Her Dead Body
              The Other Boleyn Girl               https://www.the-numbers.com/movie/Other-Boleyn-Girl-The               The Other Boleyn Girl
                             Pariah                       https://www.the-numbers.com/movie/Pariah-(2011)                              Pariah
                          War Horse                           https://www.the-numbers.com/movie/War-Horse                           War Horse
Extremely Loud and Incredibly Close https://www.the-numbers.com/movie/Extremely-Loud-and-Incredibly-Close Extremely Loud and Incredibly Close
                       Angels Crest                        https://www.the-numbers.com/movie/Angels-Crest                        Angels Crest
                   The Darkest Hour                    https://www.the-numbers.com/movie/Darkest-Hour-The                    The Darkest Hour
                        Miss Minoes                         https://www.the-numbers.com/movie/Miss-Minoes                         Miss Minoes
                    We Bought a Zoo                     https://www.the-numbers.com/movie/We-Bought-a-Zoo                     We Bought a Zoo
     In The Land of Blood and Honey      https://www.the-numbers.com/movie/In-The-Land-of-Blood-and-Honey      In the Land of Blood and Honey
                   We Are the Giant                    https://www.the-numbers.com/movie/We-Are-the-Giant                    We Are the Giant
                               Meru                                https://www.the-numbers.com/movie/Meru                                Meru
                   Welcome to Leith                    https://www.the-numbers.com/movie/Welcome-to-Leith                    Welcome to Leith
                              Truth                        https://www.the-numbers.com/movie/Truth-(2015)                               Truth
                        Point Break                https://www.the-numbers.com/movie/Point-Break-(Remake)                         Point Break

Rows: 33847
Missing File 1 titles: 3235
Missing File 2 titles: 22483

In [148]:
# Create a unique movie ID for every movie in the final dataset

merged_all.insert(
    0,
    "movie_id",
    range(1, len(merged_all) + 1)
)

# Verify the movie IDs
print("Rows:", len(merged_all))
print("Unique movie IDs:", merged_all["movie_id"].nunique())
print("Minimum movie ID:", merged_all["movie_id"].min())
print("Maximum movie ID:", merged_all["movie_id"].max())
print("Missing movie IDs:", merged_all["movie_id"].isna().sum())

Rows: 33847
Unique movie IDs: 33847
Minimum movie ID: 1
Maximum movie ID: 33847
Missing movie IDs: 0

In [149]:
# Final validation of the merged movie dataset

print("Total movies:", len(merged_all))
print("Unique movie IDs:", merged_all["movie_id"].nunique())

# Count movies by their source
file1_movies = merged_all["url_file1"].notna().sum()
file2_movies = merged_all["url_file2"].notna().sum()
matched_movies = (
    merged_all["url_file1"].notna()
    & merged_all["url_file2"].notna()
).sum()

print("\nFile 1 movies:", file1_movies)
print("File 2 movies:", file2_movies)
print("Matched movies:", matched_movies)

print("\nDuplicate rows:", merged_all.duplicated().sum())
print("Duplicate movie IDs:", merged_all["movie_id"].duplicated().sum())

Total movies: 33847
Unique movie IDs: 33847

File 1 movies: 30612
File 2 movies: 11364
Matched movies: 8129

Duplicate rows: 0
Duplicate movie IDs: 0

In [150]:
# Save the final merged dataset as a CSV file

merged_all.to_csv(
    "movies_file1_file2_final.csv",
    index=False
)

print("CSV file saved successfully.")

CSV file saved successfully.

In [151]:
# Save the full movie database as an Excel file

merged_all.to_excel(
    "full_movie_database.xlsx",
    index=False
)

print("Full movie database saved successfully.")

Full movie database saved successfully.

## 5. Original temporary movie-ID cells — cleaning9.22.ipynb

These two original cells are copied unchanged and placed after the movie-building section. The original comment says the ID insertion was too early to use.

In [ ]:
#this code works but its too early to use it
df1.insert(0, "movie_id", range(1, len(df1) + 1))

In [110]:
df1.drop("movie_id",axis=1)

,release_year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg_run_per_theatre,runtime,keywords,creative_type,url,title_clean,movie_key,release_date_clean,full_release_date
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...,bakha satang,bakha satang_2000,January 1,2000-01-01
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust,antitrust,antitrust_2001,January 12,2001-01-12
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos,santitos,santitos_2000,January 28,2000-01-28
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...,frank mcklusky ci,frank mcklusky ci_2002,NaN,NaT
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...,a walk to remember,a walk to remember_2002,January 25,2002-01-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30607,2021,January 1st,Jokbeoldu sinmun iyagi,Documentary,12356.0,NaN,12356.0,NaN,NaN,NaN,NaN,168.0,NaN,Factual,https://www.the-numbers.com/movie/Jokbeoldu-si...,jokbeoldu sinmun iyagi,jokbeoldu sinmun iyagi_2021,January 1,2021-01-01
30608,2021,March 5th,My Salinger Year,Drama,914119.0,54730.0,968849.0,NaN,28851.0,123.0,2.0,101.0,Set in New York City,Contemporary Fiction,https://www.the-numbers.com/movie/My-Salinger-...,my salinger year,my salinger year_2021,March 5,2021-03-05
30609,2021,January 1st,Escort Vehicle 36,Action,240000.0,NaN,240000.0,NaN,NaN,NaN,NaN,85.0,NaN,Historical Fiction,https://www.the-numbers.com/movie/Escort-Vehic...,escort vehicle 36,escort vehicle 36_2021,January 1,2021-01-01
30610,2021,May 21st,The Dry,Thriller/Suspense,16987526.0,364397.0,17351923.0,NaN,119364.0,186.0,2.5,118.0,Crime Thriller,Contemporary Fiction,https://www.the-numbers.com/movie/Dry-The-(Aus...,the dry,the dry_2021,May 21,2021-05-21
30611,2021,January 1st,Posledniy bogatyr. KorenÃ¢â‚¬â„¢ Zla,Adventure,33396899.0,NaN,33396899.0,NaN,NaN,NaN,NaN,NaN,NaN,Super Hero,https://www.the-numbers.com/movie/Posledniy-bo...,posledniy bogatyr korenãââ zla,posledniy bogatyr korenãââ zla_2021,January 1,2021-01-01

## 6. Expert and user review cleaning — CleaningExpertAndUserReviews22septFINISHEDCLEANING.ipynb

In [3]:
import pandas as pd

df3 = pd.read_csv(
    "UserReviews43DylanDMB.csv",
    encoding="latin1"
    # Use latin1 encoding so pandas can correctly read special characters in the CSV file
)

df4 = pd.read_csv(
    "ExpertReviewsClean43LIWCforDMB.csv",
    encoding="latin1"
    # Use latin1 encoding so pandas can correctly read special characters in the CSV file
)

C:\Users\dylansodhi\AppData\Local\Temp\ipykernel_2648\611161027.py:3: DtypeWarning: Columns (0: idvscore, 1: thumbsUp, 2: thumbsTot) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv(

In [4]:
# to see the columns of each files:
print(df3.columns.tolist())
print(df4.columns.tolist())

['url', 'idvscore', 'reviewer', 'dateP', 'Rev', 'thumbsUp', 'thumbsTot', 'WC', 'Analytic', 'Clout', 'Authentic', 'Tone', 'WPS', 'Sixltr', 'Dic', 'function', 'pronoun', 'ppron', 'i', 'we', 'you', 'shehe', 'they', 'ipron', 'article', 'prep', 'auxverb', 'adverb', 'conj', 'negate', 'verb', 'adj', 'compare', 'interrog', 'number', 'quant', 'affect', 'posemo', 'negemo', 'anx', 'anger', 'sad', 'social', 'family', 'friend', 'female', 'male', 'cogproc', 'insight', 'cause', 'discrep', 'tentat', 'certain', 'differ', 'percept', 'see', 'hear', 'feel', 'bio', 'body', 'health', 'sexual', 'ingest', 'drives', 'affiliation', 'achieve', 'power', 'reward', 'risk', 'focuspast', 'focuspresent', 'focusfuture', 'relativ', 'motion', 'space', 'time', 'work', 'leisure', 'home', 'money', 'relig', 'death', 'informal', 'swear', 'netspeak', 'assent', 'nonflu', 'filler', 'AllPunc', 'Period', 'Comma', 'Colon', 'SemiC', 'QMark', 'Exclam', 'Dash', 'Quote', 'Apostro', 'Parenth', 'OtherP']
['url', 'idvscore', 'reviewer', 'dateP', 'Rev', 'WC', 'Analytic', 'Clout', 'Authentic', 'Tone', 'WPS', 'Sixltr', 'Dic', 'function', 'pronoun', 'ppron', 'i', 'we', 'you', 'shehe', 'they', 'ipron', 'article', 'prep', 'auxverb', 'adverb', 'conj', 'negate', 'verb', 'adj', 'compare', 'interrog', 'number', 'quant', 'affect', 'posemo', 'negemo', 'anx', 'anger', 'sad', 'social', 'family', 'friend', 'female', 'male', 'cogproc', 'insight', 'cause', 'discrep', 'tentat', 'certain', 'differ', 'percept', 'see', 'hear', 'feel', 'bio', 'body', 'health', 'sexual', 'ingest', 'drives', 'affiliation', 'achieve', 'power', 'reward', 'risk', 'focuspast', 'focuspresent', 'focusfuture', 'relativ', 'motion', 'space', 'time', 'work', 'leisure', 'home', 'money', 'relig', 'death', 'informal', 'swear', 'netspeak', 'assent', 'nonflu', 'filler', 'AllPunc', 'Period', 'Comma', 'Colon', 'SemiC', 'QMark', 'Exclam', 'Dash', 'Quote', 'Apostro', 'Parenth', 'OtherP']

In [5]:
# to see the first 20 rows of title for each file
print(df3["reviewer"].head(20))
print(df4["reviewer"].head(20))

0       'Longbottom94'
1            'MartinB'
2             'Jaakko'
3              'CapoR'
4           'OrwellB.'
5             'RONGIU'
6        'Tokyochuchu'
7           'Fenrir81'
8            'cabrita'
9           'farknash'
10           'Spangle'
11         'Nesbitt10'
12        'TrilobiteG'
13          'Luxocell'
14        'TomBeltran'
15            'BrettT'
16         'Voltronix'
17     'LatinCritic13'
18       'MattBrady99'
19         'Ralfbergs'
Name: reviewer, dtype: str
0          "Andrew O'Hehir"
1              'A.O. Scott'
2                      None
3             'Noel Murray'
4         'Joshua Rothkopf'
5                      None
6        'Bill Goodykoontz'
7         'Kimberley Jones'
8           'Peter Travers'
9            'V.A. Musetto'
10        'David Hiltbrand'
11            'Roger Ebert'
12       'Michael Phillips'
13                'Ty Burr'
14             'Shawn Levy'
15                     None
16     'James Berardinelli'
17                     None
18             'Rick Groen'
19                     None
Name: reviewer, dtype: str

In [6]:
# Keep only the columns needed for the analysis and remove all unnecessary columns
# axis=1 tells pandas to remove columns instead of rows
df3 = df3.drop(df3.columns[5:], axis=1) 
df4 = df4.drop(df4.columns[7:], axis=1)

In [7]:
# Check the number of rows and columns in the dataframe
print(df3.shape)
print(df4.shape)

(319662, 5)
(238973, 7)

In [8]:
df3.head(20)

,url,idvscore,reviewer,dateP,Rev
0,https://www.metacritic.com/movie/bronson,8.0,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...
1,https://www.metacritic.com/movie/bronson,9.0,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...
2,https://www.metacritic.com/movie/bronson,10.0,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...
3,https://www.metacritic.com/movie/bronson,6.0,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...
4,https://www.metacritic.com/movie/bronson,8.0,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...
5,https://www.metacritic.com/movie/bronson,8.0,'RONGIU',"'Jun 10, 2011'","'Sorry, machine translation. The stage, by Ni..."
6,https://www.metacritic.com/movie/bronson,8.0,'Tokyochuchu',"'Nov 30, 2013'","'Bronson is a great, extremely strange movie ..."
7,https://www.metacritic.com/movie/bronson,7.0,'Fenrir81',"'Apr 22, 2011'",'Despite being flawed by a weak narrative str...
8,https://www.metacritic.com/movie/bronson,4.0,'cabrita',"'Aug 10, 2012'",'If valhalla rising was a weak version of agg...
9,https://www.metacritic.com/movie/bronson,10.0,'farknash',"'Aug 19, 2011'",'http://mikesharkey.blogspot.com/2009/04/igiz...
10,https://www.metacritic.com/movie/bronson,4.0,'Spangle',"'Mar 6, 2015'","'Extremely claustrophobic, Bronson is possibl..."
11,https://www.metacritic.com/movie/bronson,8.0,'Nesbitt10',"'Jul 4, 2013'",'One thing is for certain: Bronson invites yo...
12,https://www.metacritic.com/movie/bronson,5.0,'TrilobiteG',"'Jan 6, 2016'","'Got to say, I m rather disappointed. To begi..."
13,https://www.metacritic.com/movie/bronson,3.0,'Luxocell',"'Jan 16, 2015'","'Call me simple minded if you desire, but I r..."
14,https://www.metacritic.com/movie/bronson,5.0,'TomBeltran',"'May 27, 2013'",'Posted on 5/20/13 10:15 AM\rTom hardy gives ...
15,https://www.metacritic.com/movie/bronson,7.0,'BrettT',"'Jun 8, 2014'","'Well acted and gritty, Bronson is a good fil..."
16,https://www.metacritic.com/movie/bronson,8.0,'Voltronix',"'Aug 14, 2014'","'Tom Hardy nails it in this role, partially d..."
17,https://www.metacritic.com/movie/bronson,9.0,'LatinCritic13',"'Apr 7, 2019'",'Bronson is defined as a film that s notoriou...
18,https://www.metacritic.com/movie/bronson,9.0,'MattBrady99',"'Sep 9, 2015'",'Bronson follows the life of notorious prison...
19,https://www.metacritic.com/movie/bronson,5.0,'Ralfbergs',"'Jun 25, 2016'","'I really liked TOm Hardy s performance here,..."

In [9]:
df4.head(20)

,url,idvscore,reviewer,dateP,Rev,WC,Analytic
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46
5,https://www.metacritic.com/movie/bronson,80.0,None,None,"'He s neither victim nor hero, but a man who,...",17,59.32
6,https://www.metacritic.com/movie/bronson,80.0,'Bill Goodykoontz',None,"'This is unhinged genius, an amazing piece of...",16,93.26
7,https://www.metacritic.com/movie/bronson,78.0,'Kimberley Jones',None,'Refn s artful and energetic film never goes ...,12,62.04
8,https://www.metacritic.com/movie/bronson,75.0,'Peter Travers',None,'This movie and Hardy s electrifying performa...,13,65.46
9,https://www.metacritic.com/movie/bronson,75.0,'V.A. Musetto',None,'Tom Hardy gives an amazing performance as Pe...,20,99.00
10,https://www.metacritic.com/movie/bronson,75.0,'David Hiltbrand',None,"'The tone is surreal, at once visceral and cl...",20,78.30
11,https://www.metacritic.com/movie/bronson,75.0,'Roger Ebert',None,"'It is 92 minutes of rage, acted by Tom Hardy.'",10,93.26
12,https://www.metacritic.com/movie/bronson,75.0,'Michael Phillips',None,"'Hardy is remarkable, however. This is an act...",20,87.27
13,https://www.metacritic.com/movie/bronson,75.0,'Ty Burr',None,'Bronson isn t a story in the traditional sen...,30,99.00
14,https://www.metacritic.com/movie/bronson,75.0,'Shawn Levy',None,"'It s played with real zest and energy, and i...",24,27.87
15,https://www.metacritic.com/movie/bronson,70.0,None,None,"'With an intelligent, provocative and stylize...",27,99.00
16,https://www.metacritic.com/movie/bronson,63.0,'James Berardinelli',None,'It s lively and vivid but ends up leaving th...,26,88.90
17,https://www.metacritic.com/movie/bronson,60.0,None,None,"'Too smart/arty for the slasher set, and too ...",31,63.48
18,https://www.metacritic.com/movie/bronson,50.0,'Rick Groen',None,'Bronson is one of those based on a true stor...,26,99.00
19,https://www.metacritic.com/movie/bronson,30.0,None,None,"'Despite the artistic flourishes, this is sti...",26,97.95

In [10]:
# Check how many missing values each column has
print(df3.isnull().sum())

url            0
idvscore    3404
reviewer    3407
dateP       3413
Rev         3413
dtype: int64

In [11]:
print(df4.isnull().sum())

url         0
idvscore    2
reviewer    2
dateP       2
Rev         2
WC          0
Analytic    0
dtype: int64

In [12]:
# Check how many completely duplicated rows exist
print(df3.duplicated().sum())

929

In [13]:
print(df4.duplicated().sum())

27

In [14]:
# Show rows in df3 that contain at least one missing value
display(df3[df3.isnull().any(axis=1)].head(20))

,url,idvscore,reviewer,dateP,Rev
29,https://www.metacritic.com/movie/a-screaming-man,NaN,NaN,NaN,NaN
30,https://www.metacritic.com/movie/lovers-of-hate,NaN,NaN,NaN,NaN
34,https://www.metacritic.com/movie/viva-riva!,NaN,NaN,NaN,NaN
130,https://www.metacritic.com/movie/september-11,NaN,NaN,NaN,NaN
134,https://www.metacritic.com/movie/catching-out,NaN,NaN,NaN,NaN
185,https://www.metacritic.com/movie/norman,NaN,NaN,NaN,NaN
187,https://www.metacritic.com/movie/dumbstruck,NaN,NaN,NaN,NaN
277,https://www.metacritic.com/movie/the-catechism...,NaN,NaN,NaN,NaN
296,https://www.metacritic.com/movie/the-real-cancun,NaN,NaN,NaN,NaN
297,https://www.metacritic.com/movie/the-era-of-va...,NaN,NaN,NaN,NaN
762,https://www.metacritic.com/movie/emerald-cowboy,NaN,NaN,NaN,NaN
867,https://www.metacritic.com/movie/footprints,NaN,NaN,NaN,NaN
1049,https://www.metacritic.com/movie/a-love-affair...,NaN,NaN,NaN,NaN
1208,https://www.metacritic.com/movie/alls-faire-in...,NaN,NaN,NaN,NaN
1234,https://www.metacritic.com/movie/a-warriors-heart,NaN,NaN,NaN,NaN
1235,https://www.metacritic.com/movie/brothers-justice,NaN,NaN,NaN,NaN
1525,https://www.metacritic.com/movie/the-big-bang,NaN,NaN,NaN,NaN
2012,https://www.metacritic.com/movie/the-greening-...,NaN,NaN,NaN,NaN
2241,https://www.metacritic.com/movie/certifiably-j...,NaN,NaN,NaN,NaN
2242,https://www.metacritic.com/movie/salvation-bou...,NaN,NaN,NaN,NaN

In [15]:
display(df4[df4.isnull().any(axis=1)].head(20))

,url,idvscore,reviewer,dateP,Rev,WC,Analytic
41664,https://www.metacritic.com/movie/whiteout,NaN,NaN,NaN,NaN,0,0.0
157759,https://www.metacritic.com/movie/micmac---au-f...,NaN,NaN,NaN,NaN,0,0.0

In [16]:
df4.head(50)

,url,idvscore,reviewer,dateP,Rev,WC,Analytic
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46
5,https://www.metacritic.com/movie/bronson,80.0,None,None,"'He s neither victim nor hero, but a man who,...",17,59.32
6,https://www.metacritic.com/movie/bronson,80.0,'Bill Goodykoontz',None,"'This is unhinged genius, an amazing piece of...",16,93.26
7,https://www.metacritic.com/movie/bronson,78.0,'Kimberley Jones',None,'Refn s artful and energetic film never goes ...,12,62.04
8,https://www.metacritic.com/movie/bronson,75.0,'Peter Travers',None,'This movie and Hardy s electrifying performa...,13,65.46
9,https://www.metacritic.com/movie/bronson,75.0,'V.A. Musetto',None,'Tom Hardy gives an amazing performance as Pe...,20,99.00
10,https://www.metacritic.com/movie/bronson,75.0,'David Hiltbrand',None,"'The tone is surreal, at once visceral and cl...",20,78.30
11,https://www.metacritic.com/movie/bronson,75.0,'Roger Ebert',None,"'It is 92 minutes of rage, acted by Tom Hardy.'",10,93.26
12,https://www.metacritic.com/movie/bronson,75.0,'Michael Phillips',None,"'Hardy is remarkable, however. This is an act...",20,87.27
13,https://www.metacritic.com/movie/bronson,75.0,'Ty Burr',None,'Bronson isn t a story in the traditional sen...,30,99.00
14,https://www.metacritic.com/movie/bronson,75.0,'Shawn Levy',None,"'It s played with real zest and energy, and i...",24,27.87
15,https://www.metacritic.com/movie/bronson,70.0,None,None,"'With an intelligent, provocative and stylize...",27,99.00
16,https://www.metacritic.com/movie/bronson,63.0,'James Berardinelli',None,'It s lively and vivid but ends up leaving th...,26,88.90
17,https://www.metacritic.com/movie/bronson,60.0,None,None,"'Too smart/arty for the slasher set, and too ...",31,63.48
18,https://www.metacritic.com/movie/bronson,50.0,'Rick Groen',None,'Bronson is one of those based on a true stor...,26,99.00
19,https://www.metacritic.com/movie/bronson,30.0,None,None,"'Despite the artistic flourishes, this is sti...",26,97.95
20,https://www.metacritic.com/movie/bronson,30.0,'J. Hoberman',None,"'Bronson is essentially a faux-operatic, musi...",17,97.21
21,https://www.metacritic.com/movie/bronson,25.0,'Walter Addiego',None,'It s an assaultive work about an assaultive ...,9,98.87
22,https://www.metacritic.com/movie/disgrace,100.0,'Roger Ebert',None,'This is such a rare movie. Its characters ar...,14,14.58
23,https://www.metacritic.com/movie/disgrace,90.0,'Stephen Holden',None,'Mr. Malkovich is one of the few actors capab...,14,99.00
24,https://www.metacritic.com/movie/disgrace,83.0,'Peter Rainer',None,"'As fiercely unsentimental as Disgrace is, it...",29,69.54
25,https://www.metacritic.com/movie/disgrace,80.0,None,None,"'The austere economy of Coetzee s writing, cr...",24,99.00
26,https://www.metacritic.com/movie/disgrace,80.0,'Bob Mondello',None,'John Malkovich has played some odd ducks in ...,32,95.70
27,https://www.metacritic.com/movie/disgrace,80.0,None,None,'Surprisingly successful adaptation of J. M. ...,10,98.58
28,https://www.metacritic.com/movie/disgrace,75.0,'V.A. Musetto',None,'I cannot tell a lie. I derive great satisfac...,13,43.96
29,https://www.metacritic.com/movie/disgrace,75.0,'Lisa Schwarzbaum',None,'Newcomer Jessica Haines is transparent and h...,22,98.34
30,https://www.metacritic.com/movie/disgrace,75.0,'Ty Burr',None,"'It s a harsh experience, at times engrossing...",32,93.26
31,https://www.metacritic.com/movie/disgrace,70.0,'Eddie Cockrell',None,'Anchored by another marvelously quirky yet d...,39,95.33
32,https://www.metacritic.com/movie/disgrace,70.0,'J.R. Jones',None,'The movie eventually begins to wilt under th...,40,99.00
33,https://www.metacritic.com/movie/disgrace,70.0,'Joe Morgenstern',None,"'Nothing is simple in this film, which ramifi...",28,98.76
34,https://www.metacritic.com/movie/disgrace,70.0,None,None,"'Absorbing but often bloodless and, frankly, ...",7,5.89
35,https://www.metacritic.com/movie/disgrace,67.0,'Keith Phipps',None,'After a compelling opening act and some shoc...,24,99.00
36,https://www.metacritic.com/movie/disgrace,60.0,None,None,'The story often appears a little unreal.',7,99.00
37,https://www.metacritic.com/movie/disgrace,60.0,'Philip Kennicott',None,'Is it a great movie? John Malkovich s portra...,28,93.26
38,https://www.metacritic.com/movie/disgrace,40.0,None,None,'A frustrating film full of overplayed men-as...,28,68.29
39,https://www.metacritic.com/movie/disgrace,40.0,'Joe Neumaier',None,"'The film, unfortunately, hasn t the depth Ma...",12,99.00
40,https://www.metacritic.com/movie/a-screaming-man,90.0,'Manohla Dargis',"'Apr 14, 2011'","'It s a modest film, if only in scale and app...",42,97.73
41,https://www.metacritic.com/movie/a-screaming-man,83.0,'Eric Kohn',"'Apr 12, 2011'","'At its core, A Screaming Man emphasizes the ...",27,93.26
42,https://www.metacritic.com/movie/a-screaming-man,80.0,'Robert Koehler',"'May 26, 2013'",'Haroun s tender but unsentimental regard for...,25,93.26
43,https://www.metacritic.com/movie/a-screaming-man,80.0,'David Fear',"'Apr 12, 2011'",'A collective sense of psychological turmoil ...,43,99.00
44,https://www.metacritic.com/movie/a-screaming-man,70.0,None,"'Apr 12, 2011'",'Haroun is uninterested in big war scenes and...,17,97.21
45,https://www.metacritic.com/movie/a-screaming-man,60.0,None,"'Apr 16, 2011'",'The first half-hour is as evocative as (and ...,38,95.37
46,https://www.metacritic.com/movie/a-screaming-man,60.0,'Joe Neumaier',"'Apr 15, 2011'",'Haroun is achingly conscious of day-to-day d...,21,29.30
47,https://www.metacritic.com/movie/a-screaming-man,50.0,'Nick Pinkerton',"'Apr 12, 2011'",'The characterizations never comfortably acco...,18,46.37
48,https://www.metacritic.com/movie/lovers-of-hate,91.0,'Eric Kohn',"'Feb 10, 2011'",'Never indulging in outright scare tactics or...,21,93.26
49,https://www.metacritic.com/movie/lovers-of-hate,90.0,'Jeannette Catsoulis',"'Feb 10, 2011'","'Smartly written and flawlessly acted, Lovers...",27,66.94

In [17]:
# Creates a new column by extracting the movie title from the end of the URL
df3["title_from_url"] = df3["url"].str.rsplit("/", n=1).str[-1]

In [18]:
df3.head(30)

,url,idvscore,reviewer,dateP,Rev,title_from_url
0,https://www.metacritic.com/movie/bronson,8.0,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...,bronson
1,https://www.metacritic.com/movie/bronson,9.0,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...,bronson
2,https://www.metacritic.com/movie/bronson,10.0,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...,bronson
3,https://www.metacritic.com/movie/bronson,6.0,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...,bronson
4,https://www.metacritic.com/movie/bronson,8.0,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...,bronson
5,https://www.metacritic.com/movie/bronson,8.0,'RONGIU',"'Jun 10, 2011'","'Sorry, machine translation. The stage, by Ni...",bronson
6,https://www.metacritic.com/movie/bronson,8.0,'Tokyochuchu',"'Nov 30, 2013'","'Bronson is a great, extremely strange movie ...",bronson
7,https://www.metacritic.com/movie/bronson,7.0,'Fenrir81',"'Apr 22, 2011'",'Despite being flawed by a weak narrative str...,bronson
8,https://www.metacritic.com/movie/bronson,4.0,'cabrita',"'Aug 10, 2012'",'If valhalla rising was a weak version of agg...,bronson
9,https://www.metacritic.com/movie/bronson,10.0,'farknash',"'Aug 19, 2011'",'http://mikesharkey.blogspot.com/2009/04/igiz...,bronson
10,https://www.metacritic.com/movie/bronson,4.0,'Spangle',"'Mar 6, 2015'","'Extremely claustrophobic, Bronson is possibl...",bronson
11,https://www.metacritic.com/movie/bronson,8.0,'Nesbitt10',"'Jul 4, 2013'",'One thing is for certain: Bronson invites yo...,bronson
12,https://www.metacritic.com/movie/bronson,5.0,'TrilobiteG',"'Jan 6, 2016'","'Got to say, I m rather disappointed. To begi...",bronson
13,https://www.metacritic.com/movie/bronson,3.0,'Luxocell',"'Jan 16, 2015'","'Call me simple minded if you desire, but I r...",bronson
14,https://www.metacritic.com/movie/bronson,5.0,'TomBeltran',"'May 27, 2013'",'Posted on 5/20/13 10:15 AM\rTom hardy gives ...,bronson
15,https://www.metacritic.com/movie/bronson,7.0,'BrettT',"'Jun 8, 2014'","'Well acted and gritty, Bronson is a good fil...",bronson
16,https://www.metacritic.com/movie/bronson,8.0,'Voltronix',"'Aug 14, 2014'","'Tom Hardy nails it in this role, partially d...",bronson
17,https://www.metacritic.com/movie/bronson,9.0,'LatinCritic13',"'Apr 7, 2019'",'Bronson is defined as a film that s notoriou...,bronson
18,https://www.metacritic.com/movie/bronson,9.0,'MattBrady99',"'Sep 9, 2015'",'Bronson follows the life of notorious prison...,bronson
19,https://www.metacritic.com/movie/bronson,5.0,'Ralfbergs',"'Jun 25, 2016'","'I really liked TOm Hardy s performance here,...",bronson
20,https://www.metacritic.com/movie/bronson,8.0,'nbock',"'Aug 26, 2015'",'While Bronson does take several creative lib...,bronson
21,https://www.metacritic.com/movie/bronson,3.0,'Broyax',"'Jan 27, 2017'","'J avais vu la bande-annonce, tr s dr le, et ...",bronson
22,https://www.metacritic.com/movie/bronson,7.0,'AndrewBurge',"'Jan 31, 2019'",'This film is so British that I want to send ...,bronson
23,https://www.metacritic.com/movie/bronson,6.0,'ahmedaiman1999',"'Mar 20, 2019'",'This is definitely a one-of-a-kind character...,bronson
24,https://www.metacritic.com/movie/bronson,10.0,'Mclovin69',"'Apr 5, 2021'","'The movie was hilarious, Michael peterson wa...",bronson
25,https://www.metacritic.com/movie/bronson,9.0,'TUMBLERok',"'Jun 22, 2020'","' , , . . ! . , , . . ! . , , Bronson . . . 9...",bronson
26,https://www.metacritic.com/movie/bronson,9.0,'Honestyopinons',"'Jun 27, 2020'",'one of the best movies about insanity withou...,bronson
27,https://www.metacritic.com/movie/disgrace,0.0,'Nazgulero',"'Feb 27, 2011'",'After watching this horrible movie for thirt...,disgrace
28,https://www.metacritic.com/movie/disgrace,10.0,'wwh',"'Aug 2, 2011'",'Re: seems quite disgusted by him right from ...,disgrace
29,https://www.metacritic.com/movie/a-screaming-man,NaN,NaN,NaN,NaN,a-screaming-man

In [19]:
df4["title_from_url"] = df4["url"].str.rsplit("/", n=1).str[-1]

In [20]:
df4.head(30)

,url,idvscore,reviewer,dateP,Rev,WC,Analytic,title_from_url
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88,bronson
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07,bronson
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69,bronson
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46,bronson
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46,bronson
5,https://www.metacritic.com/movie/bronson,80.0,None,None,"'He s neither victim nor hero, but a man who,...",17,59.32,bronson
6,https://www.metacritic.com/movie/bronson,80.0,'Bill Goodykoontz',None,"'This is unhinged genius, an amazing piece of...",16,93.26,bronson
7,https://www.metacritic.com/movie/bronson,78.0,'Kimberley Jones',None,'Refn s artful and energetic film never goes ...,12,62.04,bronson
8,https://www.metacritic.com/movie/bronson,75.0,'Peter Travers',None,'This movie and Hardy s electrifying performa...,13,65.46,bronson
9,https://www.metacritic.com/movie/bronson,75.0,'V.A. Musetto',None,'Tom Hardy gives an amazing performance as Pe...,20,99.00,bronson
10,https://www.metacritic.com/movie/bronson,75.0,'David Hiltbrand',None,"'The tone is surreal, at once visceral and cl...",20,78.30,bronson
11,https://www.metacritic.com/movie/bronson,75.0,'Roger Ebert',None,"'It is 92 minutes of rage, acted by Tom Hardy.'",10,93.26,bronson
12,https://www.metacritic.com/movie/bronson,75.0,'Michael Phillips',None,"'Hardy is remarkable, however. This is an act...",20,87.27,bronson
13,https://www.metacritic.com/movie/bronson,75.0,'Ty Burr',None,'Bronson isn t a story in the traditional sen...,30,99.00,bronson
14,https://www.metacritic.com/movie/bronson,75.0,'Shawn Levy',None,"'It s played with real zest and energy, and i...",24,27.87,bronson
15,https://www.metacritic.com/movie/bronson,70.0,None,None,"'With an intelligent, provocative and stylize...",27,99.00,bronson
16,https://www.metacritic.com/movie/bronson,63.0,'James Berardinelli',None,'It s lively and vivid but ends up leaving th...,26,88.90,bronson
17,https://www.metacritic.com/movie/bronson,60.0,None,None,"'Too smart/arty for the slasher set, and too ...",31,63.48,bronson
18,https://www.metacritic.com/movie/bronson,50.0,'Rick Groen',None,'Bronson is one of those based on a true stor...,26,99.00,bronson
19,https://www.metacritic.com/movie/bronson,30.0,None,None,"'Despite the artistic flourishes, this is sti...",26,97.95,bronson
20,https://www.metacritic.com/movie/bronson,30.0,'J. Hoberman',None,"'Bronson is essentially a faux-operatic, musi...",17,97.21,bronson
21,https://www.metacritic.com/movie/bronson,25.0,'Walter Addiego',None,'It s an assaultive work about an assaultive ...,9,98.87,bronson
22,https://www.metacritic.com/movie/disgrace,100.0,'Roger Ebert',None,'This is such a rare movie. Its characters ar...,14,14.58,disgrace
23,https://www.metacritic.com/movie/disgrace,90.0,'Stephen Holden',None,'Mr. Malkovich is one of the few actors capab...,14,99.00,disgrace
24,https://www.metacritic.com/movie/disgrace,83.0,'Peter Rainer',None,"'As fiercely unsentimental as Disgrace is, it...",29,69.54,disgrace
25,https://www.metacritic.com/movie/disgrace,80.0,None,None,"'The austere economy of Coetzee s writing, cr...",24,99.00,disgrace
26,https://www.metacritic.com/movie/disgrace,80.0,'Bob Mondello',None,'John Malkovich has played some odd ducks in ...,32,95.70,disgrace
27,https://www.metacritic.com/movie/disgrace,80.0,None,None,'Surprisingly successful adaptation of J. M. ...,10,98.58,disgrace
28,https://www.metacritic.com/movie/disgrace,75.0,'V.A. Musetto',None,'I cannot tell a lie. I derive great satisfac...,13,43.96,disgrace
29,https://www.metacritic.com/movie/disgrace,75.0,'Lisa Schwarzbaum',None,'Newcomer Jessica Haines is transparent and h...,22,98.34,disgrace

In [21]:
# Show rows where all important review information is missing
missing_reviews = df3[
    df3[["idvscore", "reviewer", "dateP", "Rev"]]
    .isnull()
    .all(axis=1)
]

display(missing_reviews.head())
print(len(missing_reviews))

,url,idvscore,reviewer,dateP,Rev,title_from_url
29,https://www.metacritic.com/movie/a-screaming-man,NaN,NaN,NaN,NaN,a-screaming-man
30,https://www.metacritic.com/movie/lovers-of-hate,NaN,NaN,NaN,NaN,lovers-of-hate
34,https://www.metacritic.com/movie/viva-riva!,NaN,NaN,NaN,NaN,viva-riva!
130,https://www.metacritic.com/movie/september-11,NaN,NaN,NaN,NaN,september-11
134,https://www.metacritic.com/movie/catching-out,NaN,NaN,NaN,NaN,catching-out

3403

In [22]:
print(df3.isnull().sum())

url                  0
idvscore          3404
reviewer          3407
dateP             3413
Rev               3413
title_from_url       0
dtype: int64

In [23]:
# Delete rows that contain more than 2 null values
df3 = df3[df3.isnull().sum(axis=1) <= 2]

In [24]:
df4 = df4[df4.isnull().sum(axis=1) <= 2]

In [26]:
print(df3.isnull().sum())

url               0
idvscore          0
reviewer          0
dateP             5
Rev               5
title_from_url    0
dtype: int64

In [27]:
print(df4.isnull().sum())

url               0
idvscore          0
reviewer          0
dateP             0
Rev               0
WC                0
Analytic          0
title_from_url    0
dtype: int64

In [29]:
display(df3[df3.isnull().any(axis=1)].head())

,url,idvscore,reviewer,dateP,Rev,title_from_url
124298,https://www.metacritic.com/movie/rogue-one-a-s...,cargo carriers,storm-troopers,NaN,NaN,rogue-one-a-star-wars-story
260515,https://www.metacritic.com/movie/the-dark-knight,10.0,'{Nobody,NaN,NaN,the-dark-knight
271313,https://www.metacritic.com/movie/eragon,0,'[Anonymous,NaN,NaN,eragon
290080,https://www.metacritic.com/movie/before-the-de...,10.0,'[Anonymous,NaN,NaN,before-the-devil-knows-youre-dead
297409,https://www.metacritic.com/movie/children-of-men,10.0,"'Lance""The\'OlP""Romance', 'date_published': '...",NaN,NaN,children-of-men

In [32]:
df3.head(20)

,url,idvscore,reviewer,dateP,Rev,title_from_url
0,https://www.metacritic.com/movie/bronson,8.0,'Longbottom94',"'Apr 25, 2013'",'Many have dismissed this film for not explor...,bronson
1,https://www.metacritic.com/movie/bronson,9.0,'MartinB',"'Oct 13, 2009'",'Anyone who doesn t like this movie simply ju...,bronson
2,https://www.metacritic.com/movie/bronson,10.0,'Jaakko',"'Jul 19, 2012'",'Not sure what to think at this film at first...,bronson
3,https://www.metacritic.com/movie/bronson,6.0,'CapoR',"'Oct 13, 2009'",'Nicely portrayed but it lacks the elements t...,bronson
4,https://www.metacritic.com/movie/bronson,8.0,'OrwellB.',"'Oct 10, 2009'",'Bronson is more than entertainment. It is ar...,bronson
5,https://www.metacritic.com/movie/bronson,8.0,'RONGIU',"'Jun 10, 2011'","'Sorry, machine translation. The stage, by Ni...",bronson
6,https://www.metacritic.com/movie/bronson,8.0,'Tokyochuchu',"'Nov 30, 2013'","'Bronson is a great, extremely strange movie ...",bronson
7,https://www.metacritic.com/movie/bronson,7.0,'Fenrir81',"'Apr 22, 2011'",'Despite being flawed by a weak narrative str...,bronson
8,https://www.metacritic.com/movie/bronson,4.0,'cabrita',"'Aug 10, 2012'",'If valhalla rising was a weak version of agg...,bronson
9,https://www.metacritic.com/movie/bronson,10.0,'farknash',"'Aug 19, 2011'",'http://mikesharkey.blogspot.com/2009/04/igiz...,bronson
10,https://www.metacritic.com/movie/bronson,4.0,'Spangle',"'Mar 6, 2015'","'Extremely claustrophobic, Bronson is possibl...",bronson
11,https://www.metacritic.com/movie/bronson,8.0,'Nesbitt10',"'Jul 4, 2013'",'One thing is for certain: Bronson invites yo...,bronson
12,https://www.metacritic.com/movie/bronson,5.0,'TrilobiteG',"'Jan 6, 2016'","'Got to say, I m rather disappointed. To begi...",bronson
13,https://www.metacritic.com/movie/bronson,3.0,'Luxocell',"'Jan 16, 2015'","'Call me simple minded if you desire, but I r...",bronson
14,https://www.metacritic.com/movie/bronson,5.0,'TomBeltran',"'May 27, 2013'",'Posted on 5/20/13 10:15 AM\rTom hardy gives ...,bronson
15,https://www.metacritic.com/movie/bronson,7.0,'BrettT',"'Jun 8, 2014'","'Well acted and gritty, Bronson is a good fil...",bronson
16,https://www.metacritic.com/movie/bronson,8.0,'Voltronix',"'Aug 14, 2014'","'Tom Hardy nails it in this role, partially d...",bronson
17,https://www.metacritic.com/movie/bronson,9.0,'LatinCritic13',"'Apr 7, 2019'",'Bronson is defined as a film that s notoriou...,bronson
18,https://www.metacritic.com/movie/bronson,9.0,'MattBrady99',"'Sep 9, 2015'",'Bronson follows the life of notorious prison...,bronson
19,https://www.metacritic.com/movie/bronson,5.0,'Ralfbergs',"'Jun 25, 2016'","'I really liked TOm Hardy s performance here,...",bronson

In [33]:
df4.head(20)

,url,idvscore,reviewer,dateP,Rev,WC,Analytic,title_from_url
0,https://www.metacritic.com/movie/bronson,100.0,"""Andrew O'Hehir""",None,'Bronson owes a little or a lot to Kubrick s ...,25,73.88,bronson
1,https://www.metacritic.com/movie/bronson,90.0,'A.O. Scott',None,'Bronson invites you to admire its protagonis...,30,13.07,bronson
2,https://www.metacritic.com/movie/bronson,90.0,None,None,'Whether it s Peterson/Bronson s more theatri...,40,72.69,bronson
3,https://www.metacritic.com/movie/bronson,83.0,'Noel Murray',None,'There are two Bronsons on display here: the ...,39,65.46,bronson
4,https://www.metacritic.com/movie/bronson,80.0,'Joshua Rothkopf',None,'Refn has somehow found his way to an authent...,24,88.46,bronson
5,https://www.metacritic.com/movie/bronson,80.0,None,None,"'He s neither victim nor hero, but a man who,...",17,59.32,bronson
6,https://www.metacritic.com/movie/bronson,80.0,'Bill Goodykoontz',None,"'This is unhinged genius, an amazing piece of...",16,93.26,bronson
7,https://www.metacritic.com/movie/bronson,78.0,'Kimberley Jones',None,'Refn s artful and energetic film never goes ...,12,62.04,bronson
8,https://www.metacritic.com/movie/bronson,75.0,'Peter Travers',None,'This movie and Hardy s electrifying performa...,13,65.46,bronson
9,https://www.metacritic.com/movie/bronson,75.0,'V.A. Musetto',None,'Tom Hardy gives an amazing performance as Pe...,20,99.00,bronson
10,https://www.metacritic.com/movie/bronson,75.0,'David Hiltbrand',None,"'The tone is surreal, at once visceral and cl...",20,78.30,bronson
11,https://www.metacritic.com/movie/bronson,75.0,'Roger Ebert',None,"'It is 92 minutes of rage, acted by Tom Hardy.'",10,93.26,bronson
12,https://www.metacritic.com/movie/bronson,75.0,'Michael Phillips',None,"'Hardy is remarkable, however. This is an act...",20,87.27,bronson
13,https://www.metacritic.com/movie/bronson,75.0,'Ty Burr',None,'Bronson isn t a story in the traditional sen...,30,99.00,bronson
14,https://www.metacritic.com/movie/bronson,75.0,'Shawn Levy',None,"'It s played with real zest and energy, and i...",24,27.87,bronson
15,https://www.metacritic.com/movie/bronson,70.0,None,None,"'With an intelligent, provocative and stylize...",27,99.00,bronson
16,https://www.metacritic.com/movie/bronson,63.0,'James Berardinelli',None,'It s lively and vivid but ends up leaving th...,26,88.90,bronson
17,https://www.metacritic.com/movie/bronson,60.0,None,None,"'Too smart/arty for the slasher set, and too ...",31,63.48,bronson
18,https://www.metacritic.com/movie/bronson,50.0,'Rick Groen',None,'Bronson is one of those based on a true stor...,26,99.00,bronson
19,https://www.metacritic.com/movie/bronson,30.0,None,None,"'Despite the artistic flourishes, this is sti...",26,97.95,bronson